jaxrs/providers/resteasy-validator-provider-11/pom.xml
jaxrs/security/resteasy-oauth/src/main/java/org/jboss/resteasy/auth/oauth/OAuthUtils.java

Added cdi-api dep to resteasy-validator-provider-11 since it use javax.enterprise.inject.spi.
Added import for ArrayList in org.jboss.resteasy.auth.oauth.OAuthUtils since it used in code.

Build: dependency and import fixes

---

README.md

It looks like the issues section on github is no longer used.
Remove the reference to those from the readme.

Update readme. Remove github issues that are no longer used

---

jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java

Details:
Fix for RESTEASY-1113: HttpHeaders.getAcceptableMediaTypes() doesn't comply with JAX-RS 2.0 spec
https://issues.jboss.org/browse/RESTEASY-1113
Updated getAcceptableMediaTypes() to return Wildcard media type in case no acceptable media types are specified

Update to ResteasyHttpHeaders.java

---

jaxrs/providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/Jackson2JsonpInterceptor.java
jaxrs/providers/jackson2/src/test/java/org/jboss/resteasy/test/nextgen/providers/jackson/JacksonTest.java

`Jackson2JsonpInterceptor` does not render closing bracket because the underlying OutputStream is closed. 
So
`foo({"foo":"bar"}`
Is rendered instead of
`foo({"foo":"bar"})`

Resteasy-1168: Jackson2JsonpInterceptor does not render closing bracket

---

jaxrs/server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java

I added a hook to insert http related handlers between the Netty and the RestEasy ones.
I also refactored the start method to remove code duplication and made it easier to read by extracting some code into separate methods.
Please note that setting the channelOptions and the childChannelOptions was previously only being executed for Https requests. I believe this is a bug and I have moved it so it executes for Http and Https requests alike.

Resteasy 1171 add hooks for http handlers

---

jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java

The user warning when the 2nd registration of the *class* provider is attempted.
This is documented as user should get warning in the javax.ws.rs.core.Configurable interface.
The 2nd registration of the *instance* provider gives the warning.

RESTEASY-1185 - Missing warning 2nd registration of the *class* provider

---

jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java

client.property(some_property, null) should remove property from client configuration.

RESTEASY-1184: Cannot remove property from client configuration

---

jaxrs/jboss-modules/lib.xml
jaxrs/jboss-modules/pom.xml
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/client/ApacheHttpClient4Test.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/asynch/AsynchTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/client/ApacheHttpClient4Test.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/xxe/TestXXE.java

https://issues.jboss.org/browse/RESTEASY-1213
fix Resteasy master build problem with JDK 8. After this change, both JDK7 and JDK8 can BUILD SUCCESS with "mvn clean install"
Also set a bigger connection timeout to avoid ApacheHttpClient4Test intermittent failure as reported in one of travis build https://s3.amazonaws.com/archive.travis-ci.org/jobs/74869505/log.txt 
Test failed with "ConnectionPoolTimeoutException: Timeout waiting for connection from pool", I think the connection timeout it too short to let garbage collector to finish itself. (I never see this test failure in my local test run)
I disabled two tests to avoid intermittent failures on travis-ci build as well, now that latest build output is "All checks have passed". I propose to use …

RESTEASY-1213, fix build problem with JDK 8.

---

jaxrs/server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyUtil.java
jaxrs/server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/NettyTest.java

Correctly handle requests with an absolute URI in the request line, like:
```
GET http://www.example.com/testContent HTTP/1.1
Host: www.example.com
```
This is required per the spec: http://tools.ietf.org/html/rfc2616#section-5, specifically: 
> To allow for transition to absoluteURIs in all requests in future versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI form in requests, even though HTTP/1.1 clients will only generate them in requests to proxies.
And:
> If Request-URI is an absoluteURI, the host is part of the Request-URI. Any Host header field value in the request MUST be ignored.
Issue: https://issues.jboss.org/browse/RESTEASY-1193

[Netty4] Correct handling for absolute URIs in HTTP request lines

---

jaxrs/docbook/reference/en/en-US/modules/Json.xml
jaxrs/providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/Jackson2JsonpInterceptor.java
jaxrs/providers/jackson2/src/test/java/org/jboss/resteasy/test/nextgen/providers/jackson/JacksonTest.java

I suggest wrapping the JSONP callback in a try-catch block.
It will prevent some browsers like MSIE to shown an error window when the specified callback function doesn't exist

[RESTEASY-1190] Wrap JSONP response in try-catch block

---

jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java

If you are creating your own thread pool and giving it to the client for exclusive use,
you probably want the executor cleaned up when the client is closed.

Allow setting of 'cleanupExecutor' property for custom executors on client builder

---

jaxrs/resteasy-guice/src/main/java/org/jboss/resteasy/plugins/guice/ModuleProcessor.java

For guice, if you want to bind() a generic type you have to use the
TypeLiteral class. The type however is not of Class and the registration of class's annotated with
@Provider were being ommited.
see: https://github.com/google/guice/wiki/FrequentlyAskedQuestions#how-to-inject-class-with-generic-type

Guice fix: Register generic @Providers

---

jaxrs/providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java

resteasy-jackson2 is incompatible with jackson 2.6 because it uses methods that were deprecated in 2.2 and 2.3 and have been removed.

resteasy-jackson2: switch to non-deprecated jackson2 methods

---

jaxrs/resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/InfinispanCache.java
jaxrs/resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/SimpleServerCache.java
jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/CacheEntry.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/cache/CacheEntry.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/cache/MapCache.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilder.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/WeightedMediaType.java
jaxrs/security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/doseta/DosetaKeyRepository.java

* Use long type in time comparision in cache classes:
* InfinispanCache.java
* SimpleServerCache.java
* CacheEntry.java
* Use correct key during cache cleanup
* Add prevention for NullPointerException in WeightedMediaType.java
* Remove duplicite code in ResteasyUriBuilder

Resteasy 1248 - Fix cache expired time and prevent for NullPointerException

---

jaxrs/tjws/src/main/java/Acme/Serve/Serve.java

As a developer, I am not interested in the value of the "keepalive" variable. I also don't care if the "Servlet for path '/' already defined and no default will be used." Yet my IDE (and maven) tells me this for every integration test I run.
There are some other places as well where I get unwanted output.
If desired, a logging framework like JUL could be a suitable replacement.

remove use of System.out.println for logging

---

jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/PathSegmentImpl.java

When sending matrixParams that are not defined (like ;a;b=1;c=2, where a is not defined) a 404 Not found will be returned. Instead it should just ignore the value and fullfill the reuqest, therefor a check for an empty String is necessary.

Support for not defined Matrix Parameter

---

jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Encode.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/specimpl/ResteasyUriBuilderTest.java

Use queryStringEncoding instead of queryNameValueEncoding for encoding
the fragment part of a URI

RESTEASY-1261 Use queryStringEncoding for the fragment

---

jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java

https://issues.jboss.org/browse/RESTEASY-1256
unable to inject Configuration resource due to missing Configuration.class in context data.

RESTEASY-1256 missing Configuration resource in context data

---

jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/annotations/Query.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/QueryInjector.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/Parameter.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/methodparams/QueryParamTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/methodparams/QueryTest.java

Add an option to use a @Query parameter to map parameters to an object.
I started out with [Issue-715](https://issues.jboss.org/browse/RESTEASY-715), but ended up doing this instead.
I know this is not what is asked for in the issue, but maybe it could be handy?

Resteasy query

---

jaxrs/pom.xml
jaxrs/providers/resteasy-validator-provider-11/pom.xml

`resteasy-validator-provider-11` currently ships with Hibernate Validator 5.0.1 which is rather old and contains a memory leaks: [HV-838](https://hibernate.atlassian.net/browse/HV-838).
This pull request makes `resteasy-validator-provider-11` use the Hibernate Validator version defined in the main `pom.xml` and updates it to Hibernate Validator 5.1.3.
`dep.hibernate-validator.version` is not used anywhere else in the project in the moment. I suspect it got abandoned when `resteasy-hibernatevalidator-provider` got split.

Update Hibernate Validator in resteasy-validator-provider-11

---

jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/NoContentStreamingCloseTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/InputStreamProvider.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/ReaderProvider.java

Fixing a HttpClient-ConnectionLeak we encountered when downloading 0Byte-Files with the Restclient.
It seems this bug was originally introduced in a large commit f846687fced7 "tck fixes and oauth2 fixes", probably when changing similar non-streaming MessageBodyReaderWriter but without regard to the special streaming MessageBodyReaderWriter for InputStream or Readers.

Fix Httpclient-Connectionleak for InputStream or Reader and Content-Length 0

---

jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/entity/TestGetEntity.java

ClientResponse in resteasy-client module calls releaseConnection() instead of close() in readEntity().

RESTEASY-1251: 

---

jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/ResponseTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResponseBuilderImpl.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/specimpl/ResponseBuilderImplTest.java

It seems that RESTEASY-222 should be reopened again, because when I use 'lastModified' the actual Last-Modified header is not correctly formatted. This is a fix, plus a test-case.

Test case and fix for RESTEASY-222

---

jaxrs/arquillian/ValidationTest-WF8/src/test/java/org/jboss/resteasy/test/validation/TestValidationJAXB.java
jaxrs/providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java

Fixed GeneralValidatorImpl in resteasy-validator-provider-11 so that checkForConstraintViolations()
passes mediaTypes to ResteasyViolationException.

RESTEASY-1264

---

jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java

Allowing ResteasyDeployment to use previously set dispatcher
Also adding an extra constructor to SynchronousDispatcher with pre-set ResourceMethodRegistry object
This is necessary for RESTEasy Spring Boot starter
See https://issues.jboss.org/browse/RESTEASY-1305
See https://github.com/paypal/resteasy-spring-boot

[RESTEASY-1305] RESTEasy Spring Boot starter integration

---

jaxrs/tjws/src/main/java/Acme/Serve/SSLAcceptor.java

Adding a security provider at runtime should be avoided as it effects
the entire JVM and may effect other efforts.
Constructing com.sun.net.ssl.internal is not part of public API.
This change performs the construction and registration of sun internal
JSSE provider only if SSLContext cannot be established, it solves only
the issue of not constructing and registering JSSE provider if already
available.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

RESTEASY-1318: TJWS construct and register java internal JSSE provider if required

---

jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/regression/ResteasyProviderFactoryTest.java

At 2 points in the code, the priority was not provided to the registerSingleton method. This caused a bug for me when I tried to get one ContainerResponseFilter to run before another, but the priority was not picked up.

RESTEASY-1311: ResteasyProviderFactory.registerProviderInstance does not always take priority into account

---

jaxrs/jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs-wf8/main/module.xml

resteasy-jaxrs-wf8 doesn't export httpcomponents in jboss-modules.

RESTEASY-1237

---

jaxrs/server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
jaxrs/server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/RequestHandler.java
jaxrs/server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/RESTEASY1325Test.java

RETEASY-1325: Netty server should close idle connections.
Even NettyJaxrsServer has SO_KEEPALIVE socket option, I would like to add idle timeout option to cleanup idle TCP clients.
By defaul, this feature doesn't turn on, so it's identical to previous versions.
If call to setIdleTimeout with number of seconds, Http client connection will be closed after specific idle time.
Description of this JIRA from https://issues.jboss.org/browse/RESTEASY-1325
"
Netty server adapter should handle client idle when there is no traffic within a certain amount of time.
Currently, if client open connection without sending any message. The connection will keep open.
If there is no Connection: close header, the connection will keep open.
Unless there is "Connection: close" header, they always require client …

Resteasy 1325

---

jaxrs/pom.xml
jaxrs/resteasy-jaxrs/pom.xml

Note that the `groupId` changed from `javassist` to `org.javassist`.

RESTEASY-1333 Upgraded Javassist to latest version.

---

jaxrs/pom.xml
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/finegrain/methodparams/QueryParamAsPrimitiveTest.java
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/finegrain/methodparams/UriParamAsPrimitiveTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/TypeConverterTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/core/request/QualityValueTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/methodparams/HeaderParamsAsPrimitivesTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/methodparams/MatrixParamAsPrimitiveTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/methodparams/QueryParamAsPrimitiveTest.java
jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/methodparams/UriParamAsPrimitiveTest.java
jaxrs/resteasy-spring/pom.xml
jaxrs/security/keystone/example/keystone-server/pom.xml
jaxrs/security/keystone/example/some-app/pom.xml
jaxrs/security/skeleton-key-idm/skeleton-key-idp-war/pom.xml
jaxrs/server-adapters/resteasy-netty4-cdi/pom.xml

The [Assert.assertEquals(e,a)](http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(double, double)) for floating point variables is deprecated.  One must use the newer [Assert.assertEquals(e,a,d)](http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertEquals(double, double, double)).
In addition, the version of JUnit used throughout the project was inconsistent.  Some `pom.xml` was tweaked to make it more consistent and centralize the version at the parent pom.

RESTEASY-1334 JUnit Assert.assertEquals(a,b) for floating point is deprecated

---

jaxrs/resteasy-links/src/main/java/org/jboss/resteasy/links/LinkResource.java
jaxrs/resteasy-links/src/main/java/org/jboss/resteasy/links/ParamBinding.java
jaxrs/resteasy-links/src/main/java/org/jboss/resteasy/links/impl/RESTUtils.java
jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStore.java
jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStoreMinimal.java
jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStoreService.java
jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/ScrollableCollection.java
jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestFacadeLinks.java

Implementation of feature request [RESTEASY-1321](https://issues.jboss.org/browse/RESTEASY-1321).
Currently the LinkResource annotation only supports path parameters for the atom link definition. This is enough when only adding default atom links (self, list, CRUD). But in order to add more advanced customized links (f.e. for paging) it is necessary to support the other types of parameters (query and matrix).
Therefore I added a new annotation called ParamBinding. Typically I would add the type as an enum in the ParamBinding, but just added two more members to the annotation (queryParameters, matrixParameters) in order not to break the API (this would remove / rename LinkResource#pathParameters).

RESTEASY-1321: Support non-path-parameters in LinkResource

---

jaxrs/arquillian/RESTEASY-1008-AS7/pom.xml
jaxrs/arquillian/RESTEASY-1008-WF8/pom.xml
jaxrs/arquillian/RESTEASY-1054-AS7/pom.xml
jaxrs/arquillian/RESTEASY-1054-WF8/pom.xml
jaxrs/arquillian/RESTEASY-1056-jetty-bv10/pom.xml
jaxrs/arquillian/RESTEASY-1056-jetty-bv11/pom.xml
jaxrs/arquillian/RESTEASY-1058-WF8/pom.xml
jaxrs/arquillian/RESTEASY-1073-WF8/pom.xml
jaxrs/arquillian/RESTEASY-1082-WF8/pom.xml
jaxrs/arquillian/RESTEASY-1141-WF8/pom.xml
jaxrs/arquillian/RESTEASY-736-as71/pom.xml
jaxrs/arquillian/RESTEASY-736-jetty/pom.xml
jaxrs/arquillian/RESTEASY-760-jetty/pom.xml
jaxrs/arquillian/RESTEASY-767-jetty/pom.xml
jaxrs/arquillian/RESTEASY-800-AS71/pom.xml
jaxrs/arquillian/RESTEASY-903-AS7/pom.xml
jaxrs/arquillian/RESTEASY-903-WF8/pom.xml
jaxrs/arquillian/RESTEASY-923-AS7/pom.xml
jaxrs/arquillian/RESTEASY-923-EAP6/pom.xml
jaxrs/arquillian/RESTEASY-923-WF8/pom.xml
jaxrs/arquillian/RESTEASY-945-WF8/pom.xml
jaxrs/arquillian/RESTEASY-TEST-EAP6/pom.xml
jaxrs/arquillian/RESTEASY-TEST-EAP7/pom.xml
jaxrs/arquillian/RESTEASY-TEST-WF10/pom.xml
jaxrs/arquillian/RESTEASY-TEST-WF8/pom.xml
jaxrs/arquillian/ValidationTest-WF8/pom.xml
jaxrs/arquillian/ValidationTest/pom.xml
jaxrs/arquillian/resteasy-cdi-ejb-test/pom.xml
jaxrs/pom.xml

Consistent versions for `arquillian-bom` and `wildfly-arquillian-container-managed`, then upgraded to:
* `arquillian-bom-1.1.11.Final`
* `wildfly-arquillian-container-managed-8.2.1.Final`

RESTEASY-1339 Arquillian Consistency and Upgrade

---

jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/security/PasswordColonTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/BasicAuthHelper.java

Allow ':' in Basic Auth passwords.
https://issues.jboss.org/browse/RESTEASY-1176
Also, reversing a test in ResteasyProviderFactory for RESTEASY-1284.

RESTEASY-1176

---

jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/finegrain/ResourceInfoInjectionTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AbstractAsynchronousResponse.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java

1. Missing ResourceInfo injected by @Context returns null on
getResourceClass() and getResourceMethod().
2. Push contextDataMap on ResteasyProviderFactory stack in
AbstractAsynchronousResponse for later use.

RESTEASY-1281

---

jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/interceptors/GZIPAnnotationTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/encoding/ClientContentEncodingAnnotationFeature.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/encoding/ClientContentEncodingAnnotationFilter.java

Changed RuntimeType to RuntimeType.Client on
ClientContentEncodingAnnotationFeature and
ClientContentEncodingAnnotationFilter.
https://issues.jboss.org/browse/RESTEASY-1265

[RESTEASY-1265]

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java

If I run Resteasy in Tomcat with "-Dfile.encoding=UTF-16" I get the following exception:
```
482  WARN   [ localhost-startStop-1   ] org.jboss.resteasy.plugins.providers.RegisterBuiltin   -  ClassNotFoundException :  Unable  to  load  builtin  provider : org.jboss.resteasy.plugins.providers.jackson.ResteasyJacksonProvider ²
483  WARN   [ localhost-startStop-1   ] org.jboss.resteasy.plugins.providers.RegisterBuiltin   -  ClassNotFoundException :  Unable  to  load  builtin  provider : org.jboss.resteasy.plugins.providers.DataSourceProvider
rg.jboss.resteasy.plugins.providers.DocumentProvider
rg.jboss.resteasy.plugins.providers.DefaultTextPlain
rg.jboss.resteasy.plugins.providers.StringTextStar
rg.jboss.resteasy.plugins.providers.SourceProvider …
```

Character encoding problem when reading the services file

---

arquillian/RESTEASY-TEST-WF10/src/main/java/org/jboss/resteasy/resteasy1365/HeadContentLengthApplication.java
arquillian/RESTEASY-TEST-WF10/src/main/java/org/jboss/resteasy/resteasy1365/SimpleResource.java
arquillian/RESTEASY-TEST-WF10/src/test/java/org/jboss/resteasy/test/resteasy1365/HeadContentLengthTest.java
jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
jaxrs/server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpResponse.java
jaxrs/server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpRequestDecoder.java
jaxrs/server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpResponseEncoder.java
jaxrs/server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/NettyTest.java

Backport of https://issues.jboss.org/browse/RESTEASY-1365 to 3.0.x.
EAP 7.x Jira (still waiting for acks):
https://issues.jboss.org/browse/JBEAP-4671
Upstream:
https://github.com/resteasy/Resteasy/pull/842   (already merged)

[RESTEASY-1365] resteasy-netty: HEAD requests always return Content-Length: 0

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResponseBuilderImpl.java
resteasy-jaxrs/src/test/java/org/jboss/resteasy/specimpl/ResponseBuilderImplTest.java

[RESTEASY-1439: ETag not quoted in ResponseBuilder.tag(String tag)](https://issues.jboss.org/browse/RESTEASY-1439)
`Response.status(412).entity(message).tag("123").build()` should generate `ETag: "123"` but instead does not quote the tag `ETag: 123.`
The [JAX-RS spec](http://docs.oracle.com/javaee/6/api/javax/ws/rs/core/Response.ResponseBuilder.html#tag(java.lang.String)) says:
> the ETag should be quoted by the runtime
Jersey adheres to the spec here, RESTEasy doesn't.
`ResponseBuilder.tag(EntityTag tag)` method works corrrectly but `ResponseBuilder.tag(String tag)` has this bug

RESTEASY-1439: ETag not quoted in ResponseBuilder.tag(String tag)

---

providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java

Small bugfix to prevent (IO)Exceptions being wrapped by unhandled RuntimeException, when reading posted Multiparts.

Fix for nondescript RuntimeException during Multipart-reading

---

pom.xml
testsuite/arquillian-utils/pom.xml
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtil.java
testsuite/integration-tests-spring/deployment/pom.xml
testsuite/integration-tests-spring/inmodule/pom.xml
testsuite/integration-tests-spring/pom.xml
testsuite/integration-tests/pom.xml
testsuite/pom.xml
testsuite/unit-tests/pom.xml

Custom resteasy version is needed to be able to run testsuite with different resteasy version than the project version. 
If the property "version.resteasy.testsuite" is  it applies to whole testsuite module. Otherwise project.version for resteasy dependencies is used.

[RESTEASY-1470] Property to specify resteasy version for testsuite + update creaper version

---

pom.xml

Jira: https://issues.jboss.org/browse/RESTEASY-1474
----
Allow to override redirectTestOutputToFile attribute of surefire plugin in testsuite.
This attribute is false by default. If value of this attribute is true in pom, it can't be override by -Dmaven.test.redirectTestOutputToFile=<property>.
----
Use same way as WF use:
https://github.com/wildfly/wildfly-core/blob/master/testsuite/pom.xml#L127
https://github.com/wildfly/wildfly-core/blob/master/testsuite/pom.xml#L307

[RESTEASY-1474] Allow to override redirectTestOutputToFile attribute

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ContentEncodingInvocationTest.java

Clean out Content-Encoding header in ClientInvocation when setting a new
entity.

[RESTEASY-1274]

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/UserDefinedContextResolverTest.java

In ResteasyProviderFactory, user defined context providers should be
registered as "not builtin".

[RESTEASY-1471]

---

jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/interceptors/GzipTest.java
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/interceptors/resource/GzipProxy.java
jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/interceptors/resource/Pair.java

Issue: https://issues.jboss.org/browse/RESTEASY-1499

[RESTEASY-1499] @GZIP annotation on client proxy doesn't set content-type gzip to the request header

---

docbook/reference/en/en-US/modules/Json.xml
providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/Jackson2JsonpInterceptor.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java

Jackson2JsonInterceptor needs to be enabled by setting a web context
parameter to "true".

[RESTEASY-1486]

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/ProcessorFactory.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/PathParamProcessor.java

If a client uses @PathParam which contains a slash, its currently encoded which then causes the call to fail. With this change, the user can decide to not encode the slashes by adding @Encoded

Added ability to control slash encoding for ParamParam

---

jaxrs/resteasy-client/src/test/java/org/jboss/resteasy/test/internal/ClientInvocationBuilderTest.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AsynchronousInvoke.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilder.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/FormProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/InvocationProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/AbstractInvocationCollectionProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/CookieParamProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/FormParamProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/HeaderParamProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/MessageBodyParameterProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/URIParamProcessor.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/LinkBuilderImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/LinkImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilder.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientInvocationBuilderTest.java

New pull request replacing https://github.com/resteasy/Resteasy/pull/906.
The goal of this pull request is to make few resteasy builders compliant with the Builder pattern (http://www.javaworld.com/article/2074938/core-java/too-many-parameters-in-java-methods-part-3-builder-pattern.html) and add consistency in the way Builder pattern is implemented in the project.
Actually almost all resteasy builders strictly follow the Builder pattern such as org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder but few others don't for unknown reason.
According to the pattern for a given builder instance, all "setters" methods (those which return a  builder) must return the updated builder instance not a new one:
>  public static class PersonBuilder
{
....
public PersonBuilder lastName(String …

My resteasy 1341

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/JacksonDatatypeEndPoint.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/JacksonDatatypeJacksonProducer.java

Basic integration test for jackson-datatype-jsr310 and jackson-datatype-jdk8 modules.
This test fails with WildFly 10.1, because this old WildFly doesn't contains jackson-datatype-jsr310 and jackson-datatype-jdk8 modules. So I add @Category({ExpectedFailing.class}) to new test now. And this annotation will be removed once new WildFly will be used in RESTEasy for testing.

[RESTEASY-1548] Add tests for jackson-datatype-jsr310 and jackson-datatype-jdk8 modules

---

testsuite/integration-tests-spring/deployment/pom.xml
testsuite/integration-tests-spring/inmodule/pom.xml
testsuite/integration-tests/pom.xml
testsuite/legacy-integration-tests/pom.xml
testsuite/pom.xml

* moves forward compatibility profile to the main testsuite pom
* excludes legacy integration tests module from the profile (that will be needed to added later When Wildfly/EAP with the resteasy 3.1 is released).

Forward Compatibility profile excludes legacy integration tests

---

pom.xml

See https://issues.jboss.org/browse/RESTEASY-1550
Default behaviour keeps same, test output is printed to file. But if something like this is used, test output is printed to console:
mvn install -Dmaven.test.redirectTestOutputToFile=false

[RESTEASY-1550] Allow to change redirectTestOutputToFile from console

---

server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/RequestHandler.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpRequestDecoder.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/NettyTest.java

https://issues.jboss.org/browse/RESTEASY-1205

[RESTEASY-1205] RestEasy-Netty4: ByteBuf leak in ResteasyHttpRequestDecoder

---

docbook/reference/en/en-US/modules/Migration_to_3.1.xml

Removed SerializableProvider from the list of deprecated classes moved
to a new package.

[RESTEASY-1541]

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java

ResteasyClientBuilder: fix socketTimeout documentation error

[RESTEASY-1561] ResteasyClientBuilder socketTimeout documentation error

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchCounterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/ValidationWithCDITest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AbortMessageTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/ResteasyJAXRSImplTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/FilteredCookieTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipSizeTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/SigningTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/Resteasy1405Test.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/atom/AtomComplexModelTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/XmlHeaderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/resource/Book.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/resource/BookStoreResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlPojoBindingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MultipleEndpointsWarningTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ApplicationScopeValidationTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java

YamlProvidertest - link issue JBEAP-7614 for bad request test
JaxbSmokeTest - make it pass with version com.fasterxml.jackson 2.5.x
XmlHeaderTest - not for forward compatibility
JsonView/JsonFilter forward compatibility
Jackson2Test forward compatibility
AtomComplexModelTest forward compatibility
Resteasy1405Test forward compatibility
GzipTest forward compatibility
FilteredCookieTest forward compatibility
ResteasyJAXRSImplTest forward compatibility
ValidationWithCDITest forward compatibility
AsynchCounterTest forward compatibility
SigningTest forward compatibility

Add NotForForwardCompatibility annotation into tests

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationHibernateI18NTest.java

Fix ValidationHibernateI18NTest test. This test check hibernate validation message, but this message was changed in new version of hibernate: https://github.com/hibernate/hibernate-validator/commit/8549a02d0457363fbc923fc9f9260eefc019f544#diff-124ed53e2f45f264c0428538f460f94cR13
Tests needs to pass with old and with new version of hibernate (it means with old WF and with new WF)

[RESTEASY-1564] ValidationHibernateI18NTest stabilization

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/AbstractReaderInterceptorContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/AbstractWriterInterceptorContext.java
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/LogCounter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingCustomReaderAndWriter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingEndPoint.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingReaderInterceptorCustom.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingWriterInterceptorCustom.java

Backport RESTEASY-1562 to 3.0.20.SPx branch
* Clarify debug messages with used interceptors
* Prepare tests for provider's and interceptor's debug messages.
* RESTEASY-1415
* RESTEASY-1558
* https://github.com/resteasy/Resteasy/pull/954
* https://github.com/resteasy/Resteasy/pull/1008

[RESTEASY-1583] Prepare tests for debug messages

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/NullHeaderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/NullHeaderFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/NullHeaderResource.java

ResteasyProviderFactory.toHeaderString() handles null value.

[RESTEASY-1579]

---

server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java

Bug fix: Only the first client requests are successful, any other requests issued by a new connection timeout. 
Using wireshark, it appears that the handshake is performed only at the first connection. I checked the code and indeed resteasy keep using the same SSL session for all connections.
Fix: use a new SSLEngine for each new connection.
Netty documentation about using the SSLHandler and restarting a session: 
https://netty.io/4.0/api/io/netty/handler/ssl/SslHandler.html =
Jira issue: https://issues.jboss.org/browse/RESTEASY-1590

[RESTEASY-1590] Create a new SSLEngine for each connection

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ResponseFilterCustomExceptionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/CustomException.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ThrowCustomExceptionResponseFilter.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/RequestFilterTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ClientCustomException.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/RequestFilterThrowCustomException.java

Currently every exception in .invoke() is wrapped in a ResponseProcessingException or it is mapped to specific HTTP exception in handleErrorStatus.
This change allows a Client Request/Repsonse Filters to throw custom exceptions.

[RESTEASY-1591] Change catch Throwable to IOException in ClientInvocation

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseRedirectTest.java

Issue: https://issues.jboss.org/browse/RESTEASY-1588

[RESTEASY-1588] Location header contains uppercase characters in ipv6 address on Windows

---

docbook/reference/en/en-US/modules/Content_Marshalling_Providers.xml
docbook/reference/en/en-US/modules/Installation_Configuration.xml
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/CacheInterceptor.java
resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/ResponseObjectTest.java
resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/finegrain/resource/ResourceLocatorTest.java
resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/finegrain/resource/VariantsTest.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/cache/CacheInterceptor.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/encoding/MessageSanitizerContainerResponseFilter.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ListenerBootstrap.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/MediaTypeHelper.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchContextualDataTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ResponseObjectTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/ReaderWriterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/WriterNotBuiltinTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/ContentTypeMatchingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/TypeMappingJettisonTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlPojoBindingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultCharsetTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MatchedResourceTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ResourceLocatorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/ResourceMatchingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/VariantsTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/CustomForbiddenMessageTest.java

Add NotForForwardCompatibility for the new tests
[RESTEASY-1628]
Changed treatment of text media types without charset parameter to add
"charset=UTF-8" by default.
[RESTEASY-1628]
Altered
org.jboss.resteasy.plugins.interceptors.encoding.MessageSanitizerContainerResponseFilter.containsHtmlText().

[RESTEASY-1628 squashed]

---

docbook/reference/en/en-US/modules/Content_Marshalling_Providers.xml
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/file/TempFileDeletionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/file/resource/TempFileDeletionResource.java

On server side, FileProvider adds temporary File to Cleanables so that
it will be deleted at end of invocation.

[RESTEASY-1464]

---

testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtil.java
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilSpring.java
testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/SpringBeanProcessorDependenciesInDeploymentTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/servlet/UndertowTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/file/TempFileDeletionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/html/HeadersInViewResponseTest.java

* UndertowTest - fix adress in SocketPermission for ipv6 runs
* HeadersInViewResponseTest - allow to get resteasy-html jar from the local repository if the resteasy project isn't build

[RESTEASY-1651] Enhance UndertowTest and HeadersInViewResponseTest

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/MessageBodyParameterProcessor.java

Isse: https://issues.jboss.org/browse/JBEAP-11919
Upstream Issue: https://issues.jboss.org/browse/RESTEASY-1684
Upstream PR: https://github.com/resteasy/Resteasy/pull/1206

RESTEASY-1684 - Arguments must not be null when sending a null JSON object with ResteasyWebTarget

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java

MDBInjectionTest doesn't work with IPv6
String definition of IPv6 address must be in [%] in SocketPermission constructor
Jira: https://issues.jboss.org/browse/RESTEASY-1691
PR for RESTEasy 3.0: https://github.com/resteasy/Resteasy/pull/1214

[RESTEASY-1691] MDBInjectionTest doesn't work with IPv6

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/CorsFilter.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/CorsHeaders.java

https://issues.jboss.org/browse/RESTEASY-1704

fix for RESTEASY-1704

---

resteasy-client/pom.xml
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/AsyncClientHttpEngine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/LogMessages.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
resteasy-dependencies-bom/pom.xml
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncBenchTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncInvokeTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/InputStreamTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/other/ApacheHttpClient43Test.java

Followup from https://github.com/resteasy/Resteasy/pull/1228.
PR 1228 description pretended the new async/NIO engine is enabled by default when the libs are available, however that was not the case, given the new engine was not actually being constructed anywhere. I tried defaulting to the new engine, but that clearly does not fit most of the common usage scenario, as for example built-in providers can ask for blocking reads in a thread handling IO. So I think it's better to let the use decide to build a new engine and set it in the client when it makes sense.

Async client

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PostMatchContainerRequestContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ResponseContainerRequestContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/SuspendableContainerRequestContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/SuspendableContainerResponseContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventSinkInterceptor.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceMethod.java
resteasy-legacy/src/main/java/org/jboss/resteasy/core/interception/ContainerResponseContextImpl.java
resteasy-legacy/src/main/java/org/jboss/resteasy/core/interception/PostMatchContainerRequestContext.java
resteasy-legacy/src/main/java/org/jboss/resteasy/core/interception/PreMatchContainerRequestContext.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncRequestFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncPreMatchRequestFilter1.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncPreMatchRequestFilter2.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncPreMatchRequestFilter3.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter1.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter2.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter3.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilterResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter1.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter2.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter3.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/request/ContainerRequestContextTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/AcceptParameterHttpPreprocessorTest.java

Hi,
This is a proto for supporting async request filters, which I need in another project.
This is not done by far, but given as a PR for discussion (do not merge it).
I only support post-match requests going async, and for backwards compat the default behaviour is to be synchronous in post-match filters. To go async from within a filter, you need to cast the context argument and invoke `suspend()` on it. After that you can resume the filtering with `abortWith` (existing method) or `resume()` to move on to the next filter or the resource method itself.
It's possible to have a filter that goes async, and a non-async filter or a non-async resource method after it, and we do handle this case. In the case of non-async resource methods, I assume that if the method is not declared as returning …

Async request filters

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java

@jimma , this is to prevent issues with events sometimes not delivered in order

[RESTEASY-1680] Making testMultipleDataFields more robust

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/EventByteArrayOutputStream.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/InboundSseEventImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseConstants.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventInputImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventProvider.java

Fix couple of things : 
-  each event is now ended with '\n' insteand of '\r\n' 
-  eventInputImpl can read the event with delimiter '\r', '\n' or '\r\n' (it's only '\r\n' before this change)
-  all event fields are encoded with "UTF-8" and value is encoded with mediaType's charset  if it exists.

[RESTEAY-1680]:Reads event with different eol; clean up charset constant

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilder.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/UriBuilderTest.java

@ronsigal @asoldano Please review.  All the variants of an IPv6 addresses can't
easily be determined by a Pattern object.  I've appropriated IPv parsing code
from URI and created utility, IPv6FormatParser.  In addition Resteasy supports 
uri "templating" (see UriBuilderTest line 87) which allows left and right brackets.
IPv format considers {} "excluded characters" because gateways and other transport
agents are known to sometimes modify such characters, so a Pattern for template
text was created and checked first so we can identify these before the IPv
address format is checked.

[RESTEASY-1718] added utility to check for IPv6 format

---

eagledns/src/main/java/se/unlogic/standardutils/crypto/Base64.java
eagledns/src/main/java/se/unlogic/standardutils/threads/ThreadPoolTaskGroupHandler.java
eagledns/src/main/java/se/unlogic/standardutils/xml/XMLUtils.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/AsyncJaxrsResource.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxRequestHandler.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/AnotherPublisherResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/ApplicationScopeRestServiceAppScoped.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/ApplicationScopeRestServiceReqScoped.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ChunkedTransferEncodingUnitTest.java

Eliminate ex.printStackTrace() from the code base
Issue: https://issues.jboss.org/browse/RESTEASY-1737
non test classes:
*   eagledns keeps using log4j, jboss logging is not used there
*   resteasy-jaxrs using jboss-logging messages
*   server-adapters using jboss-logging messages
*   tjws won't be fixed as the classes are deprecated
test classes:
* using jboss-logging

[RESTEASY-1737] Eliminate ex.printStackTrace() from the code base

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletInputMessage.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/FormEntityTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/resource/FormEntityResource.java

If an entity is sent with media type application/x-www-form-urlencoded
entity, reconstruct body from form parameters if the InputStream has
been read.
[RESTEASY-1738]
Before constructing form entity from form parameters, check that form
parameters were already read.

[RESTEASY-1738]

---

server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/NettyApplicationPathTest.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/Netty4ApplicationPathTest.java

Jira: https://issues.jboss.org/browse/RESTEASY-1657
This PR includes fix for detecting root path from the annotation. I put it just after deployment start in the server start method.
The setRootResourcePath method takes precedence.
Adding also some tests.

[RESTEASY-1657] RESTEasy-Netty4 ignores @ApplicationPath

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/HttpResponseCodes.java

<a href="https://tools.ietf.org/html/rfc7538">RFC 7538</a> describes the behavior of the HTTP status code <strong>308</strong>. While this RFC is quite new it solves an actual problem regarding POST redirections.
And it completes quite well the 307 status code found in the <a href="https://tools.ietf.org/html/rfc7231">HTTP 1.1 RFC</a> (previously described in the obsolete <a href="https://tools.ietf.org/html/rfc2616">RFC 2616</a>).

Added PERMANENT_REDIRECT to HttpResponseCodes

---

providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/AbstractJAXBContextFinder.java
providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBContextWrapper.java
providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBXmlTypeProvider.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ClientHttpEngineBuilder43.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClient.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncPostProcessingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchBasicTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EJBTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/extensions/ScopeExtensionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AbortMessageTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientCacheTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/InternalDispatcherTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/CorsFiltersTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/PriorityExecutionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/WriterNotBuiltinTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/JaxbMarshallingSoakTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/XmlJavaTypeAdapterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/HeaderDelegateTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationComplexTest.java

Issue: https://issues.jboss.org/browse/RESTEASY-1638
@asoldano, this PR contains several changes that might need extra attention to make sure it doesn't affect other parts of the code. So far I did run a full build and tested all failing tests referred on the JIRA. The one test that still fails is `JaxbMarshallingSoakTest` due to `JAXBContext.newInstance()` requiring FilePermission to a JAR file that I couldn't get around.

[RESTEASY-1638] Permission check failed when creating instance of resteasy client

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/CorsFilter.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/CorsHeaders.java

Issue: https://issues.jboss.org/browse/JBEAP-12820
Upstream Issue: https://issues.jboss.org/browse/RESTEASY-1704
Upstream PR: #1258
Backporting fix for RESTEASY-1704 to branch 3.0 (thus for EAP 7.1.z stream)

[RESTEASY-1704] CVE-2017-7561 resteasy: Vary header not added by CORS filter leading to cache poisoning

---

resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/interceptors/GzipTest.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/encoding/ServerContentEncodingAnnotationFeature.java

Backport from commit 7e0c52cb115245081b9d695d839ff3b0c0c4074a

[RESTEASY-1735] RESTEasy returns wrong Content-Encoding data if client request gzip

---

docbook/reference/en/en-US/modules/Guice.xml

Request scoped injection by Guice does not work as given in current docs where `RequestScoped` is applied to the class. Applying `RequestScoped` annotation to fields makes injection work.
I haven't checked in detail why annotating a class does not work but I believe docs shall have a working case.

Update Guice Integration / Request Scope docs

---

resteasy-jsapi/src/main/resources/resteasy-client.js

**resteasy-jsapi/resteasy-client.js** Do not stringify FormData.
Developers may send the form content inside FormData to be properly handled by XMLHttpRequest.

Do not stringify FormData

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkClosingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkClosingTestResource.java

Closing the SseEventSink instance once an event has been sent should not return any response and thus not pass through the JAX-RS response pipeline.

RESTEASY-1766: Closing SseEventSink should not call JAX-RS filters

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventSinkInterceptor.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEnablingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEnablingTestResource.java

This pull request introduce the concept of **SSE resource method** as described in the specification:
> 9.3 Server API
> ...
> A resource method that injects an SseEventSink and produces the media type text/event-stream is an
> SSE resource method.
It helps to fixe issues listed in https://issues.jboss.org/browse/RESTEASY-1776

Resteasy 1776: Sse feature should only be enabled when resource method only produces "text/event-stream" and is injected with @Context SseEventSink

---

testsuite/microprofile-tck/pom.xml

Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.891 s - in TestSuite

Remove the snapshot dependency on MP 1.1-SNAPSHOT

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageProxy.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java

jira: https://issues.jboss.org/browse/RESTEASY-1809
master PR: https://github.com/resteasy/Resteasy/pull/1418
I add "@Category({ExpectedFailing.class})" annotation to this test. If you want rather to use @Ignore annotation, or no annotation, I can change it ...

[RESTEASY-1809] Tests for CompletionStage resource method return type

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/MapCache.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java

Use Map.entrySet instead of iterating keySet and getting value later
First round is for resteasy-client module to see if makes sense to proceed further.
https://issues.jboss.org/browse/RESTEASY-1810

[RESTEASY-1810] Usage of Map.entrySet instead of keySet

---

resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java

JIRA: https://issues.jboss.org/browse/RESTEASY-1816
Test case added separately in https://github.com/kanovotn/Resteasy/commit/4cc3f12f862b45212bfe6a2fc2a3780cb6be90c0#diff-46bd7bf2136ed3b55bf449e8b0a9ee77R121

[RESTEASY-1816] OnComplete callback registered via SseEventSource.register() is not called

---

resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlServlet.java

Added missing return statement, so that NPE is avoided.
Jira: https://issues.jboss.org/browse/RESTEASY-1824

[RESTEASY-1824] NullPointer exception in ResteasyWadlWriter

---

pom.xml
resteasy-jaxrs/pom.xml

https://issues.jboss.org/browse/RESTEASY-1844
Java 9 cleanup, preparation for Java 10+
Java 10+ missing piece is https://github.com/jettison-json/jettison/issues/21, proposed fix is https://github.com/jettison-json/jettison/pull/22
`mvn clean install -Dversion.org.codehaus.jettison=1.3.9-SNAPSHOT` with proposed fix passes

[RESTEASY-1844] Java 9 cleanup, preparation for Java 10+

---

resteasy-servlet-initializer/src/main/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializer.java

on the one hand, the spec says:
```
if the Application subclass is annotated with @ApplicationPath , implementations are REQUIRED to use the value of this annotation appended with ”/*” to define a mapping for the added server.
```
on the other the code already tries to handle the "/" suffix differently.
as-is right now though, the resulting path would end in `/*/*`, which is definitely wrong.

[RESTEASY-1846] dont append /* to application paths that already end in /*

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/LocatorRegistry.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/POJOResourceFactory.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/SingletonResource.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceClass.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceConstructor.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceLocator.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceMethod.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/MethodParameter.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceClass.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceClassProcessor.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceConstructor.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceLocator.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceMethod.java
resteasy-jsapi/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxRegistry.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxResteasyDeployment.java

This replaces #1455 
* [RESTEASY-1805] Extract interface from ResourceLocator
* [RESTEASY-1805] Extract interface from ResourceMethod
* [RESTEASY-1805] Extract interface from ResourceConstructor
* [RESTEASY-1805] Extract interface from ResourceClass
* [RESTEASY-1805] Let ResteasyProviderFactory manage a single ResourceBuilder
* [RESTEASY-1805] Added ResourceClassProcessor SPI
* Make POJOResourceFactory backward compatibile
* Make ResourceBuilder backward compatible
* Keep on using former APIs on tests
* Restore constructor in SingletonResource
* Deprecate old constructor in POJOResourceFactory

[RESTEASY-1805] (#1449)

---

pom.xml
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerNotAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerNotAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/resource/GzipInterface.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/resource/GzipResource.java
testsuite/integration-tests/src/test/resources/arquillian.xml
testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTest-javax.ws.rs.ext.Providers

jira: https://issues.jboss.org/browse/RESTEASY-1882
This commit adds regression tests for https://issues.jboss.org/browse/RESTEASY-1735
The main reason for new execution in these tests is that server needs to be started with two different settings: define -Dresteasy.allowGzip=true and don't define that.
This could be implemented also by more container definitions in arquillian.xml, but if we want to use this approach, container (EAP/WF) needs to be started in class/manual mode, see some details in [1]. I don't recommend this approach.
If this PR will be approved, I create new PR for 3.6. New 3.6 PR would be slightly different, because gzip interceptors are placed in different packages in 3.6.
[1] http://arquillian.org/blog/2011/11/26/arquillian-core-1-0-0-CR6/

[RESTEASY-1882] Regression tests for RESTEASY-1735 (gzip tests)

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilder.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/UriBuilderTest.java

Jira: https://issues.jboss.org/browse/RESTEASY-1878
There is a problem when building URI starting with template parameter regex expression (for example "{path: .+}"), ResteasyUriBuilder mistakes it for URI scheme.

[RESTEASY-1878] UriBuilder.fromPath() fails on regexp template parameter

---

checkstyle.xml
pom.xml

The profile is enabled with '-Dcheckstyle'. The errors found by checkstyle needs to be fixed before enabling this by default.

Checkstyle profile, checkstyle configuration

---

docbook/reference/en/en-US/master.xml
docbook/reference/en/en-US/modules/_CookieParam.xml
docbook/reference/en/en-US/modules/_FormParam.xml
docbook/reference/en/en-US/modules/_HeaderParam.xml
docbook/reference/en/en-US/modules/_MatrixParam.xml
docbook/reference/en/en-US/modules/_NewParam.xml
docbook/reference/en/en-US/modules/_PathParam.xml
docbook/reference/en/en-US/modules/_QueryParam.xml

Documentation for new param annotations, as requested in #1467

Documentation for new param annotations RESTEASY-1880

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorBasicTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/ResourceClassProcessorClass.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/ResourceClassProcessorEndPoint.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/ResourceClassProcessorEndPointCDI.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/ResourceClassProcessorEndPointEJB.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/ResourceClassProcessorImplementation.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/ResourceClassProcessorMethod.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/ResourceClassProcessorProxy.java

[RESTEASY-1805] Proxy tests for resource metadata SPI
jira: https://issues.jboss.org/browse/RESTEASY-1805
This PR adds ResourceClassProcessorBasicTest#proxyTest. This test is in ExpectedFailing category. SPI needs to be fixed for proxy.
This PR also fixes test bug in customClassCustomMethodTestHelper and defaultClassDefaultMethodTestHelper methods.
3.6 PR: not yet, but I can prepared it ...

[RESTEASY-1805] Proxy tests for resource metadata SPI

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/AbstractInjectionTestBase.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/resource/CDIInjectionResourceProducer.java

Update naming and BeforeClass method in JMS tests. It is necessary for WF13
See the details in WFLY-10432
Jira: https://issues.jboss.org/browse/RESTEASY-1912
Master PR: https://github.com/resteasy/Resteasy/pull/1521

[RESTEASY-1912] Update naming and BeforeClass method in JMS tests

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationComplexTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ValidationComplexOtherGroupConstraint.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ValidationComplexOtherGroupValidator.java

Fix ValidationComplexTest custom bean validation constraint
Jira: https://issues.jboss.org/browse/RESTEASY-1910
Master PR: https://github.com/resteasy/Resteasy/pull/1515
ValidationComplexTest uses ValidationComplexOtherGroupConstraint. This constraint uses ValidationComplexClassValidator. But ValidationComplexClassValidator can be used only for ValidationComplexClassConstraint.
WF used hibernate-validator-6.0.9.Final in the past and this old validator ignores this constraint bug. But now, WF uses hibernate-validator-cdi-6.0.10.Final. And test ValidationComplexTest#testOtherGroups fails with new hibernate-validator-cdi-6.0.10.Final:
```
javax.validation.ConstraintDefinitionException: HV000243: Constraint org.jboss.resteasy.test.validation.resource.ValidationComplexOtherGroupConstraint …
```

[RESTEASY-1910] Fix ValidationComplexTest custom bean validation constraint

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncRequestFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilterResource.java

This fixes a bug when the resource method return type is neither `void` nor `Response` and a filter turns the request async.

Async filter bugfix

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/UndertowTestRunner.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageServerAsyncTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/ExceptionThrowingFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/FilterException.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/RxCompletionStageResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/RxCompletionStageResourceImpl.java

If we have an async response (returning `CompletionStage` for example, and a filter throws an exception while writing the response, the exception used to be silently ignored by `CompletionStage`, which meant that the client would hang waiting for the response, and nothing would be logged.
I fixed this, but it also means I don't throw `UnhandledException` to the container anymore in such cases, because it's very hard (if not impossible) to know at that point if the container is still in our call stack, or if we're in another thread entirely, in which case the container would never get the exception, and the exception would be caught by whatever happened to complete the async response, which is just wrong.
So I had to adapt a test which used to assume we'd get a stack trace from the …

Async filter exception bug

---

resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientResponse.java
resteasy-client-jetty/src/test/java/org/jboss/resteasy/test/client/jetty/JettyClientEngineTest.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponseContextImpl.java

Currently, a response filter that chooses to read the response context's `getEntityStream` is returning the `inputStream`.
This is fine if the stream has not been read already.  But if it ends up being buffered, either internally or via `bufferEntity()`, the input stream is exhausted.
Returning the entity stream from the response fixes this issue.

[RESTEASY-1927] ClientResponseContextImpl: getEntityStream returns possibly exhausted inputStream

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/CustomConstrainedFeatureTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomClientConstrainedFeature.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomConstrainedFeatureResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomServerConstrainedFeature.java
testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/custom/CustomConstrainedFeature.Providers

Jira: https://issues.jboss.org/browse/RESTEASY-1861
The approach is to not call configure method if the runtime environment does not match the one mentioned in javax.ws.rs.ConstrainedTo annotation (similar to dynamic features).

[RESTEASY-1861] RESTEasy ignores @ConstrainedTo in some situations

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/ClientResponseFilterExceptionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResourceImpl.java

ClientInvoker.invoke() catches ResponseProcessingException and closes
connection.
[RESTEASY-1932]
Added integration test.
[RESTEASY-1932]
Cleaned up test.

[RESTEASY-1932]

---

testsuite/pom.xml

Testsuite elytron module misconfiguration
Elytron module sets surefire system properties in testsuite/pom.xml. But these properties are replaced/removed by system properties from surefire execution definitions from testsuite/integration-tests/pom.xml
Elytron profile definition needs to be updated
Jira: https://issues.jboss.org/browse/RESTEASY-1936
Master PR: https://github.com/resteasy/Resteasy/pull/1591

[RESTEASY-1936] Testsuite elytron module misconfiguration

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AbstractAsynchronousResponse.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/SuspendableContainerRequestContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/SuspendableContainerResponseContext.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncRequestFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncFilterException.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncFilterExceptionMapper.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilterResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter.java

This fixes the following bugs:
- `SuspendableRequestContainerContext.resume(Throwable)` and `SuspendableResponseContainerContext.resume(Throwable)` were ill-specified
- `SuspendableRequestContainerContext.resume(Throwable)` and `SuspendableResponseContainerContext.resume(Throwable)` did not call async callbacks
- `SuspendableRequestContainerContext.resume(Throwable)` did not always call exception mapper and response filters
- `SuspendableResponseContainerContext.resume(Throwable)` should not call exception mapper and response filters

[RESTEASY-1943] Async filter resume with exception issues

---

resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSourceTest.java

This pull request is to remove multiple invocation of SseEventSource completion handlers and enable test about it.
@ronsigal You might be interested by this PR since it seem's that the regression has been introduced by https://github.com/resteasy/Resteasy/pull/1478 
@rnetuka and @kanovotn You also might be interested by this PR as an enrichment to what have been done in https://github.com/resteasy/Resteasy/pull/1435/files

OnComplete callback registered via SseEventSource.register() must be called only once

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/JaxrsInterceptorRegistry.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/NameBoundCDIProxiesTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesApplication.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesInterceptor.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundProxiesAnnotation.java

Allow matching name binding between Applications and interceptors when
the Application object is a CDI proxy.

[RESTEASY-1708]

---

testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java

Unused imports in JaxrsWithSpringMVCTest prevent compilation success on **Java 11 ea+22**
Import of `javax.xml.ws.WebServicePermission` is the main problem.
https://issues.jboss.org/browse/RESTEASY-1959

[RESTEASY-1959] Removal of unused imports in JaxrsWithSpringMVCTest

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java

JIRA: https://issues.jboss.org/browse/RESTEASY-1725
As stated by R Searls, Java doesn't support inspecting generic types inside lambdas. Reworking the whole ResteasyProviderFactory system for this one particular case would be very difficult. The IndexOutOfBoundsException is however highly confusing. It would be definitely better to throw some more descriptive excpetion instead.

[RESTEASY-1725] Registering lambda context resolver results in ArrayIndexOutOfBoundsException

---

testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAbstractTestBase.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerNotAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTestBase.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAbstractTestBase.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerNotAllowGzipOnClientTest.java
testsuite/integration-tests/src/test/resources/arquillian.xml

https://issues.jboss.org/browse/RESTEASY-1884
Removal of extra surefire execution just for two testcases, instead new container with needed settings is manually started for these tests.

[RESTEASY-1884] Use custom manually started container for GZIP tests instead of surefire execution

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/PriorityExecutionTest.java

Originally, PriorityExecutionTest defined server filters by ResteasyProviderFactory loaded in test method run on server-deployment by Arquillian. This leads to intermittent failures, see the description on https://issues.jboss.org/browse/RESTEASY-1935
This PR removes ResteasyProviderFactory usage from test methods, but adds filter definitions to web.xml file. Web.xml file is created automatically by TestUtil.finishContainerPrepare TS util method.
Jira: https://issues.jboss.org/browse/RESTEASY-1935
Master PR: https://github.com/resteasy/Resteasy/pull/1651

[RESTEASY-1935] Define filters in web.xml in PriorityExecutionTest

---

testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java

testsuite/integration-tests-spring/deployment module can't be built with unused import of `javax.xml.ws.WebServicePermission` on JDK11:
```
11:32:52 [ERROR] COMPILATION ERROR : 
11:32:52 [INFO] -------------------------------------------------------------
11:32:52 [ERROR] /home/hudson/hudson_workspace/workspace/eap-7.x-resteasy-functional-ts-rhel/64f1522b/resteasy/testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java:[6,20] package javax.xml.ws does not exist
```
JDK11 test run with this fix is linked on [jira](https://issues.jboss.org/browse/RESTEASY-1995)
Jira: https://issues.jboss.org/browse/RESTEASY-1995
3.6.1.SPx PR: https://github.com/resteasy/Resteasy/pull/1662
master PR: merged a few time ago: …

[RESTEASY-1995] remove unused imports from JaxrsWithSpringMVCTest

---

testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilRxJava.java
testsuite/integration-tests/pom.xml

Do not use specific rxjava dependency in TS, because rxjava is not used in WF, so no need to change this version
Jira: https://issues.jboss.org/browse/RESTEASY-1999
3.6 PR: https://github.com/resteasy/Resteasy/pull/1669
3.6.1 PR: https://github.com/resteasy/Resteasy/pull/1670

[RESTEASY-1999] Do not use specific rxjava dependency in TS

---

testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/LogCounter.java
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtil.java
testsuite/integration-tests-spring/deployment/pom.xml
testsuite/integration-tests-spring/inmodule/pom.xml
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/ContainerConstants.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorErrorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAbstractTestBase.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingAnnotationsJacksonTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/NotFoundErrorMessageTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingTestBase.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
testsuite/integration-tests/src/test/resources/arquillian.xml
testsuite/pom.xml

https://issues.jboss.org/browse/RESTEASY-2003
To isolate the instance specific stuff I had to introduce few more steps for copying the standalone directory and retarget few plugin runs to different phases so that all is executed in proper order.

[RESTEASY-2003] Isolate container standalone dir in tests

---

arquillian/RESTEASY-1056-jetty-bv11/src/test/resources/arquillian.xml
arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/src/test/resources/arquillian.xml
arquillian/pom.xml
pom.xml
testsuite/integration-tests-spring/deployment/src/test/resources/arquillian.xml
testsuite/integration-tests-spring/inmodule/src/test/resources/arquillian.xml
testsuite/integration-tests/src/test/resources/arquillian.xml
testsuite/pom.xml

Add java.se module to JDK11 testsuite runs
I add the same jdk11 args as common.sh script: https://github.com/wildfly/wildfly-core/blob/master/core-feature-pack/src/main/resources/content/bin/common.sh#L9-L12
This PR remove modular.jdk.props, this property is currently not used in WF: https://github.com/wildfly/wildfly/blob/master/pom.xml#L6985-L6997
upstream PR: https://github.com/resteasy/Resteasy/pull/1690
jira: https://issues.jboss.org/browse/RESTEASY-2004

[RESTEASY-2004] Add java.se module to JDK11 testsuite runs

---

.travis.yml
pom.xml
testsuite/integration-tests-spring/deployment/src/test/resources/arquillian.xml
testsuite/integration-tests-spring/inmodule/src/test/resources/arquillian.xml
testsuite/integration-tests/src/test/resources/arquillian.xml
testsuite/pom.xml

**https://issues.jboss.org/browse/RESTEASY-2004**
Add java.se module to JDK11 testsuite runs
I add the same jdk11 args as common.sh script: https://github.com/wildfly/wildfly-core/blob/master/core-feature-pack/src/main/resources/content/bin/common.sh#L9-L12
This PR remove modular.jdk.props, this property is currently not used in WF: https://github.com/wildfly/wildfly/blob/master/pom.xml#L6985-L6997
master PR: https://github.com/resteasy/Resteasy/pull/1689
----
**https://issues.jboss.org/browse/RESTEASY-2002**
Move towards WildFly 14
master PR: https://github.com/resteasy/Resteasy/pull/1683

JDK11 java.se module and WF14 upstream testing

---

resteasy-cdi/src/main/resources/META-INF/web-fragment.xml
resteasy-servlet-initializer/src/main/resources/META-INF/web-fragment.xml

The problem I'm trying to solve is the following:
- Tomcat 9.0.10
- OpenWebBeans 2.0.4
We are using `<absolute-ordering>` in our `web.xml`. This - as far as I understood the Servlet API Spec - disable autoscanning on all JARs not explicitly mentioned in the `<absolute-ordering>` section, including scans for Annotations.
I still want to use RestEasy's autoscan feature, but in order to do that, I have to mention `resteasy-servlet-initializer` in the `<absolute-ordering>` section of my `web.xml`, but since `resteasy-servlet-initializer.jar` does not contain a `web-fragment.xml` with a `<name>` tag (actually: it does not contain any `web-fragment.xml` at all) I can't do that.
Similar applies to `resteasy-cdi`, which has a `web-fragment`, but does not set the `<name>` tag on it, so I cannot …

[RESTEASY-2035] Add named web-fragments

---

providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartFormDataWriter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/EncodingMimeMultipartFormProviderResource.java

Fixed by replacing to correct chars. Enhanced test to cover this case.
Jira: https://issues.jboss.org/browse/RESTEASY-2046

[RESTEASY-2046] Space Improperly Encoded in Content-Disposition Filename

---

resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java

The code has been reorganized to show a more logical grouping of the actions to be take on "instanceof" classes.  
Before the flow was
check for specific class
check instanceof ApplicationException
check instanceof WriterException
check instanceof ReaderException
check instanceof WebApplicationException  handle case one
check exception cause and super classes of cause 
check instanceof WebApplicationException  handle case two
check instanceof Failure
The refactored flow is
check for specific class
check instanceof WebApplicationException
handle case one
check exception cause and super classes of cause
handle case two
check instanceof Failure   
check instanceof WriterException   - class is a subclass of Failure
check instanceof ReaderException  - class is a subclass of Failure
check for …

[RESTEASY-2045] refactored method

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/CacheInterceptor.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientCacheInterceptorTest.java

Use media type from the request, if not present then fallback to response content type.
Jira: https://issues.jboss.org/browse/RESTEASY-2038

[RESTEASY-2038] CacheInterceptor uses content type of response as mediatype instead of accept header of request

---

resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLoggerImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandling.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingEnableTracingRequestFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingPleaseMapException.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingPleaseMapExceptionMapper.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java

Fix for the following issue: https://issues.jboss.org/browse/RESTEASY-1142
The resteasy-client's ClientResponse throws an IllegalStateException when the ExceptionMapper calls ClientResponse.getEntity().
This issue is a blocker for my use-case.

[RESTEASY-1142] ExceptionHandler: catch IllegalStateException from ClientResponse

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/ByteArrayProvider.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileRangeWriter.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/StreamingOutputProvider.java

Add missing `@Provider` annotation to `StreamingOutputProvider`, `ByteArrayProvider` and `FileRangeWriter`.
Fix for minor Issue [RESTEASY-2063](https://issues.jboss.org/browse/RESTEASY-2063).

[RESTEASY-2063] Add missing provider annotations

---

resteasy-dependencies-bom/pom.xml

jira: https://issues.jboss.org/browse/RESTEASY-2053
3.6 PR: https://github.com/resteasy/Resteasy/pull/1760
---- 
RESTEasy currently prints with JDK11 these warnings:
1. WARNING: Illegal reflective access by org.wildfly.security.manager.GetAccessibleDeclaredFieldAction (file:/home/mkopecky/.m2/repository/org/wildfly/security/wildfly-elytron/1.1.5.Final/wildfly-elytron-1.1.5.Final.jar) to field java.security.AccessControlContext.context
2. WARNING: Illegal reflective access by org.jboss.as.server.deployment.reflect.ClassReflectionIndex (jar:file:/home/mkopecky/playground/wf/modules/system/layers/base/org/jboss/as/server/main/wildfly-server-7.0.0.Alpha4.jar!/) to method java.lang.Object.finalize()
Second one is caused by WFCORE-4116 (not yet used in WF). First one is cause by wrong elytron …

[RESTEASY-2053] JDK11 illegal reflective access testsuite warnings

---

testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ChunkedTransferEncodingUnitTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseFilterTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ConfigurationInheritanceTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFeature1.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFeature2.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFeature3.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFeature4.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFeature5.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFeature6.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFilter1.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFilter2.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFilter3.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFilter4.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFilter5.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestFilter6.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestMessageBodyReader1.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestMessageBodyReader2.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestMessageBodyReader3.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestMessageBodyReader4.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestMessageBodyReader5.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/ConfigurationInheritanceTestMessageBodyReader6.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/FakeHttpServer.java

I encounter spurious test failures in travis test logs:
```
org.jboss.resteasy.test.client.ConfigurationInheritenceTest
testContextResolverInheritence(org.jboss.resteasy.test.client.ConfigurationInheritenceTest)  Time elapsed: 127.237 sec  <<< ERROR!
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine.invoke(ApacheHttpClient43Engine.java:272)
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:484)
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:63)
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:182)
at org.jboss.resteasy.test.client.ConfigurationInheritenceTest.testCon …
```

Improve client unit test robustness

---

testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/PriorityTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/resource/FakeHttpServer.java

This is a follow up on https://github.com/resteasy/Resteasy/pull/1765
Tests in `org.jboss.resteasy.test.interception.PriorityTest` also use the RESTEasy client, targetting the real internet site `www.test.com`. This leads to spurious test failures.
The commit replaces use of `www.test.com` with the URL of a fake HTTP server listening on the IPv4 loopback address on a dynamically allocated port.
@asoldano Sorry for not committing in time to catch the previous PR's merge. I duplicated the `FakeHttpServer` class in `../interception/resource` to conform to the projects test layout. In theory I would prefer to mock the client for these tests, but using the fake server is too easy and apparently fast enough.

PriorityTest: improve robustness (FakeHttpServer)

---

resteasy-dependencies-bom/pom.xml

Old version of wildfly-arquillian-container-* causes 200 ts error with WF master (WF14 is not affected).
Jira: https://issues.jboss.org/browse/RESTEASY-2066
3.6 PR: https://github.com/resteasy/Resteasy/pull/1774

[RESTEASY-2066] Upgrade wildfly-arquillian-container dependencies

---

testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ChunkedTransferEncodingUnitTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/FakeHttpServer.java

I encountered the following, spurious Travis errors:
```
Running org.jboss.resteasy.test.client.ChunkedTransferEncodingUnitTest
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.044 sec <<< FAILURE! - in org.jboss.resteasy.test.client.ChunkedTransferEncodingUnitTest
testChunkedRequest(org.jboss.resteasy.test.client.ChunkedTransferEncodingUnitTest)  Time elapsed: 0.028 sec  <<< ERROR!
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine.invoke(ApacheHttpClient43Engine.java:272)
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:484)
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:63)
at …
```

Improve ChunkedTransferEncodingUnitTest robustness

---

testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/TypesBuiltInTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/resource/TypesParamConverterPOJO.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/resource/TypesTestProvider.java

Update TypesBuiltInTest to use ParamConverter
Jira: https://issues.jboss.org/browse/RESTEASY-2072
3.6: https://github.com/resteasy/Resteasy/pull/1783

[RESTEASY-2072] Update TypesBuiltInTest to use ParamConverter

---

resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlWriter.java

https://issues.jboss.org/browse/RESTEASY-2070
wadl - Useless control flow - if ends with semi-colon
`iter.remove()` is performed every time

[RESTEASY-2070] wadl - Useless control flow - if ends with semi-colon

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncBenchTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorBasicTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcastTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseBroadcastResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultMediaTypeTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java

Jira: https://issues.jboss.org/browse/RESTEASY-2077
3.6 PR: https://github.com/resteasy/Resteasy/pull/1789
Cleanup of ignored tests:
* DuplicitePathTest
* related bug is fixed
* fix test
* remove ignoring
* SseBroadcastTest
* add description to ignore annotation
* improve ignored tests (cc @jimma )
* btw, related jira was reopened [RESTEASY-1819](https://issues.jboss.org/browse/RESTEASY-1819)
* AsyncBenchTest
* improve javadoc
* add description to ignore annotation
* ResourceClassProcessorBasicTest
* add description to ignore annotation
* DefaultMediaTypeTest
* improve javadoc

[RESTEASY-2077] Cleanup of ignored tests

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java

jira: https://issues.jboss.org/browse/RESTEASY-2096
This issue is valid for master branch only
---
Remove all usage of removed ExpectedFailingOnWildFly12 class
ExpectedFailingOnWildFly12 was removed by https://github.com/resteasy/Resteasy/pull/1798, but it was introduced again by un-rebased https://github.com/resteasy/Resteasy/pull/1790

[RESTEASY-2096] Remove all usage of removed ExpectedFailingOnWildFly12 class

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseWithEntityTest.java

Jira: https://issues.jboss.org/browse/RESTEASY-2097

[RESTEASY-2097]: ClientResponse.getEntity() and ClientResponse.bufferEntity() do not completely follow the spec

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientRequestContextImpl.java

The reason for this change is to be able to better implement MicroProfile Rest Client 1.2 in SmallRye,
see:
https://github.com/michalszynkiewicz/smallrye-rest-client/commit/99e05e97932e5b53bb4161594950c3ef7dba9a2d#diff-7b1121516d3f6222abe697292542ecf2R35

[RESTEASY-2111] Expose client invocation from ClientRequestContextImpl

---

arquillian/RESTEASY-736-jetty/pom.xml
profiling-tests/pom.xml
providers/jackson2/pom.xml
providers/jaxb/pom.xml
providers/json-binding/pom.xml
providers/json-p-ee7/pom.xml
providers/multipart/pom.xml
providers/resteasy-html/pom.xml
providers/resteasy-validator-provider-11/pom.xml
resteasy-cache/resteasy-cache-core/pom.xml
resteasy-cdi/pom.xml
resteasy-core-spi/pom.xml
resteasy-core/pom.xml
resteasy-dependencies-bom/pom.xml
resteasy-guice/pom.xml
resteasy-jsapi/pom.xml
resteasy-links/pom.xml
resteasy-servlet-initializer/pom.xml
resteasy-spring/pom.xml
resteasy-stats/pom.xml
resteasy-wadl-undertow-connector/pom.xml
resteasy-wadl/pom.xml
security/resteasy-crypto/pom.xml
server-adapters/resteasy-jdk-http/pom.xml
server-adapters/resteasy-netty4-cdi/pom.xml
server-adapters/resteasy-netty4/pom.xml
server-adapters/resteasy-vertx/pom.xml
testsuite/integration-tests-spring/pom.xml
testsuite/integration-tests/pom.xml

Upgrade Java Servlet API from 3.1 to 4.0
https://issues.jboss.org/browse/RESTEASY-2119

[RESTEASY-2119] Upgrade Java Servlet API from 3.1 to 4.0

---

jboss-modules/pom.xml
providers/jaxb/pom.xml
resteasy-core-spi/pom.xml
resteasy-core/pom.xml
resteasy-dependencies-bom/pom.xml
resteasy-guice/pom.xml
resteasy-links/pom.xml
resteasy-spring/pom.xml
resteasy-stats/pom.xml
security/resteasy-crypto/pom.xml
server-adapters/resteasy-jdk-http/pom.xml
server-adapters/resteasy-vertx/pom.xml

Upgrade Common Annotations API from 1.2 to 1.3
https://issues.jboss.org/browse/RESTEASY-2120

[RESTEASY-2120] Upgrade Common Annotations API from 1.2 to 1.3

---

resteasy-dependencies-bom/pom.xml
testsuite/microprofile-tck/pom.xml

[RESTEASY-2124] microprofile-tck cleanup + move to wildfly-microprofile-config-smallrye
https://issues.jboss.org/browse/RESTEASY-2124
wildfly-microprofile-config-implementation is just experimental artifact, smallrye based one it the right one

[RESTEASY-2124] microprofile-tck cleanup + move to wildfly-microprofile-config-smallrye

---

arquillian/RESTEASY-1056-jetty-bv11/pom.xml
resteasy-dependencies-bom/pom.xml

wiremock update, commons-logging removal
https://issues.jboss.org/browse/RESTEASY-2123
json-patch will be covered in separate PR
Issue which proposes 3 possible solutions for json-patch is https://issues.jboss.org/browse/RESTEASY-2126

[RESTEASY-2123] wiremock update, commons-logging removal

---

.travis.yml
pom.xml

Jira: https://issues.jboss.org/browse/RESTEASY-2128
Re-enabling javadoc for JDK 11 by reverting commit f97ba8cce.
Thanks @rsvoboda for the found workaround.

 [RESTEASY-2128] JDK-8212233 workaround

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/FormProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/ProcessorFactory.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ProxyParameterAnotations.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ProxyParameterAnotationsResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/RESTEasyParamBasicTest.java

RESTEASY issue: https://issues.jboss.org/browse/RESTEASY-2105
It is now possible to use any of the org.jboss.resteasy.annotations.jaxrs.*Param annotations in proxy and MP REST client.

[RESTEASY-2105] - org.jboss.resteasy.annotations.jaxrs.*Param annotations don't work with both proxy and MP REST client

---

resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/TestLinksInvalidEL.java

This test is automatically fixed, because we have uniformed the `@AddLink` annotation to work for both JAXB and Jackson provider.

RESTEASY-2113 Fix testELWorksWithoutPackageJSON

---

providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ResteasyConstraintViolation.java
resteasy-dependencies-bom/pom.xml
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/JaxbXmlRootElementProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationJaxbTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationXMLTest.java

Another proposal for fixing RESTEASY-2107, with minimum disruption. The idea is to avoid introducing yet another mechnism for controlling precedences in json providers on client side. The user can either build the ResteasyProviderFactory with the providers he wants or he can control the classpath deciding which provider module is available.

RESTEASY-2107 2nd proposal

---

resteasy-jsapi/src/main/resources/resteasy-client.js

Some reverse proxies add a charset specification after the content-type: e.g. `application/json;charset=utf-8`. More details here: https://www.npmjs.com/advisories/8 .
This needs to be recognized as application/json as well.

Ignore charset when checking the content type

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/AbstractCollectionProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/FormParamProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/HeaderParamProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/MatrixParamProcessor.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/QueryParamProcessor.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyUriBuilder.java
resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilderImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/QueryParamAsPrimitiveTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/QueryParamAsPrimitiveResourceArray.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/QueryParamAsPrimitiveResourceResourceArray.java

RESTEASY issue: https://issues.jboss.org/browse/RESTEASY-2100
Enhanced speed of the QueryParam processing in the proxy client. It is achieved by using StringBuilder and passing the data as array to the ResteasyUriBuilderImpl.java.
I have fixed the failing test and run few builds in Travis CI on the "21a40d2" commit to ensure there aren't intermittent failures:
https://travis-ci.org/MMarus/Resteasy/builds

[RESTEASY-2100] - The byte[] type of input parameter in proxy/MP-rest-client will cause large JVM stack used. 

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java

Due to GenericType.equals implementation currently (as per 3.6.2.Final) SseBroadcasterImpl always removes first item from the outputQueue in notifyOnCloseListeners method when client closes connection. Resulting in other clients stop receive events.
Test project that reproduces the issue and suggest workaround: [link](https://github.com/Ingvord/resteasy-sse-bug-report)

[RESTEASY-2083] Fix issue when SseBroadcasterImpl.notifyOnCloseListeners removes wrong sink from the outputQueue

---

.travis.yml
testsuite/README.MD
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/setup/AbstractUsersRolesSecurityDomainSetup.java
testsuite/config/enable-elytron-full.cli
testsuite/integration-tests-spring/deployment/pom.xml
testsuite/integration-tests-spring/inmodule/pom.xml
testsuite/integration-tests/pom.xml
testsuite/pom.xml

https://issues.jboss.org/browse/RESTEASY-2166
These commits allow for testing with Elytron security domains against recent WildFly builds and running this configuration with JDK11.
The change of configuration of travis testing is just for a verification of the changes and serves as an example, I don't think we need to double the testing execution time this way.

[RESTEASY-2166] Review elytron testing

---

.travis.yml
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly13.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJaxbCoexistenceTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/ProxyWithGenericReturnTypeJacksonTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
testsuite/pom.xml

Jira: https://issues.jboss.org/browse/RESTEASY-2173
3.7 PR: https://github.com/resteasy/Resteasy/pull/1881
Move towards WildFly 16
*  set default server version to WildFly 16
*  update Travis configuration to run WF 14/15/16

[RESTEASY-2173] Move towards WildFly 16

---

testsuite/integration-tests/pom.xml

https://issues.jboss.org/browse/RESTEASY-1884
It was decided not to spend more time with getting rid of multiple executions so this PR just adds comment to track already taken effort should we find ourselves in similar situation in the future.

[RESTEASY-1884] Add comment with issue so that we don't forget about it

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/Params.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ProxyBeanParam.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ProxyBeanParamResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/RESTEasyParamBasicTest.java

Resteasy issue: https://issues.jboss.org/browse/RESTEASY-1955
The  verifyInterface() method in MicroprofileClientBuilder didn't take into account that @PathParam's can be also defined in the @BeanParam annotated class. Therefore this PR adds behaviour to populate @PathParam's from the @BeanParam as well in the verifyInterface() method.

[RESTEASY-1955] - MicroprofileClientBuilder can't handle nested @BeanParam's

---

providers/jackson2/pom.xml
providers/json-binding/pom.xml
providers/json-p-ee7/pom.xml
providers/resteasy-atom/pom.xml

https://issues.jboss.org/browse/RESTEASY-2181
This PR fixes warning because of missing jboss-logging-annotations on the classpath:
```
[INFO] Compiling 8 source files to /home/travis/build/resteasy/Resteasy/providers/jackson2/target/classes
--
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] unknown enum constant org.jboss.logging.annotations.Message.Format.MESSAGE_FORMAT
reason: class file for org.jboss.logging.annotations.Message$Format not found
[WARNING] unknown enum constant org.jboss.logging.annotations.Message.Format.MESSAGE_FORMAT
```
According to jboss logging docs https://jboss-logging.github.io/jboss-logging-tools/ all three dependencies should be declared to function properly so to be consistent I declared them also in other providers if they …

[RESTEASY-2181] Unify jboss-logging dependencies among providers

---

server-adapters/resteasy-undertow-spring/pom.xml

https://issues.jboss.org/browse/RESTEASY-2009
This is a follow-up for https://github.com/resteasy/Resteasy/pull/1916 which introduced new warnings into build caused by duplicated dependencies declaration.

[RESTEASY-2009] Remove duplicated dependencies

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyClassloaderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ClassloaderResource.java

Issue: https://issues.jboss.org/browse/JBEAP-16542
Upstream Issue: https://issues.jboss.org/browse/RESTEASY-2157
Upstream PR: #1914 
cherry-picked from:
https://github.com/resteasy/Resteasy/commit/80440df6576bf282bd61e6d80eb09b34ee5a9c42
https://github.com/resteasy/Resteasy/commit/7053eddcc5f36d97af4035f91d874509e4fc4938

[JBEAP-16542,RESTEASY-2157] Resteasy is not able to load the proxy interface

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyUriBuilder.java
resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilderImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ClientFilterResponseBuilderTest.java

https://issues.jboss.org/browse/RESTEASY-2181
Fix few calls of methods with varargs which causes compiler warnings for ambiguity. 
I also slightly modified javadoc for used method, but there might be more changes needed (that should have been done with changes in https://issues.jboss.org/browse/RESTEASY-2100) so I may remove these change and address it individually.

[RESTEASY-2181] Be explicit about non-varargs call

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponse.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/AbstractBuiltResponse.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/BuiltResponse.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/BuiltResponseEntityNotBacked.java
resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasyView.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ClientFilterResponseBuilderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ResponseBuilderCustomResponseFilter.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/MessageSanitizerMediaTypeTest.java

* [RESTEASY-1991] Exception removed from BuiltResponse readEntity and code added for the task.  BuiltResponseEntityNotBacked created to support existing exception throwing scenarios.  ClientFilterResponseBuilderTest created to test code change.
* Update ClientResponse.java
I changed "    " (four spaces) to "   " (three spaces), and the diff is *much* easier to read.

[RESTEASY-1991] response builder built response (#1835)

---

testsuite/integration-tests-spring/inmodule/src/test/resources/org/jboss/resteasy/test/spring/inmodule/module/module.xml

Remove dependency to "org.jboss.metadata" module from "inmodule" module of ts.
This module was private and have beed removed in [WFLY-11679](https://issues.jboss.org/browse/WFLY-11679).
This module is not necessary for the run of tests in "inmodule" module. All "inmodule" tests passes without "org.jboss.metadata" dependency.
This issue is not valid with WF16 (travis testing), but this issue is valid with latest WF.
---
Jira: https://issues.jboss.org/browse/RESTEASY-2197
3.7 PR: https://github.com/resteasy/Resteasy/pull/1951

[RESTEASY-2197] Remove dependency to org.jboss.metadata

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithoutCertificateTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslTestBase.java

SslServerWithoutCertificateTest fails if -Dnode is used.
Jira: https://issues.jboss.org/browse/RESTEASY-1404
Master PR: https://github.com/resteasy/Resteasy/pull/1954

[RESTEASY-1404] Fix SslServerWithoutCertificateTest for non-localhost rest run

---

pom.xml

Enforce Java 8 for release
Bound to deploy phase, but haven't tried as I don't have credentials to deploy.
Please try to deploy a snapshot release with Java 11 if the check kicks in properly.
I tried to bind it to compile phase and it worked well.
I noticed some checks when invoking `mvn deploy`
```
[INFO] --------------< org.jboss.resteasy:resteasy-dependencies >--------------
[INFO] Building RESTEasy dependencies BOM 4.0.0-SNAPSHOT                 [1/57]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java-version) @ resteasy-dependencies ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven-version) @ resteasy-dependencies ---
...
Return code is: 401, ReasonPhrase: …
```

Enforce Java 8 for release

---

profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/InMemoryClientEngine.java
providers/fastinfoset/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/fastinfoset/FastinfoSetContext.java
providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBContextWrapper.java
resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestFacadeLinks.java
resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestLinkIds.java
resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestLinks.java
resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestSecureLinks.java
resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/TestLinksInvalidEL.java
resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/TestLinksNoPackage.java
server-adapters/resteasy-netty4-cdi/src/test/java/org/jboss/resteasy/plugins/server/netty/cdi/SeCdiNettyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/FooResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/TestApplication.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/RxInvokerTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/HomecontrolCustomJAXBContext.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ResponseHeaderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/RxCompletionStageResourceImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/JsonFormattedTracingInfoTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingApp.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/ProgammaticTest.java

https://issues.jboss.org/browse/RESTEASY-2205
This PR removes all compilation warnings on build of the project.
The change with javax.xml.bind.Validator is a workaround for JDK bug https://bugs.openjdk.java.net/browse/JDK-8042566
To get rid of warnings in JsonFormattedTracingInfoTest I had to fix the test itself as it was trying to map json directly to list of RESTEasyTracingMessage but then expecting list of list of maps.

[RESTEASY-2205] Fix all remaining warnings on build

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithCorrectCertificateTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWildcardHostnameCertificateTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWrongHostnameCertificateTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithoutCertificateTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslSniHostNamesTest.java

Minor fix for RESTEASY-1404
Jira: https://issues.jboss.org/browse/RESTEASY-1404
Master: https://github.com/resteasy/Resteasy/pull/1975

[RESTEASY-1404] Fix - create the builder using the JAX-RS API instead of ResteasyClientBuilderImpl

---

resteasy-core/src/main/java/org/jboss/resteasy/mock/MockHttpResponse.java

Given a Content-Type header with additional parameters after the charset
parameter, then the detected charset also contains the other parameters.
For example 'application/json;charset=UTF-8;version=1.0' would lead to a
charset of 'UTF-8;version=1.0'.
This commit fixes this issues by using the semicolon as a separator.

resteasy-core/MockHttpResponse: Fix charset detection

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/MessageSanitizerContainerResponseFilter.java

Please consider picking this into 4.0.0.Final -- we are encountering this exception with 4.0.0.CR2.  Thanks!
```
java.lang.ClassCastException: class java.util.LinkedList cannot be cast to class java.util.ArrayList (java.util.LinkedList and java.util.ArrayList are in module java.base of loader 'bootstrap')
at org.jboss.resteasy.plugins.interceptors.MessageSanitizerContainerResponseFilter.filter(MessageSanitizerContainerResponseFilter.java:46)
at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:362)
at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:219)
```

Remove unnecessary and dangerous ArrayList cast

---

resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseReconnectResource.java

This PR cancel and replace previous one: https://github.com/resteasy/Resteasy/pull/1605
JIRA: https://issues.jboss.org/browse/RESTEASY-1958

[Resteasy 1958]: Reconnect delay override using last received 'retry' field value should not be a one time override

---

resteasy-core/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java

When CompletionStage completes exceptionally its exceptions are not wrapped, but when they complete exceptionally due to an exception throw in one of its pipeline callbacks (in thenApply() for example) then, CompletionStage wraps the exception before passing it to us. We should unwrap it, otherwise our exception mappers will never match and we get internal errors instead of the expected answers.

[RESTEASY-2229] Cs wrapped exception

---

resteasy-client/pom.xml
resteasy-core-spi/pom.xml
resteasy-core/pom.xml
security/jose-jwt/pom.xml

Remove unused dependencies from `resteasy-core` and `resteasy-core-spi`,
and add dependencies that were being depended on transitively.

Cleanup httpclient dependencies for resteasy-core

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/extractors/BodyEntityExtractor.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/GenericProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/BaseEntity.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/EntityExtendingBaseEntity.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/GenericEntityExtendingBaseEntity.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/GenericEntityExtendingBaseEntityProxy.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/GenericEntityExtendingBaseEntityResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/MultipleGenericEntities.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/MultipleGenericEntitiesProxy.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/GenericEntities/MultipleGenericEntitiesResource.java

RESTEASY issue: https://issues.jboss.org/browse/RESTEASY-1432
There was a problem with getting the GenericType from methods inside interfaces which use generics.

[RESTEASY-1432] - Interface with generic type does not work with client proxy

---

resteasy-dependencies-bom/pom.xml
security/jose-jwt/pom.xml

The JCIP Annotations are released under the [Creative Commons Attribution License](http://creativecommons.org/licenses/by/2.5), which is [not recommended for licensing software](http://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F).
I'd like to move them over to using the Apache-2.0 licensed version provided by @stephenc:
https://github.com/stephenc/jcip-annotations

Use Apache-2.0 licensed version of the JCIP annotations

---

profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/InMemoryClientEngine.java
resteasy-core/src/main/java/org/jboss/resteasy/core/InternalDispatcher.java
resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
resteasy-core/src/main/java/org/jboss/resteasy/mock/MockHttpRequest.java
resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java
resteasy-core/src/main/java/org/jboss/resteasy/specimpl/UnmodifiableMultivaluedMap.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/ResteasyHttpHeadersTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/UnmodifiableMultivaluedMapTest.java

ResteasyHttpHeaders.getRequestHeaders() and ResteasyHttpHeaders.getRequestHeader() must return not modifiable collection
Signed-off-by: NicoNes <nicolas.nesmon@gmail.com>

[RESTEASY-2268] ResteasyHttpHeaders does not follow JAX-RS spec concerning modifiability

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/ProviderFactoryTest.java
resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/SslTest.java

Modify MP REST Client implementation to be able to completely disable SSL class usage if it's not enabled. This helps with DCE.

[RESTEASY-2291] Native image improvements for MP REST Client on Quarkus

---

resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResourceInvoker.java
resteasy-core/src/main/java/org/jboss/resteasy/core/AcceptHeaderByFileSuffixFilter.java
resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceLocatorInvoker.java
resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
resteasy-core/src/main/java/org/jboss/resteasy/core/registry/Expression.java
resteasy-core/src/main/java/org/jboss/resteasy/core/registry/MatchCache.java
resteasy-core/src/main/java/org/jboss/resteasy/core/registry/MethodExpression.java
resteasy-core/src/main/java/org/jboss/resteasy/core/registry/RootNode.java
resteasy-core/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
resteasy-core/src/main/java/org/jboss/resteasy/mock/MockHttpRequest.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletUtil.java
resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriInfo.java
security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/doseta/DigitalSigningInterceptor.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyUtil.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxUtil.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/resource/UriInfoSimpleResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/TrailingSlashTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/request/ContainerRequestContextTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/BenchmarkTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/TrailingSlashTest.java

I screwed up my squash merge.  Redoing PR.
* Matches are now cached if and only if its a static regular expression i.e. no path params and only if the match is a resource method (not resource locator). Match is based on path, content-type and accept header. This avoids all the complex and expensive matching that happens, especially for content negotiation. Future approach would be to further optimize the matching layer for simple cases.
* Lazy instantiation of ResteasyUriInfo things. This was a pretty expensive operation
* Improvements to Netty layer.

performance improvements

---

providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java

Master version of #1984 
Replace Jackson's AnnotationBundleKey with an implementation that uses `.equals()` instead of `==` to compare annotations. AnnotationBundleKey assumed annotation references were unique which breaks because the JRE doesn't cache parameter annotations, returning new references each time parameter annotations are queried. This was causing a severe performance degradation over time since matching ClassAnnotationKey instances had the same `hashCode` while failing equality checks, leading to a large and growing single bucket with identical objects and lock contention.

ResteasyJackson2Provider: fix ConcurrentHashMap contention

---

resteasy-bom/pom.xml

This prevents RESTEASY-2317 from being included in 3.9.0.Final and also fixes the versioning issue that I patched on master just before 4.2.0.Final release

resteasy-bom fixes as a consequence of RESTEASY-1864 changes

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/OptionalInjectionTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/OptionalResource.java

RESTEASY-1419 - Add support for injecting Optional<T> parameter types
This is the backport for branch 3.9

RESTEASY-1419 - Add support for injecting Optional<T> parameter types

---

resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ClassLevelMediaTypeTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/resource/ClassLevelMediaTypeResource.java

JIRA: https://issues.jboss.org/browse/RESTEASY-2244

[RESTEASY-2244] @Produces not picked up well

---

jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jackson-provider/main/module.xml
jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly12.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloClient.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
testsuite/pom.xml

Backporting RESTEASY-2042 to the 3.6.1.SPx branch.
https://issues.jboss.org/browse/RESTEASY-2042

[RESTEASY-2042] module.xml in resteasy-jaxrs is missing dependency to microprofile-config-api

---

resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/HttpRequest.java
resteasy-core/src/main/java/org/jboss/resteasy/mock/MockHttpRequest.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletInputMessage.java
resteasy-core/src/main/java/org/jboss/resteasy/util/DelegatingHttpRequest.java
server-adapters/resteasy-jdk-http/src/main/java/org/jboss/resteasy/plugins/server/sun/http/HttpServerRequest.java
server-adapters/resteasy-jdk-http/src/test/java/org/jboss/resteasy/test/HttpContextTest.java
server-adapters/resteasy-jdk-http/src/test/java/org/jboss/resteasy/test/SimpleResource.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/NettyTest.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxRequestHandler.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/VertxTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/ResteasyRequestTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/resource/RequestResource.java

New interface ResteasyRequest extends JAX-RS Request with those methods
But it delegates to HttpRequest (perhaps we don't need both?)
This works, but we need to make some decisions:
- Do we keep `ResteasyRequest` as a subtype of JAX-RS `Request`, or do we tell users to inject RESTEasy's `HttpRequest` which has to have those methods anyway?
- Do we keep the `String getRemoteAddress/getRemoteHost` duo or go for something like `InetSocketAddress getRemoteAddress` like Netty has?
WDYT @patriot1burke @asoldano ?

Add support for remote ip/address without requiring HttpServletRequest

---

resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/Utils.java

This is meant to address part of https://github.com/quarkusio/quarkus/issues/4345

Cache lookups that yield a null HeaderDelegate

---

resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
resteasy-spring-web/src/main/java/org/jboss/resteasy/spi/metadata/SpringResourceBuilder.java
testsuite/integration-tests-spring-web/deployment/pom.xml
testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/TestController.java

if no annotation values (for "name" or "value") are supplied the method parameter name will be used
Related to Quarkus [#3992](https://github.com/quarkusio/quarkus/issues/3992) issue
Could you @geoand please review this and forward it to someone else if necessary?

feat: use the method parameter name if annotation configuration is not provided

---

resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java
resteasy-core/src/main/java/org/jboss/resteasy/specimpl/UnmodifiableMultivaluedMap.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/UnmodifiableMultivaluedMapTest.java

Relates to: https://github.com/quarkusio/quarkus/issues/4345
Basically in a lot of the benchmarks the EntrySet of `UnmodifiableMultivaluedMap` is never queried, however without this patch it is always created.
During CPU profiling (using async-profiler) of Quarkus `0.24.0` which uses RESTEasy `4.3.1.Final`  I discovered entries like the following:
```
--- 220900450 ns (0.13%), 22 samples
[ 0] ObjectSynchronizer::FastHashCode(Thread*, oopDesc*)
[ 1] JVM_IHashCode
[ 2] java.lang.Object.hashCode
[ 3] java.util.HashMap.hash
[ 4] java.util.HashMap.put
[ 5] java.util.HashSet.add
[ 6] org.jboss.resteasy.specimpl.UnmodifiableMultivaluedMap.buildEntrySet
[ 7] org.jboss.resteasy.specimpl.UnmodifiableMultivaluedMap.<init>
[ 8] org.jboss.resteasy.specimpl.ResteasyHttpHeaders.<init>
[ 9] …
```

Allow UnmodifiableMultivaluedMap to create EntrySet lazily

---

resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/BaseServletConfigSource.java

`source` may be null, causing a NPE in the getName() method.

Fix NPE when ConfigSource is not available

---

resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasySpringDispatcherServlet.java
testsuite/integration-tests-spring/inmodule/pom.xml
testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/RESTEasy828Test.java
testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/resource/RESTEasy828Resource.java
testsuite/integration-tests-spring/inmodule/src/test/resources/org/jboss/resteasy/test/spring/inmodule/resteasy828/applicationContext.xml
testsuite/integration-tests-spring/inmodule/src/test/resources/org/jboss/resteasy/test/spring/inmodule/resteasy828/web.xml

The default Spring `DispatcherServlet` doesn't push the  `ServletContext` into `ResteasyContext` properly, however using `DispatcherServlet` is a convenient way to configure `springframework`, so we need to provided a `ResteasySpringDispatcherServlet` for users to use.
Please note using `DispatcherServlet` is not the only way to configure the RESTEasy/Spring integration, and we also have the other ways such as:
- Using the `resteasy-spring-boot` project to eliminate the manual configuration with Spring/SpringMVC: https://github.com/resteasy/resteasy-spring-boot
- Totally configuring the `web.xml` manually to setup spring container properly and don't use `DispatcherServlet` at all(which is very verbose and not the standard way described in document), and here is the example: …

RESTEASY-828 Issue with injected ServletContext in Resteasy/SpringMVC setup

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/InvocationContextImpl.java

fixes https://github.com/quarkusio/quarkus/issues/4774

MP Rest Client allow async interceptor invocation

---

resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineByteBufReleaseTest.java
resteasy-dependencies-bom/pom.xml

Update project reactor version to Dysprosium-SR2 (3.3.x)
Minor fix to the utests for netty buffer leak detection

Update project reactor version to Dysprosium-SR2

---

profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/InMemoryClientEngine.java
resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientResponse.java
resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineByteBufReleaseTest.java
resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AbortedResponse.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/FinalizedClientResponse.java

To improve gc remove finalize from ClientResponse and re-add finalize
at the specific client implementation
Make finalize addition configurable with the ReactorNettyClientHttpEngine RestEasyClientReponse.

RESTEASY-2454: Remove finalize from ClientResponse to improve gc

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/PartialResponse.java

I haven't found any corresponding tests or documentation to be updated.
As it clearly violates the spec, maybe there's one missing from the Microprofile TCK?
And I agree with the Apache 2.0 license.

[RESTEASY-2460] Fix TODO in PartialResponse#getMetadata

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionClientEngineBuilder.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java

I observed an issue using Quarkus, which uses the RestEasy REST Client, for which I have opened an issue here:
https://github.com/quarkusio/quarkus/issues/6522
It concerns an issue where the http-proxy setup with a `RestClientBuilder` would not work, i.e. the settings are completely ignored in the following setup:
```
MyRestClient build = RestClientBuilder.newBuilder()
.baseUri(UriBuilder.fromUri("http://localhost:3001").build())
.property(PROPERTY_PROXY_HOST, "localhost") //ignored
.property(PROPERTY_PROXY_PORT, 3002) //ignored
.property(PROPERTY_PROXY_SCHEME, "http") //ignored
.build(MyRestClient.class);
```
The change concerns this part of `ResteasyClientBuilderImpl`:
```
boolean resetProxy = false;
if (this.defaultProxy == null) {
resetProxy = true;
// check for proxy config …
```

[RESTEASY-2486] Fix for RestEasyClientBuilder http proxy not working

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java

RESTEASY-1986 backport to 3.6.1.Spx.
Issue: https://issues.redhat.com/browse/RESTEASY-2492
Upstream Issue: https://issues.redhat.com/browse/RESTEASY-1986
Upstream PR: https://github.com/resteasy/Resteasy/pull/1862

[RESTEASY-1986] Lower log level to DEBUG as the exception is rethrown

---

resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractWriterInterceptorContext.java
resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ServerWriterInterceptorContext.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/AsyncIOWriterResource.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/AsyncIOWriterTest.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/MyType.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/MyTypeInterceptor.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/MyTypeWriter.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/SSEResource.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/SSETest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/InterceptorResource.java

Re-resolve the writer after all interceptors are done, making sure we don't get a blocking
one after we started with an async one

Fixed TCK test, added passing version of SSE TCK test

---

providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyAbstractDataObject.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyDataObject.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyResourceIntf.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlySingletonResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatefulResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatelessResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyTestApplication.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/validation/NoFieldValidationEJBTest.java

Issue: https://issues.redhat.com/browse/RESTEASY-2503
This is the cheery-pick of https://github.com/resteasy/Resteasy/pull/2324 to `3.11` branch for `WildFly master` and `EAP 7.3` unless we have plan to upgrade Resteasy to 3.12 in both streams.

[3.11] [RESTEASY-2503] Throw ViolationException for EJBs with just parameter violations.

---

resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java

Fix for https://github.com/quarkusio/quarkus/issues/8675
The root cause of the problem was not setting the content type, but it still should not return a 200 response if writing the error fails.

Set response code to 500 if writing exception fails

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/HeaderParamProcessor.java

AbstractInvocationCollectionProcessor is processing Array and Collection of elements being ParamConverter aware. But with single values is delegating in final class to process the value. HeaderParamProcessor is not being aware of such transformation.
See https://issues.redhat.com/browse/RESTEASY-2495

[RESTEASY-2495] ParamConverter not being applied to HeaderParam

---

jboss-modules/build.xml
jboss-modules/pom.xml
jboss-modules/src/main/resources/modules/com/ibm/async/asyncutil/main/module.xml
jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
resteasy-core/pom.xml
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileRangeWriter.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/ProviderHelper.java
resteasy-dependencies-bom/pom.xml
server-adapters/resteasy-undertow/src/test/java/org/jboss/resteasy/test/undertow/AsyncIOResource.java
server-adapters/resteasy-undertow/src/test/java/org/jboss/resteasy/test/undertow/AsyncIOTest.java

Proper fix for #2342, as described there.
This PR introduces a new (tiny) dependency that is required to properly implement loops using `CompletionStage`. I'm not sure if it's best to add a jboss modules for it, or include it in the jaxrs-all module.
Need guidance from @asoldano about this.

Fix RESTEASY-2526 by using asyncutil lib for async loops

---

.github/workflows/maven.yml
resteasy-client-jetty/src/test/java/org/jboss/resteasy/test/client/jetty/JettyClientEngineTest.java
resteasy-core-spi/pom.xml
resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestWadlFunctions.java
server-adapters/resteasy-jdk-http/src/main/java/org/jboss/resteasy/plugins/server/sun/http/SunHttpJaxrsServer.java
server-adapters/resteasy-jdk-http/src/test/java/org/jboss/resteasy/test/HeadContentLengthTest.java
server-adapters/resteasy-jdk-http/src/test/java/org/jboss/resteasy/test/HttpContextTest.java
server-adapters/resteasy-jdk-http/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/NettyTest.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/SniTest.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/DeploymentTest.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/VertxTest.java
testsuite/arquillian-utils/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/JaxrsAsyncServletTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/ResteasyRequestTest.java
testsuite/microprofile-tck/pom.xml
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/common/FakeHttpServer.java

https://issues.redhat.com/browse/RESTEASY-2561
https://issues.redhat.com/browse/RESTEASY-2564
The first commit fixes tests to work on multiple environments.
The second change adds a GitHub Action and ignores the MicroProfile TCK for Windows
The third commit uses a default 10 second delay when stopping the `SunHttpJaxrsServer`. This only delays 10 seconds if the server has not successfully stopped in that delay.

Add GitHub Actions for CI

---

.github/workflows/maven.yml

After some thought I'm wondering if we really want to add archived logs for successful jobs. It adds unneeded archives and clutters the UI. Also just keeps down on the size of retained data.
This is definitely not required so feel free to close it if we'd rather keep all the archives.

Only upload archives for failed runs. Also fix the name to not end with ".zip"

---

server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilter.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncResponseFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/CallbackSecondSettingCompletionCallback.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/CallbackSettingCompletionCallback.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseNoStreamTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/SingleProvider.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/AsyncResponseCallback.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseNoStreamResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseResource.java

A bunch of changes in test classes to prevent concurrency related issues that might be causing the intermittent failure of org.jboss.resteasy.test.response.CompletionStageResponseTest and similar tests.

CompletionStageResponseTest intermittent failures

---

resteasy-core/src/main/java/org/jboss/resteasy/core/AbstractAsynchronousResponse.java
resteasy-core/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/AnotherPublisherResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseNoStreamTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseRawStreamTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseNoStreamResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseRawStreamResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseResource.java

Fix for https://issues.redhat.com/projects/RESTEASY/issues/RESTEASY-2573

[RESTEASY-2573] ResteasyContext never popped for SSE async streams

---

testsuite/README.MD

The README suggests to run a single test like this `mvn surefire:test@default-test ...`
the problem is that directly invoking the execution-id `surefire:test@default-test` makes it impossible to automatically start the `wiremock-maven-plugin` in the case of `microprofile-tck` tests;
In facts, running `mvn help:effective-pom` from testsuite/microprofile-tck:
```
<plugin>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.19.1</version>
<executions>
<execution>
<id>default-test</id>
<phase>test</phase>
<goals>
<goal>test</goal>
</goals>
```
we see it's actually invoking this which the `default-test` execution;

How to run a single microprofile-ck test

---

server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyUtil.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyUtil.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/HeaderEmptyHostTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/HeaderEmptyHostTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/HeaderEmptyHostResource.java

Issue: https://issues.redhat.com/browse/RESTEASY-2300
Upstream PR: https://github.com/resteasy/Resteasy/pull/2435

[RESTEASY-2300] Blank Host Name still throws exception

---

resteasy-spring-web/src/main/java/org/jboss/resteasy/spi/metadata/SpringResourceBuilder.java
testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/SpringWebTest.java

Fixes: https://github.com/quarkusio/quarkus/issues/10133

Fix issue with Spring Web parameters encoding

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/HttpHeadersContextProvider.java
resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java

JAX-RS mandates that HttpHeaders.getAcceptableLanguages() returns a
single wildcard locale instance if no acceptable languages are defined.
I agree on the Apache License 2.0 terms.

[RESTEASY-2634] Fix HttpHeaders.getAcceptableLanguages

---

resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java

This PR wraps calls to `System.getProperty(...)` and `Integer.getInteger(...)` in doPriv blocks to ensure that they will work with a Java 2 security manager enabled.

[RESTEASY-2642] Add doPrivs to sys prop checks

---

jboss-modules/build.xml
providers/jackson2/pom.xml
resteasy-dependencies-bom/pom.xml

Upgrades json-patch to 1.13.
as a biggest bonus (and main reason for doing this) we get rid of guava dependency in jackson provider.

RESTEASY-2648 Upgrade json-patch to 1.13

---

resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Encode.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java

[RESTEASY-2633] Encode code points that span multiple characters - utf-8 mb4, emojis
Backport of #2456 and #2480

[RESTEASY-2633] Encode code points that span multiple characters

---

resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java

https://issues.redhat.com/browse/RESTEASY-2674 - Escape sign of quotation to see the value of parameter
Without this fix I don't see value of the parameter, regression against RESTEasy 4.5.3.Final / Quarkus 1.3.4.Final
Reproducer:
When using https://github.com/gastaldi/resteasy-xss and these changes
```diff
--- a/pom.xml
+++ b/pom.xml
@@ -12,10 +12,10 @@
<maven.compiler.target>1.8</maven.compiler.target>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
-    <quarkus-plugin.version>1.2.1.Final</quarkus-plugin.version>
+    <quarkus-plugin.version>1.7.0.CR2</quarkus-plugin.version>
<quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id> …
```

RESTEASY-2674 Escape sign of quotation to see the value of parameter

---

resteasy-core/src/main/java/org/jboss/resteasy/core/MediaTypeMap.java

The `cache` can result in null at initialization. I'm changing to always set the `cache` to `classCache` no matter if it was created by the same thread or by any another one. I also used a ConcurrentHashMap instead of normal HashMap.
I'm not protecting the setting part in `mergeEverything`, if you think it's necessary to protect it too just let me know.

[RESTEASY-2683] NPE in ApacheHttpClient43Test because cache is null in MediaTypeMap

---

pom.xml
resteasy-dependencies-bom/pom.xml
testsuite/README.MD
testsuite/arquillian-utils/pom.xml
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForBootableJar.java
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cache/ServerCacheInterceptorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorErrorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/CryptoTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingDebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
testsuite/integration-tests/src/test/resources/arquillian-bootable.xml
testsuite/pom.xml

Fixes https://issues.redhat.com/browse/RESTEASY-2694 for the 3.14 branch.
Same failures as for the 3.13 branch [1] when running against WFLY 21 Beta1 are reported at the moment, due to https://issues.redhat.com/browse/WFCORE-5143.
[1]
https://github.com/resteasy/Resteasy/pull/2526

[RESTEASY-2694] (3.14) Adding support for running test suite against bootable JAR

---

pom.xml
resteasy-dependencies-bom/pom.xml
testsuite/README.MD
testsuite/arquillian-utils/pom.xml
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForBootableJar.java
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cache/ServerCacheInterceptorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorErrorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/CryptoTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingDebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
testsuite/integration-tests/src/test/resources/arquillian-bootable.xml
testsuite/integration-tests/src/test/resources/jboss-deployment-structure-bouncycastle.xml
testsuite/pom.xml

Fixes https://issues.redhat.com/browse/RESTEASY-2694 for the 3.11 branch, currently used by EAP 7.3.x
There's still one Bouncycastle related integration test failure and only when WildFly 21.0.0.Final is being used. 
The test passes with WildFly 20 Final. Besides it seems to be affecting just bootable JAR executions + WFLY 21, see https://issues.redhat.com/browse/WFLY-13903?focusedCommentId=15335605&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15335605.
Anyway the test is not ignored or skipped because the destination (3.11) branch is not used by WildFly any more, hence not an issue here.
Draft because there are failures in MP REST Client TCK, @asoldano, @ronsigal, @marekkopecky do you have any thought?
*UPDATE*: same TCK failures when running the TS …

[RESTEASY-2694] (3.11) Adding support for running test suite against bootable JAR

---

resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java

This is needed because the client should be usable
regardless of the server implementation of JAX-RS
that might be in use

Ensure that multiple impls of UriBuilder don't cause a CCE

---

resteasy-client-microprofile-base/pom.xml
resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/publisher/MpPublisherMessageBodyReader.java
resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/publisher/SSEPublisher.java
resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/publisher/SpscLinkedArrayQueue.java
resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/publisher/Subscriptions.java
resteasy-client-microprofile-base/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/MPSseClient.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/SsePublisherClientTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/resource/MPSseResource.java

This PR is rebased with https://github.com/resteasy/Resteasy/pull/2578 and changes  the following things: 
1. Add executor to SSEPublisher to avoid block the Publisher emit
2. Add system property "resteasy.microprofile.sseclient.buffersize" to configure the Subscription queue size.
3. Add test for https://github.com/resteasy/Resteasy/pull/2578 and configure the Subscription queue size to 5 to check the overflow behavior.

Add test for https://github.com/resteasy/Resteasy/pull/2578

---

testsuite/pom.xml

At present, because of the use of property `forward.compatibility` for mutual exclusive profiles `default` and `forward.compatibility` we cannot exclude test modules `integration-tests`, `integration-tests-spring`, `microprofile-tck` from being executed for bootable jar

Fix bootable jar profile for branch 3.11

---

testsuite/README.MD

Fixes https://issues.redhat.com/browse/RESTEASY-2747
The -Delytron and -Dts.standalone.microprofile properties are mutually exclusive because both the related profiles need to set the server configuration file property value to the one of a custom file.
Besides, elytron is the default when dealing with microprofile. Hence there's no need for any configuration to be added, which is what the elytron profile does.
This PR is for updating documentation accordingly.

[RESTEASY-2747] (3.11) Adding documentation about mutually exclusive usage of -Delytron and -Dts.standalone.microprofile properties

---

testsuite/README.MD

Fixes https://issues.redhat.com/browse/RESTEASY-2747 for the `3.14` branch, by cherry-picking https://github.com/resteasy/Resteasy/pull/2587/commits/b35c498cc2d22fed4c79cd6ab8a8cbab019c7a13.
The -Delytron and -Dts.standalone.microprofile properties are mutually exclusive because both the related profiles need to set the server configuration file property value to the one of a custom file.
Besides, elytron is the default when dealing with microprofile. Hence there's no need for any configuration to be added, which is what the elytron profile does.
This PR is for updating documentation accordingly.

[RESTEASY-2747] (3.14) Adding documentation about mutually exclusive usage of -Delytron and -Dts.standalone.microprofile properties

---

testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java

Fixes https://issues.redhat.com/browse/RESTEASY-2749
This is to remove mail layer tests when executing bootable JAR test profile because so that it can be tested against EAP XP 2 feature pack, which currently does not provide such layer.

[RESTEASY-2749] (3.11) Remove mail layer tests when executing bootable JAR test profile

---

testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java

Fixes https://issues.redhat.com/browse/RESTEASY-2749 for the 3.14 branch, by cherry-picking https://github.com/resteasy/Resteasy/pull/2585/commits/b958515c29d402a4e38761e2655c1749f8ccbdc5.
This is to remove the mail layer tests when executing the bootable JAR test profile so that it can ready in advance (as requested in https://github.com/resteasy/Resteasy/pull/2585#pullrequestreview-526102363) to be tested against next versions of EAP XP 2 feature pack which would depend on RESTEasy 3.14.x, in case those will not yet provide such layer.
EAP XP 2 base (7.3.x) is currently using RESTEasy 3.11.x so the changes in here have been tested _just_ against WildFly 21 - as it was done when the `ts.bootable` profile was added, see https://github.com/resteasy/Resteasy/pull/2558 and the only failures …

[RESTEASY-2749] (3.14) Remove mail layer tests when executing bootable JAR test profile

---

testsuite/integration-tests/src/test/resources/jboss-deployment-structure-bouncycastle.xml

Fixes https://issues.redhat.com/browse/RESTEASY-2748
This is to comply with the EAP 7.3.x Bouncycastle module structure and to prevent the test deployment which use such configuration to fail.

[RESTEASY-2748] (3.11) Fixing Bouncycastle test deployment structure

---

resteasy-core/pom.xml
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletUtil.java
resteasy-core/src/test/java/org/jboss/resteasy/plugins/server/servlet/ServletUtilTest.java

This resolves JIRA [RESTEASY-2771](https://issues.redhat.com/browse/RESTEASY-2771) by decoding the incoming servlet request URL.  Thus requests like `GET /app%21/resource` will match app/resource combinations like:
```
@ApplicationPath("app%21")
public MyApp1 extends Application {}
```
```
@ApplicationPath("app!")
public MyApp2 extends Application {}
```
```
@Path("resource")
public MyResource {
@GET
public String get() {
return "Hello World!";
}
}
```

[RESTEASY-2771] Decode App Path portion of RequestURL

---

testsuite/integration-tests/pom.xml

Fixes https://issues.redhat.com/browse/RESTEASY-2769 for the `3.14` branch.
This is to comply with the EAP 7.3.x Bouncycastle module structure and to prevent the test deployment which use such configuration to fail Bootable JAR test executions.

[RESTEASY-2769] (3.14) Fixing Bouncycastle provisioning for Bootable JAR test executions

---

providers/jackson2/pom.xml
resteasy-links/pom.xml
security/jose-jwt/pom.xml
server-adapters/resteasy-undertow-spring/pom.xml

Some applications only need jackon, and where previously forced to exclude the jaxb-provider on their own. This compile dependency is now removed.
I also added jaxb-provider back to modules, which before only had jackson provider. This is to keep the same behavior for jose-jwt and resteasy-links.

[RESTEASY-2725] Remove dependency from jackson to the jaxb provider

---

resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java

fixes an issue where tomcat closes an http2 connection due to excessive overhead chatter from the reactor-netty client.
Please see this issue: https://issues.redhat.com/browse/RESTEASY-2746
The tomcat detects this error per the http2 spec:
ENHANCE_YOUR_CALM (0xb):  The endpoint detected that its peer is
exhibiting a behavior that might be generating excessive load.
The fix changes from sending an object to sending a fixed size buffer, enabling reactor-netty to reduce the number of overhead frames requires to complete the request.

Address premature connection close issue with reactor-netty and tomcat

---

security/jose-jwt/pom.xml
security/jose-jwt/src/main/java/org/jboss/resteasy/crypto/SignatureSignerContext.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/Algorithm.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/AlgorithmType.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSBuilder.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSHeader.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSInput.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSInputException.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/HMACProvider.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/RSAProvider.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/SignatureProvider.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Base64.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Base64Url.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/BouncyIntegration.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/DerUtils.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/JsonSerialization.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Key.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/PemException.java
security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/PemUtils.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/jose/JWSTest.java

Issue: https://issues.redhat.com/browse/JBEAP-20177
Upstream Issue: https://issues.redhat.com/browse/RESTEASY-2681
Upstream PR: https://github.com/resteasy/Resteasy/pull/2499
Backport for the RESTEASY-2681 in the 3.11/EAP_7.3 branch. Just the upstream PR but the `JWSInput` constructors are not modified, the old constructor signatures are maintained. The idea is avoiding further issues and the modifications needed in the calls.
@asoldano @rsearls @ronsigal Please take a look when you have time. Test pass OK and I have executed one round of tests in the jboss-eap7 branch too.

[JBEAP-20177] [RESTEASY-2681] merged changes from keycloak into code base

---

testsuite/integration-tests-spring/deployment/pom.xml
testsuite/integration-tests-spring/inmodule/pom.xml
testsuite/integration-tests/pom.xml
testsuite/pom.xml

Having e.g. `<excludedGroups>someclass1,,someclass3</excludedGroups>` causes `someclass3` to be ignored

Fix commas in excludedGroups

---

resteasy-core/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/OptionalInjectionTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/OptionalResource.java

Fix for https://issues.redhat.com/browse/RESTEASY-2776
Up to now, we have no way to use Optional types in a BeanParam, if we do so we get an error `RESTEASY003875`.
* Adds the missing wrap call to the remaining methods `createParameterExtractor` to ensure that Optional types are supported in all cases
* Changes the `OptionalResource` to cover cases where params are directly injected into the resource but also into a BeanParam

[RESTEASY-2776] Add support of Optional types in BeanParams

---

docbook/reference/en/en-US/modules/_OptionalParam.xml

Fix for https://issues.redhat.com/browse/RESTEASY-2776 (doc part)
Some documentation was needed to describe the new feature https://issues.redhat.com/browse/RESTEASY-2776
* Adds a new section in the documentation about `OptionalParam`

[RESTEASY-2776] Add some documentation about Optional types in BeanParams

---

resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
resteasy-dependencies-bom/pom.xml
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/ChunkOutputStream.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxJaxrsServer.java

This PR upgrades Resteasy to support vert.x 4
https://issues.redhat.com/browse/RESTEASY-2766 and https://issues.redhat.com/browse/RESTEASY-2665
Note: Vert.x 4 has no final release yet. This PR makes the relevant changes in preperation for the final release.

[RESTEASY-2766] Upgrade Resteasy to support vert.x 4

---

resteasy-core/src/main/java/org/jboss/resteasy/specimpl/RequestImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/PreconditionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/resource/PreconditionLastModifiedResource.java

Fix for https://issues.redhat.com/browse/RESTEASY-629
The method `evaluatePreconditions(Date)` is not useable as it is now when the input date has milliseconds because it will be compared with a date without milliseconds so it will always return `null` indicating that the content has changed which is incorrect.
* Trims the milliseconds from the input date before comparing the dates in order to compare dates with the same precision
* Adds the corresponding integration tests

[RESTEASY-629] Round down the datetime in seconds in evaluatePreconditions

---

resteasy-core/src/main/java/org/jboss/resteasy/mock/MockHttpRequest.java

In MockHttpRequest the PATCH verb is not supported immediately.
Though PATCH can be used with a workaround, it would be much clear if it explicitlty supported by it's own function.

[RESTEASY-2797] Add support PATCH MockHttpRequest

---

providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/WhiteListPolymorphicTypeValidatorBuilder.java
providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
resteasy-client-api/pom.xml
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
resteasy-core-spi/pom.xml
resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/config/Configuration.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/config/ConfigurationFactory.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/config/DefaultConfiguration.java
resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/config/ConfigurationTestCase.java
resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/config/TestConfigurationFactory.java
resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/config/TestResteasyConfiguration.java
resteasy-core-spi/src/test/resources/META-INF/services/org.jboss.resteasy.spi.config.ConfigurationFactory
resteasy-core/pom.xml
resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/core/config/DefaultConfigurationFactory.java
resteasy-core/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfigProvider.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
resteasy-core/src/main/java/org/jboss/resteasy/util/PortProvider.java
resteasy-core/src/main/resources/META-INF/services/org.jboss.resteasy.spi.config.ConfigurationFactory

https://issues.redhat.com/browse/RESTEASY-2767
This is an alternate to the approach  in #2590 which fully makes the Eclipse MicroProfile Config optional for RESTEasy.

[RESTEASY-2767] Make the Eclipse MicroProfile Config API optional.

---

providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/AbstractValidatorContextResolver.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientImpl.java
resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
resteasy-core/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/JaxrsInterceptorRegistryImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSourceImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSourceImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSourceImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DocumentProvider.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/JndiComponentResourceFactory.java
resteasy-core/src/main/java/org/jboss/resteasy/util/snapshot/SnapshotMap.java

Fix for https://issues.redhat.com/browse/RESTEASY-2798
Accessing to a volatile member has a cost in term of performances so it could be interesting to reduce the total amount of accesses to volatile member when it is possible.
* Lazy initializes by relying on a local variable to reduce volatile reads
* Use a local variable instead of doing several volatile reads within the same method
* Remove the modifier `volatile` from member fields that are only read and write in synchronized blocks
* Replace the modifier `volatile` by `final` when the fields are not modified
* Remove the modifier `volatile` from member fields that are read and write in pair with another `volatile` member field by relying on piggybacking

[RESTEASY-2798] Save accesses to volatile member

---

server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpResponse.java

https://issues.redhat.com/browse/RESTEASY-2826

[RESTEASY-2826] resteasy-vertx: Response Headers with String value of same type are overwritten

---

providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java

This change resolves an issue when a Java 2 security manager is present.

[RESTEASY-2842] DoPriv for file access in Mime4JWorkaround

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncTimeoutTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncTimeoutResource.java

This PR resolves JIRA [RESTEASY-2865](https://issues.redhat.com/browse/RESTEASY-2865) by ensuring that the `handleTimeout()` does not call `resume(new ServiceUnavailableException())` immediately after invoking the user's `TimeoutHandler`.

[RESTEASY-2865] setTimeout(..) in TimeoutHandler

---

docbook/reference/en/en-US/modules/Jaxb.xml
docbook/reference/en/en-US/modules/Multipart.xml
providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBContextWrapper.java
providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/XmlNamespacePrefixMapper.java
providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/i18n/Messages.java
providers/resteasy-atom/src/main/java/org/jboss/resteasy/plugins/providers/atom/AtomEntryProvider.java
providers/resteasy-atom/src/main/java/org/jboss/resteasy/plugins/providers/atom/AtomFeedProvider.java
resteasy-dependencies-bom/pom.xml
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/AtomProviderModelTest.java

This updates org.glassfish.jaxb:jaxb-runtime to version
3.0.0-M4.  This resolves the unit test failure in  
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/JaxrsAsyncTest.java
This archive version has the package name change to service
./META-INF/services/jakarta.xml.bind.JAXBContext and containes the new service impl file,
org.glassfish.jaxb.runtime.v2.ContextFactory.  The old service name was
./META-INF/services/javax.xml.bind.JAXBContext and its impl class name was
com/sun/xml/bind/v2/ContextFactory.class.
Also the old class name for com.sun.xml.bind.marshaller.NamespacePrefixMapper
has been changed to org.glassfish.jaxb.runtime.marshaller.NamespacePrefixMapper.
There are several files I had to update with this reference.
Please review the PR and if you think it …

updated archive jaxb-runtime to version 3.0.0-M4

---

.github/workflows/maven.yml
.travis.yml
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/AsynchronousCdiTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/TimerInterceptorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ResteasyConfigFilterTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ResteasyConfigServletContextListenerTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ResteasyConfigServletTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HeaderPropagator.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProviderPriorityTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/webapplicationexception_web.xml
testsuite/pom.xml

I prepared this PR for 3.15 branch. Let me know whether I should port this for master branch or squash commits into one commit.
* RESTEasy jira: https://issues.redhat.com/browse/RESTEASY-2837
* Another related jira: https://issues.redhat.com/browse/JBEAP-21087
----
Summary of this PR from jira:
* Parametrize resteasy-client-microprofile version in TS for servers without MP bits
* Skip ResteasyConfigServletContextListenerTest, ResteasyConfigFilterTest, RestClientProviderPriorityTest and ResteasyConfigServletTest tests on runs without MP bits. These tests requires MP on server side.
* Add `(testable = false)` to deployment methods to AsynchronousCdiTest, InjectionTest, MDBInjectionTest and TimerInterceptorTest tests, so Arquillian doesn't add arquillian classes to deployment. Arquillian …

TS updates

---

resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
resteasy-core/src/test/java/org/jboss/resteasy/core/ContextParameterInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/contextProxyInterfaces/ContextProxyInterfacesTest.java

The default should be false (i.e. only use the JAX-RS context interface, not other interfaces implemented by the delegate). This check is necessary because the reflection done in checking for additional interfaces does not work with Quarkus (where it expects the reflection to be done already in a Jandex index or something similar).

[RESTEASY-2866] Make proxy interface check configurable

---

.github/workflows/maven.yml
pom.xml
resteasy-core/pom.xml
resteasy-dependencies-bom/pom.xml
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/setup/AbstractUsersRolesSecurityDomainSetup.java
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtil.java
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilSpring.java
testsuite/integration-tests-spring-web/pom.xml
testsuite/integration-tests-spring/deployment/pom.xml
testsuite/integration-tests-spring/inmodule/pom.xml
testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/SpringMvcHttpResponseCodesTest.java
testsuite/integration-tests-spring/pom.xml
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EJBTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/CustomForbiddenMessageTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
testsuite/microprofile-tck/pom.xml
testsuite/pom.xml

There are several changes here mostly component upgrades and changes to the VM arguments required for Java 16. 
There is also a change to drop legacy security (PicketLink/PicketBox) configuration in WildFly in favor of Elytron. The legacy security will not work with Java 16+.
JIRA's:
- https://issues.redhat.com/browse/RESTEASY-2886
- https://issues.redhat.com/browse/RESTEASY-2895
- https://issues.redhat.com/browse/RESTEASY-2896
- https://issues.redhat.com/browse/RESTEASY-2897
- https://issues.redhat.com/browse/RESTEASY-2898
- https://issues.redhat.com/browse/RESTEASY-2899
- https://issues.redhat.com/browse/RESTEASY-2900
- https://issues.redhat.com/browse/RESTEASY-2902
- https://issues.redhat.com/browse/RESTEASY-2903
- https://issues.redhat.com/browse/RESTEASY-2904

[RESTEASY-2886] RESTEasy Java 16 Fixes

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/JsonpMPTest.java

https://issues.redhat.com/browse/RESTEASY-2912
Name of JsonpMPtest causes that it is not detected and executed by
surefire-plugin automatically [1].
[1] https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html

[RESTEASY-2912] Incorrect naming of JsonpMPtest class.

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/JsonpMPTest.java

Name of JsonpMPtest causes that it is not detected and executed by
surefire-plugin automatically [1].
[1] https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html
https://issues.redhat.com/browse/RESTEASY-2912

[3.15] [RESTEASY-2912] Incorrect naming of JsonpMPtest class.

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/JsonpMPTest.java

Name of JsonpMPtest causes that it is not detected and executed by
surefire-plugin automatically [1].
[1] https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html
https://issues.redhat.com/browse/RESTEASY-2912

[4.6] [RESTEASY-2912] Incorrect naming of JsonpMPtest class.

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-2933

[RESTEASY-2933] Upgrade Hibernate Validator to 6.0.22.Final

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FormUrlEncodedProvider.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/FormParamInjectionTest.java
testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/FormParamResource.java

The implementation of the FormUrlEncodedProvider currently does not handle FormParams with plaintext equal signs correctly. 
When the value of a param contains unecoded equal signs which is correct according to the whatwg spec (https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set), the FormUrlEncodedProvider cuts of everything after the first equal sign.
In the parse algorithm definition in https://url.spec.whatwg.org/#urlencoded-parsing it is stated, that only the first equal sign in a key value pair is used to split the pair.
> If bytes contains a 0x3D (=), then let name be the bytes from the start of bytes up to but excluding its first 0x3D (=), and let value be the bytes, if any, after the first 0x3D (=) up to the end of bytes.
This behaviour occurred to …

FormParam splitting

---

README.md

.travis.yml has been deleted but still, there were a few references present in README. 
Continuation of https://github.com/resteasy/Resteasy/pull/2836

Travis CI reference delete from README

---

providers/multipart/pom.xml
providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/HeaderFlushedOutputStream.java
providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaroundTest.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
resteasy-client/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43EngineTest.java

This change addresses issue [RESTEASY-2880](https://issues.redhat.com/browse/RESTEASY-2880) by allowing users to configure the in-memory limit of the server (default 1024 bytes) and the client (default 1MB) by setting the following config properties, respectively:
org.jboss.resteasy.plugins.providers.multipart.memoryThreshold=<newThresholdInBytes>
org.jboss.resteasy.client.jaxrs.engines.fileUploadInMemoryThreshold=<newThresholdInMegaBytes>

[RESTEASY-2880] Config options for in-memory limit

---

testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/AsynchronousCdiTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/TimerInterceptorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HeaderPropagator.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/webapplicationexception_web.xml

Backport #2691 to main branch
* [Jira with details - RESTEASY-2837](https://issues.redhat.com/browse/RESTEASY-2837)
* [3.15 MR](https://github.com/resteasy/Resteasy/pull/2691)
* The following commits can't be ported to main branch
* [this commit adds MicroProfileDependent annotation to a few classes, but main branch doesn't contains MicroProfileDependent annotation at all](https://github.com/resteasy/Resteasy/pull/2691/commits/4ee71640d422015ef236f34278a54c7843c56bf0)
* [This commit increase WF version for testing to WF23, but WF23 is already used in main branch](https://github.com/resteasy/Resteasy/pull/2691/commits/89a8dd9f8b261cc6a7d8e601771d176cab25987f)

Backport #2691 to main branch

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/FollowRedirectsTest.java

Adding the annotation to the test class.
https://issues.redhat.com/browse/RESTEASY-2971
This goes into the `3.15` branch only.

[RESTEASY-2971] FollowRedirectsTest should be annotated with MicroProfileDependent category

---

testsuite/integration-tests/pom.xml

Merging `includedPackages` elements in the bootable jar Maven config into one.
https://issues.redhat.com/browse/RESTEASY-2968
This goes into the `3.15` branch only.

[RESTEASY-2968] Fix rxjava2 related testing for bootable jar

---

resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ViolationReport.java

This issue was identified in a scenario that the exception' object is delegated to a task that works in other threads. As it uses the iterator on ResteasyViolationException#toString and it calls the convertViolations method (that modifies the violationLists) it can generate an issue if called concurrently.
JIRA: https://issues.redhat.com/browse/RESTEASY-2914
PR to 3.9: https://github.com/resteasy/Resteasy/pull/2806

Fixing the ResteasyViolationException#toString concurrency

---

pom.xml

https://issues.redhat.com/browse/RESTEASY-2994

[RESTEASY-2994] Do no use module directories for the generated JavaDoc's

---

testsuite/integration-tests/pom.xml

Adding the missing property to the bootable-jar surefire configuration.
https://issues.redhat.com/browse/RESTEASY-2970
This goes into the `3.15` branch only.

[RESTEASY-2970] SsePublisherClientTest fails with bootable-jar

---

server-adapters/resteasy-reactor-netty/pom.xml
server-adapters/resteasy-reactor-netty/src/main/java/org/jboss/resteasy/plugins/server/reactor/netty/ChunkOutputStream.java
server-adapters/resteasy-reactor-netty/src/main/java/org/jboss/resteasy/plugins/server/reactor/netty/ReactorNettyHttpResponse.java
server-adapters/resteasy-reactor-netty/src/main/java/org/jboss/resteasy/plugins/server/reactor/netty/ReactorNettySendException.java
server-adapters/resteasy-reactor-netty/src/main/java/org/jboss/resteasy/plugins/server/reactor/netty/i18n/Messages.java
server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/ChunkOutputStreamTest.java
server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/test/StreamingOutputTest.java

I cherry picked this change from the main branch as we need this change back ported to the last release version. 
Main [PR](https://github.com/resteasy/resteasy/pull/2882).

[RESTEASY-2996] Calling send for each chunk with flush and completing the future

---

pom.xml

https://issues.redhat.com/browse/RESTEASY-3041

[RESTEASY-3041] Upgrade the wildfly-maven-plugin to 2.1.0.Final.

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/test/StreamingOutputTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java

Combined fix as the first commit seems to trigger the others failing more. Combining them just seemed correct.
Upstream #2968

RESTEASY-3046 with other test fixes

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3068

[RESTEASY-3068] Upgrade Jetty to 11.0.7.

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java

RESTEasy includes its own parser of service loader files (in the
`RegisterBuiltin` class). That parser doesn't account for comments,
even though those are legal (see [1]). That makes for some interesting
error messages when using e.g. RESTEasy's support for MicroProfile
Context Propagation, because that file does use comments [2].
[1] https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html
[2] https://github.com/resteasy/resteasy-microprofile/blob/main/context-propagation/src/main/resources/META-INF/services/jakarta.ws.rs.ext.Providers

[RESTEASY-3073] Account for comments when parsing service loader files

---

pom.xml

In #3016 there was a bump to require Java 11. However, I missed the required compiler parameters to actually compile TO Java 11.

Actually compile to Java 11 instead of just requiring it.

---

resteasy-dependencies-bom/pom.xml
testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilSpring.java

According to Spring blog: https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement
We need to update Spring version to address vulnerability.

RESTEASY-3118 Upgrade Spring to 5.3.18

---

providers/json-binding/pom.xml
providers/json-p-ee7/pom.xml
resteasy-dependencies-bom/pom.xml
server-adapters/resteasy-vertx/pom.xml

Reverts resteasy/resteasy#3062
This breaks the TCK, so we need to revert it for now. We likely need the JSON Binding upgrade too. At this point we're waiting for an Eclipse Yasson release.

Revert "[RESTEASY-3101] Upgrade Jakarta JSON Processing to 2.1 and move to ne…"

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3105

[RESTEASY-3105] Upgrade Jakarta Annotations from 2.0.0 to 2.1.0.

---

server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/RequestDispatcher.java
server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxRequestHandler.java

To address RESTEASY-2326, I have simply made it possible to override the require methods so we can provide our own implementation of authentication for resteasy-vertx, by allowing injection of our own RequestDispatcher and allowing us to override the authenticate method of that class.
(this is a recreation of PR #2138 with target as main branch)
(I submit this PR under the terms of the ASL 2.0 License: http://www.apache.org/licenses/LICENSE-2.0 , and I accept those terms.)

RESTEASY-2326 Allow extending resteasy-vertx classes

---

docbook/reference/en/en-US/modules/Asynchronous_HTTP.xml
resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/GZIPEncodingInterceptor.java
resteasy-core/src/test/java/org/jboss/resteasy/plugins/interceptors/GZIPEncodingInterceptorTest.java

to allow it to be used in async backends like Netty.
Related to #3090 
I agree on the Apache License 2.0 terms.

[RESTEASY-3127] Make GZIPEncodingInterceptor implement AsyncWriterInterceptor

---

resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyBadRequestException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyClientErrorException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyForbiddenException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyInternalServerErrorException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAcceptableException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAllowedException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAuthorizedException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotFoundException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotSupportedException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyRedirectionException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServerErrorException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServiceUnavailableException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyWebApplicationException.java
resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/SanitizedResponseHolder.java
resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java

Hi guys,
This PR is my proposal to fix inconsistency spotted by this [JIRA](https://issues.redhat.com/browse/RESTEASY-3096).
As I said in the JIRA description, the way `WebApplicationException` thrown by client in a server side context are handled, using subtypes of  `org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper` to return a sanitized `jakarta.ws.rs.core.Response`  with no entity and only few important headers, looks fine to me and does not bother me.
But what bothers me more is, the insconsistency in the `WebApplicationException#getResponse()` method behavior:
- If  `WebApplicationException` is thrown by client in a server side context, then `WebApplicationException#getResponse()`  returns a sanitized reponse that does not match nor represents the remote side …

[Resteasy 3096]: Resteasy new WebApplicationExceptions behavior

---

.github/workflows/maven.yml

https://issues.redhat.com/browse/RESTEASY-3151

[RESTEASY-3151] Upgrade WildFly to 27.0.0.Alpha1 for CI runs.

---

resteasy-bom/pom.xml

Remove non-existing resteasy-reactive-context version constraint from the resteasy-bom.

Remove non-existing resteasy-reactive-context constraint

---

config/eclipse/resteasy-template.xml
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/AsyncWriterInterceptor.java
resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/AsyncWriterInterceptorContext.java
resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java

https://issues.redhat.com/browse/RESTEASY-3161
@NicoNes Hopefully you'll see this notification :) Is this okay with you? We would just like to change the license header from LGPL to ASLv2.

[RESTEASY-3161] Use the ASLv2 license.

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3167

[RESTEASY-3167] Upgrade Jetty from 11.0.7 to 11.0.11

---

resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java

Issue: https://issues.redhat.com/browse/RESTEASY-3155
Moving the method `convertViolations` to the constructor to avoid any race condition when calculating the lists (`convertFromString` is already called at constructor level). The lists are used now like if they were final.
I'm sending PRs for main and 3.15 branches. @jamezp If you need this any other branch just let me know.
This PR is for the main branch.
PR for 1.15: https://github.com/resteasy/resteasy/pull/3128

[RESTEASY-3155] Concurrency issues in ResteasyViolationException

---

providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataInputImpl.java
providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartRelatedInputImpl.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient43Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/FinalizedClientResponse.java
resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceCleaner.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientExecutorShutdownTest.java

https://issues.redhat.com/browse/RESTEASY-3135
This is not yet complete, but wanted to get some tests running.

[RESTEASY-3135] Initial change for removing finalizers.

---

testsuite/pom.xml

Remove the maven-help-plugin from the testsuite POM.

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3179

[RESTEASY-3179] Remove wiremock which is no longer used.

---

pom.xml
providers/resteasy-html/pom.xml

Remove an override of the maven-resource-plugin.
Upgrade Arquillian and WildFly Arquillian.
https://issues.redhat.com/browse/RESTEASY-3203

[RESTEASY-3203] Upgrade Arquillian to 1.7.0.Alpha12 and WildFly Arquillian to 5.0.0.Alpha5.

---

pom.xml
resteasy-bom/pom.xml

This adds the missing SCM info to the reasteasy-bom.

Add SCM info to the resteasy-bom

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DisabledDefaultExceptionMapperTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DisabledDefaultExceptionThrowableMapperMapperTest.java

https://issues.redhat.com/browse/RESTEASY-3225

[RESTEASY-3225] Minor follow-ups from review.

---

resteasy-dependencies-bom/pom.xml
resteasy-rxjava2/pom.xml

- [RESTEASY-3254](https://issues.redhat.com/browse/RESTEASY-3254) / the `commons-codec` versions are conflict in `resteasy-client`
- [RESTEASY-3255](https://issues.redhat.com/browse/RESTEASY-3255) / the `reactive-streams` versions are conflict in `resteasy-feature-pack-common`

RESTEASY-3254 / RESTEASY-3255

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyPathParamRegexTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ProxyPathParamRegexResource.java

https://issues.redhat.com/browse/RESTEASY-2845

[RESTEASY-2845] ResteasyWebTarget.proxy(Class) problem with questionmark in @Path with Regex

---

providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DataSourceProvider.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
server-adapters/resteasy-undertow/src/test/java/org/jboss/resteasy/test/undertow/AsyncIOResource.java
server-adapters/resteasy-undertow/src/test/java/org/jboss/resteasy/test/undertow/UndertowTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/XOPMultipartProxyTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyResource.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/RangeResource.java

https://issues.redhat.com/browse/RESTEASY-3286

[RESTEASY-3286] Use the new NIO file utilities to create temporary files

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/BaseHttpRequest.java

I have got `NPE` when call `logout` method in keycloak 20.0.3. It occurs when calling `BaseHttpRequest.getFormParameters` and `Content-Type` is not set.

RESTEASY-2831: Check mediatype before calling isCompatible

---

resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilderImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/RequestNamedQueryParameterTest.java

https://issues.redhat.com/browse/RESTEASY-3300
Replaces #3522

[RESTEASY-3300] Do not append single '&' with empty query parameters

---

resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
resteasy-client-vertx/src/test/java/org/jboss/resteasy/test/client/vertx/VertxClientEngineTest.java

This pr pulls in a subset of changes from https://github.com/resteasy/resteasy/pull/2890
The changes are
- Add query params to uri if they exist
- Dont add USER_AGENT header if one already exists
https://issues.redhat.com/browse/RESTEASY-3018

Add query params to reqest for VertxClientHttpEngine

---

resteasy-dependencies-bom/pom.xml
resteasy-wadl-undertow-connector/pom.xml
server-adapters/resteasy-undertow-cdi/pom.xml
server-adapters/resteasy-undertow-cdi/src/test/resources/logging.properties
server-adapters/resteasy-undertow/pom.xml

This is a major Servlet upgrade. In most cases this should be backwards compatible. However, Undertow no longer has a Jakarta EE 9.1 variant, [UNDERTOW-2167](https://issues.redhat.com/browse/UNDERTOW-2167). This forces a major Undertow and Servlet bump in 6.2. However, 6.2 supports Jakarta RESTful Web Services 3.1/Jakarta EE 10 so maybe not a huge issue.
https://issues.redhat.com/browse/RESTEASY-3323

[RESTEASY-3323] Upgrade Undertow to 2.3.4.Final and Servlet to 6.0

---

pom.xml
resteasy-dependencies-bom/pom.xml

* #3609
* #3611
* #3612
* #3613
* #3616

[6.2] Combined component upgrades 

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3348

[RESTEASY-3348] Upgrade bouncy castle to 1.75.

---

resteasy-dependencies-bom/pom.xml

- [Release notes](https://github.com/eclipse-ee4j/parsson/releases)
- [Commits](eclipse-ee4j/parsson@1.1.2...1.1.3)
https://issues.redhat.com/browse/RESTEASY-3354
Upstream #3706

[RESTEASY-3354] Upgrade Eclipse Parsson from 1.1.2 to 1.1.3.

---

docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java

https://issues.redhat.com/browse/RESTEASY-3324

[RESTEASY-3324] Enable redirects using property.

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/AbstractCollectionProcessor.java

(Not sure if it's necessary to create an issue for this small change so I just created a PR)
At the moment the `resteasy-client` doesn't retrieve `ParamConverter`s for objects different from Collection and array if the `ParamConverterProvider` requires the `genericType` or the `annotations`. This PR fixes the issue.
I haven't found any tests for the retrieval of `ParamConverter`s on client-side. If there are any could you just point me to them so that I can add a test case for this.

Fix client-side ParamConverter retrieval

---

pom.xml
resteasy-dependencies-bom/pom.xml

Includes:
- #3753
- #3757
- #3759
- #3760
- #3765

Component Upgrades

---

resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java

Issue: https://issues.redhat.com/browse/RESTEASY-2612

[RESTEASY-2612] Support CompletableFuture resource method return type

---

resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
resteasy-core/src/test/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegateTest.java

Previously, a "broken" MIME-type could trigger an StringIndexOutOfBoundsException instead of the more suitable IllegalArgumentException.
Example: "Accept: x; /x"
This PR now throws an IllegalArgumentException in case of a broken MIME-type.

[RESTEASY-3384] Improve parsing of malformed MediaTypes in MediaTypeHeaderDelegate

---

resteasy-client/pom.xml
resteasy-client/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43EngineTest.java
resteasy-client/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
resteasy-client/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
resteasy-client/src/test/java/org/jboss/resteasy/test/other/DisableAutomaticRetriesTest.java

https://issues.redhat.com/browse/RESTEASY-3389

[RESTEASY-3389] Migrate the resteasy-client tests to use JUnit 5.

---

providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/MultipartEntityPartProviderTest.java
resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientEngine.java
resteasy-client-jetty/src/test/java/org/jboss/resteasy/test/client/jetty/JettyClientEngineTest.java
resteasy-core/src/main/java/org/jboss/resteasy/core/FormParamInjector.java
resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
resteasy-core/src/test/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegateTest.java

- https://issues.redhat.com/browse/RESTEASY-3384
- https://issues.redhat.com/browse/RESTEASY-3390
- https://github.com/resteasy/resteasy/pull/3667

[6.2] Back ports

---

.github/workflows/cloud-tests.yml
pom.xml
testsuite/cloud-tests/client-tests/pom.xml
testsuite/cloud-tests/client-tests/src/main/java/dev/resteasy/cloud/tests/client/EchoResource.java
testsuite/cloud-tests/client-tests/src/main/java/dev/resteasy/cloud/tests/client/RestActivator.java
testsuite/cloud-tests/client-tests/src/test/java/dev/resteasy/cloud/tests/client/EchoIT.java
testsuite/cloud-tests/images/cloud-server/pom.xml
testsuite/cloud-tests/images/pom.xml
testsuite/cloud-tests/pom.xml
testsuite/pom.xml
testsuite/test-utils/pom.xml
testsuite/test-utils/src/main/java/dev/resteasy/cloud/tests/RestClientValueInjector.java
testsuite/test-utils/src/main/resources/META-INF/services/org.wildfly.test.cloud.common.ValueInjector

https://issues.redhat.com/browse/RESTEASY-3386
Upstream #3807

[RESTEASY-3386] Add cloud tests for Kubernetes.

---

resteasy-reactor/pom.xml
resteasy-reactor/src/test/java/org/jboss/resteasy/reactor/MonoProviderTest.java
resteasy-reactor/src/test/java/org/jboss/resteasy/reactor/ReactorTest.java
resteasy-reactor/src/test/java/org/jboss/resteasy/reactor/proxyframework/MonoWithProxyFrameworkApiTest.java

https://issues.redhat.com/browse/RESTEASY-3414

[RESTEASY-3414] Migrate the resteasy-reactor module to JUnit 5

---

resteasy-wadl-undertow-connector/pom.xml
resteasy-wadl-undertow-connector/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLTestExistenceVerifier.java
resteasy-wadl-undertow-connector/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLUndertowContainerTest.java

https://issues.redhat.com/browse/RESTEASY-3418

[RESTEASY-3418] Migrate the resteasy-wadl-undertow-connector module to JUnit 5

---

security/jose-jwt/pom.xml
security/jose-jwt/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
security/jose-jwt/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java

https://issues.redhat.com/browse/RESTEASY-3419

[RESTEASY-3419] Migrate the resteasy-security-josejwt module to JUnit 5

---

security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/DerUtils.java
security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/DerUtils.java

https://issues.redhat.com/browse/RESTEASY-3464
Upstream #4064

[RESTEASY-3464] Deprecate the DerUtils.decodePrivateKey methods.

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3494
Upstream #4148

[RESTEASY-3494] Upgrade BouncyCastle to 1.78.1.

---

resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
resteasy-dependencies-bom/pom.xml
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/RESTEASY3109Test.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseCallbackTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseCallbackResource.java

- https://issues.redhat.com/browse/RESTEASY-2952
- https://issues.redhat.com/browse/RESTEASY-3498
----
~~This is currently a draft because RESTEASY-3498 needs some regression tests.~~

[RESTEASY-2952 & RESTEASY-3498] Clean up the SSE callback processing

---

.github/workflows/wildfly-build.yml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/DisabledProvidersTest.java

…RESTEasy which doesn't support the configuration.
Upstream #4171

Disable the DisabledProvidersTest when provisioned with a version of … 

---

pom.xml
testsuite/arquillian-utils/pom.xml
testsuite/config/configure-bootable-jar.cli
testsuite/integration-tests/pom.xml
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorErrorTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/CryptoTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/DynamicFeatureTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingDebugLoggingTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/mediatype/BlacklistedMediaTypeTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
testsuite/integration-tests/src/test/resources/arquillian-bootable.xml
testsuite/pom.xml

This PR:
-  reintroduces bootable jar tests
- adds option to run bootable jar tests with a channel manifest

Test BootableJar using Channel Manifest

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3529
Replaces #4227

[RESTEASY-3529] Upgrade JBoss Logging Tools to 3.0.1.Final

---

testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/Student.java
testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentJsonMergePatchTest.java

Mainly negative test cases, see test documentation for details.
See https://issues.redhat.com/browse/RESTEASY-2567

[RESTEASY-2567] Added new test coverage for JSON merge patch

---

server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpResponse.java
server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpRequestDecoder.java
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/ResteasySmugglingRequestTest.java

When the **Netty** `HttpObjectDecoder` transitioned into a `BAD_MESSAGE` state, any subsequent requests on the same connection were ignored.
This PR fixes that behavior by sending a `connection: close` response header, so the client closes the connection.
Discussion: #4351
Jira ticket: [RESTEASY-3553](https://issues.redhat.com/browse/RESTEASY-3553)

[RESTEASY-3553] Send connection close header when Netty http decoder fails

---

server-adapters/resteasy-undertow-cdi/src/main/java/dev/resteasy/embedded/server/UndertowBuilderConfigurator.java
server-adapters/resteasy-undertow-cdi/src/main/java/dev/resteasy/embedded/server/UndertowCdiEmbeddedServer.java

This implements a simple ServiceLoader interface, which can be used by applications, which need to update the Undertow.Builder before it is built/started (such as, to add http2 support to a non-TLS server).

[RESTEASY-3583] Add a ServiceLoader dev.resteasy.embedded.server.UndertowBuilderConfigurer to update the Undertow.Builder

---

resteasy-dependencies-bom/pom.xml

https://issues.redhat.com/browse/RESTEASY-3610

[RESTEASY-3610] Upgrade Netty to 4.1.123.Final.

---

resteasy-dependencies-bom/pom.xml
server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/NettyTest.java
server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/test/NettyTest.java
server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/VertxTest.java

https://issues.redhat.com/browse/RESTEASY-3623
Upstream: #4659 
Replaces #4657

[RESTEASY-3623] Upgrade Netty to 4.1.126.Final.

---

testsuite/integration-tests/pom.xml

*** back-port of https://github.com/resteasy/resteasy/pull/4651 to branch 6.2 ***
In other CI environments other than Github, we need to be able to exclude additional tests without overriding existing excludes;

[6.2] Exclude additional tests in resteasy-integration-tests

---

resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java

Sending multipart/form-data with MicorProfileRestClient asynchronous results in exception. The same Request works synchronous as expected. During analysis it was found that the data is not coming as a GenericEntity to the available MessageBodyWriters in async flow, thus resulting in an incorrect MBW being picked up, which results in an exception. Further analysis led to the ClientInvoker.invokeAsync() method where this data is set to entity. Here entity is set in raw format and thus going as a immutable list to the downstream. So a code fix is required to cast the data to GenericEntity if it's not originally.

Updated code to cast to GenericEntity
