resteasy/resteasy

- jaxrs/docbook/reference/en/en-US/master.xml
- jaxrs/docbook/reference/en/en-US/modules/Atom.xml
- jaxrs/docbook/reference/en/en-US/modules/Content_Marshalling_Providers.xml
- jaxrs/docbook/reference/en/en-US/modules/Installation_Configuration.xml
- jaxrs/docbook/reference/en/en-US/modules/JAX-RS_Content_Negotiation.xml
- jaxrs/docbook/reference/en/en-US/modules/JAX-RS_Resource_Locators_and_Sub_Resources.xml
- jaxrs/docbook/reference/en/en-US/modules/Jaxb.xml
- jaxrs/docbook/reference/en/en-US/modules/Json-p.xml
- jaxrs/docbook/reference/en/en-US/modules/Json.xml
- jaxrs/docbook/reference/en/en-US/modules/Links.xml
- jaxrs/docbook/reference/en/en-US/modules/Migration_from_older_versions.xml
- jaxrs/docbook/reference/en/en-US/modules/Multipart.xml
- jaxrs/docbook/reference/en/en-US/modules/Using_Path.xml
- jaxrs/docbook/reference/en/en-US/modules/_CookieParam.xml
- jaxrs/docbook/reference/en/en-US/modules/_DefaultValue.xml
- jaxrs/docbook/reference/en/en-US/modules/_Encoded_and_encoding.xml
- jaxrs/docbook/reference/en/en-US/modules/_Form.xml
- jaxrs/docbook/reference/en/en-US/modules/_HeaderParam.xml
- jaxrs/docbook/reference/en/en-US/modules/_MatrixParam.xml
- jaxrs/docbook/reference/en/en-US/modules/_PathParam.xml
- jaxrs/docbook/reference/en/en-US/modules/_QueryParam.xml
- Removed unnecessary empty lines from some code snippets.
- Changed the indentation of some code snippets from 3 spaces to 4 spaces, which seems to be the standard.
- Fixed a few typos.
> Tidy up documentation (chapters 1-23)

- jaxrs/resteasy-jsapi/src/main/java/org/jboss/resteasy/jsapi/JSAPIServlet.java
JS sources must have MediaType application/javascript --> set the correct type
additionally remove unused imports
> this PR fixes RESTEASY-1150 

- jaxrs/resteasy-spring/src/main/java/org/jboss/resteasy/plugins/spring/SpringContextLoaderListener.java
Added missing inherited constructors to enable no-xml configuration through AnnotationConfigWebApplicationContext.
> Add inherited constructors: ContextLoaderListener

- jaxrs/resteasy-spring/src/main/java/org/jboss/resteasy/plugins/spring/SpringContextLoaderListener.java
> Revert "Add inherited constructors: ContextLoaderListener"

- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/MapCache.java
added wildcard support for the client cache, otherwise when client accepts */*, the entry would not be found in the cache
> added wildcard support for the client cache

- jaxrs/async-http-servlet-3.0/pom.xml
- jaxrs/providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/SecureUnmarshaller.java
- jaxrs/providers/jaxb/src/test/java/org/jboss/resteasy/test/nextgen/xxe/namespace/TestNamespace.java
- jaxrs/providers/jaxb/src/test/java/org/jboss/resteasy/test/xxe/TestSecureProcessingFeature.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/DocumentProvider.java
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/providers/iioimage/TestIIOImageProvider.java
- pom.xml
@ronsigal Could you please help to review whether this fix is reasonable? Thanks!
> RESTEASY-1207

- jaxrs/resteasy-jaxrs-testsuite/pom.xml
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/AsyncTimeoutExceptionsTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/client/IndirectInvocationTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/client/ClientExceptionsTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/client/ClientProviderTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/client/WebTargetTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/client/WebTargetUnitTest.java
RESTEASY-1210 - Added tests for resteasy-jaxrs-testsuite - Webtarget, Invocation, Client Exceptions, Async timeout exceptions.
> RESTEASY-1210 - Resteasy-client tests

- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/xxe/TestXXE.java
> RESTEASY-1216: Looks like a timing problem: adding one second before

- jaxrs/security/keystone/keystone-core/src/main/java/org/jboss/resteasy/keystone/server/SkeletonKeyApplication.java
- jaxrs/security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/doseta/DosetaKeyRepository.java
- jaxrs/security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/doseta/KeyStoreKeyRepository.java
RESTEasy don't close resources everywhere, it could cause performance drop during garbage collecting.
> RESTEASY-1247 - RESTEasy do not close resources everywhere

- jaxrs/resteasy-spring/src/main/java/org/jboss/resteasy/plugins/spring/SpringBeanProcessor.java
this PR is slightly cleaner version of #686, please merge this ASAP as it blocks using of main integration method of RESTEasy into Spring via @ImportResource("classpath:springmvc-resteasy.xml")
> [RESTEASY-810] fix erroneous 'java.lang.IllegalStateException: RESTEASY013015 <...>'

- jaxrs/server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
Exposed  maxInitialLineLength, maxHeaderSize and maxChunkSize
> RESTEASY-1243 Exposed HttpDecoders settings

- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlServletWriter.java
* response in ResteasyWadlServletWriter.writeWadl was already written after the first entry was processed from the serviceRegistries
> RESTEASY-166 bugfix - support multiple application classes

- jaxrs/resteasy-jaxrs-testsuite/pom.xml
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/properties/GetPropertiesTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
[RESTEASY-1172] : https://issues.jboss.org/browse/RESTEASY-1172
> [RESTEASY-1172] : Properties from javax.ws.rs.core.Application.getProperties are not registered

- jboss-modules/lib.xml
[RESTEASY-1191] : https://issues.jboss.org/browse/RESTEASY-1191 (adding the PR for 2_3)
[Upstream] : https://github.com/resteasy/Resteasy/pull/650
> [RESTEASY-1191] : Backport JBEAP-246 to 2_3

- jaxrs/resteasy-jaxrs-testsuite/pom.xml
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/BasicTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestAllResources.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestNettyContainer.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/resources/BasicResource.java
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlDefaultResource.java
- jaxrs/server-adapters/resteasy-netty4-cdi/src/test/java/org/jboss/resteasy/plugins/server/netty/cdi/CdiNettyTest.java
- jaxrs/server-adapters/resteasy-netty4/pom.xml
- jaxrs/server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/JaxrsAsyncTest.java
- jaxrs/server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/resteasy_jaxrs/i18n/TestMessagesParent.java
- add netty container tests
- bug fixes
- more tests
> add netty container tests

- jaxrs/pom.xml
[RESTEASY-1263] :  https://issues.jboss.org/projects/RESTEASY/issues/RESTEASY-1263
> [RESTEASY-1263] : Upgrade Guice to 4.0.

- jaxrs/resteasy-wadl/pom.xml
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlMethodMetaData.java
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlServiceRegistry.java
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlServlet.java
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlServletWriter.java
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlWriter.java
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/i18n/LogMessages.java
- jaxrs/resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/i18n/Messages.java
- jaxrs/resteasy-wadl/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
- jaxrs/resteasy-wadl/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
- jaxrs/resteasy-wadl/src/test/java/org/jboss/resteasy/test/i18n/TestMessages_en.java
- jaxrs/resteasy-wadl/src/test/java/org/jboss/resteasy/test/i18n/TestMessages_xx.java
- jaxrs/resteasy-wadl/src/test/resources/i18n/Messages.i18n_en.properties
- jaxrs/resteasy-wadl/src/test/resources/i18n/Messages.i18n_xx.properties
> RESTEASY-1276

- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/security/BasicAuthTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/RoleBasedSecurityFilter.java
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
Role based authorization failure returns status 403 and a brief message.
> RESTEASY-1249

- jaxrs/providers/resteasy-hibernatevalidator-provider/src/test/java/org/jboss/resteasy/test/plugins/validation/smoke/TestBeanValidationIntegrationSmoke.java
Added Assert.fail() to four test methods, added @Ignore to shouldRespectInsertGroup().
> RESTEASY-1165

- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/resource/ClientErrorBadMediaTypeTest.java
JIRA: https://issues.jboss.org/browse/RESTEASY-1280
JBEAP: https://issues.jboss.org/browse/JBEAP-2594
> [RESTEASY-1280, JBEAP-2594] ClientErrorBadMediaTypeTest shouldn't ignore configuration errors

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/InternalDispatcher.java
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/InternalDispatcherTest.java
JIRA: https://issues.jboss.org/browse/RESTEASY-1272
JBEAP: https://issues.jboss.org/browse/JBEAP-2476
> [RESTEASY-1272, JBEAP-2476] InternalDispatcher forwards requests with wrong UriInfo on EAP

- jaxrs/arquillian/RESTEASY-TEST-WF10/src/main/java/org/jboss/resteasy/resteasy1296/HikeResource.java
- jaxrs/arquillian/RESTEASY-TEST-WF10/src/main/java/org/jboss/resteasy/resteasy1296/HikingApplication.java
- jaxrs/arquillian/RESTEASY-TEST-WF10/src/test/java/org/jboss/resteasy/test/resteasy1296/ValidationThroughRestIT.java
- jaxrs/arquillian/pom.xml
- jaxrs/providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
- jaxrs/providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- jaxrs/providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/SimpleViolationsContainer.java
Changed treatment of Weld proxies in GeneralValidatorImpl in resteasy-validator-provider-11.
> RESTEASY-1296

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/dynamic/ClientDynamicFeaturesTest.java
Fixed dynamic feature storage in ResteasyProviderFactory.
> RESTEASY-1083

- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/producers/ProducesMediaTest.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/producers/TestDefaultNumberWriter.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/DefaultNumberWriter.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
- jaxrs/resteasy-jaxrs/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/finegrain/MediaTypeMapTest.java
Adding DefaultNumberWriter provider.
> RESTEASY-1282

- jaxrs/arquillian/RESTEASY-TEST-WF8/src/test/java/org/jboss/resteasy/test/resteasy1103/TestExceptionMapper.java
- jaxrs/arquillian/RESTEASY-TEST-WF8/src/test/java/org/jboss/resteasy/test/resteasy1103/TestSecureProcessing.java
- jaxrs/arquillian/RESTEASY-TEST-WF8/src/test/resources/1103/META-INF/services/javax.ws.rs.ext.Providers
- jaxrs/providers/jaxb/src/test/java/org/jboss/resteasy/test/xxe/TestSecureProcessingFeature.java
- jaxrs/providers/jaxb/src/test/java/org/jboss/resteasy/test/xxe/TestXXE.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/xxe/TestSecureProcessing.java
Added warning message when multiple resource methods match request.
> RESTEASY-1300

- jaxrs/as7-integration-testing/cdi-test/pom.xml
- jaxrs/as7-integration-testing/modules-test/src/main/java/org/jboss/resteasy/tests/NewFeaturesResource.java
- jaxrs/as8-integration-testing/application-test/pom.xml
- jaxrs/as8-integration-testing/cdilocator-test/pom.xml
- jaxrs/as8-integration-testing/ejb-singleton-test/pom.xml
- jaxrs/pom.xml
- jaxrs/providers/resteasy-hibernatevalidator-provider/pom.xml
- jaxrs/providers/resteasy-validator-provider-11/pom.xml
Upgraded javax.enterprise:cdi-api to 1.2.
> RESTEASY-1307

- jaxrs/pom.xml
- jaxrs/providers/multipart/pom.xml
Also upgraded JavaMail to latest 1.5.5.
> Removed duplicate JavaMail dependency

- jaxrs/resteasy-jaxrs-testsuite/pom.xml
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/producers/MissingProducerTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
Print file origin of missing providers in RegisterBuiltin.
> RESTEASY-1134

- jaxrs/resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/HeaderHolder.java
- jaxrs/resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/InfinispanCache.java
- jaxrs/resteasy-cache/resteasy-cache-core/src/test/java/org/jboss/resteasy/test/cache/PersistentServerCacheTest.java
- jaxrs/resteasy-cache/resteasy-cache-core/src/test/resources/infinispan.xml
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/providers/datasource/RESTEASY779Test.java
Made org.jboss.resteasy.plugins.cache.server.InfinispanCache$CacheEntry
serializable.
> RESTEASY-1175

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
Stacktrace for NotFoundException logged at DEBUG level.
> RESTEASY-1319

- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientProxy.java
- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ResteasyClientProxy.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/proxy/TestProxyCasting.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/proxy/TestProxyCastingSimple.java
Restored as() method to proxies, as in Resteasy 2.x.
> RESTEASY-1332

- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
- jaxrs/resteasy-client/src/test/java/org/jboss/resteasy/test/internal/proxy/ClientWebTargetTest.java
JIRA: https://issues.jboss.org/browse/RESTEASY-1306
> [RESTEASY-1306] - Cannot remove property from ClientWebTarget

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Types.java
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/test/util/WildcardTypeTest.java
Types.getRawType() can process WildcardType.
> RESTEASY-1295

- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/extractors/BodyEntityExtractor.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/client/GenericReturnTypeTest.java
BodyEntityExtractor checks that generic return type is not a type
variable.
> RESTEASY-1250

- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/providers/DuplicateProviderRegistrationTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Additional checks in ResteasyProviderFactory for duplicate registrations.
> RESTEASY-1284

- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/finegrain/CookieNullValueTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/delegates/NewCookieHeaderDelegate.java
Guard against NPE in NewCookieHeaderDelegate.
> RESTEASY-1328

- jaxrs/docbook/reference/en/en-US/modules/Content_Marshalling_Providers.xml
- jaxrs/docbook/reference/en/en-US/modules/ExceptionMappers.xml
- jaxrs/docbook/reference/en/en-US/modules/Json.xml
- jaxrs/docbook/reference/en/en-US/modules/_Context.xml
Fixed formatting in ExceptionMappers, Content_Marshalling_Providers, Json, and _Context sections.
https://issues.jboss.org/browse/RESTEASY-686, https://issues.jboss.org/browse/RESTEASY-770
> RESTEASY-686, RESTEASY-770

- jaxrs/server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/RESTEASY1323Test.java
- jaxrs/server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/RESTEASY1325Test.java
Extended timeouts to fix travis problems.
> RESTEASY-1323 / RESTEASY-1325

- jaxrs/security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/doseta/ServerDigitalVerificationHeaderDecoratorFeature.java
- jaxrs/security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/nextgen/security/doseta/VerifyAnnotationNoEntityTest.java
Do verification in
ServerDigitalVerificationHeaderDecoratorFeature$DigitalVerificationHeaderDecorator
if there is no entity parameter.
> RESTEASY-1169

- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/finegrain/TrailingSlashTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyUriInfo.java
Don't remove trailing '/' from path in ResteasyUriInfo.
> RESTEASY-1124

- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/LocalResteasyProviderFactory.java
- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/client/ConfigurationInheritenceTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Added a subclass of ResteasyProviderFactory which doesn't reference its
parent after it is created.
https://issues.jboss.org/browse/RESTEASY-1345
> RESTEASY-1345

- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/providers/FormUrlEncodedCharsetTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/FormUrlEncodedProvider.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/BaseHttpRequest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletInputMessage.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Encode.java
FormUrlEncodedProvider processes charsets.
https://issues.jboss.org/browse/RESTEASY-477
> RESTEASY-477

- jaxrs/resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/finegrain/DuplicateDeploymentTest.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
Duplicates in Application give log warning.
https://issues.jboss.org/browse/RESTEASY-841
> RESTEASY-841

- jaxrs/docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
- jaxrs/jboss-modules/build-wf8.xml
- jaxrs/jboss-modules/lib.xml
- jaxrs/jboss-modules/pom.xml
- jaxrs/jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-spring/main/module.xml
Added resteasy-spring to resteasy-jboss-modules-wf8-<version>.zip.
> RESTEASY-1354

- jaxrs/docbook/reference/en/en-US/modules/Asynchronous_HTTP.xml
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/annotations/Suspend.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SuspendInjector.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/AsynchronousResponse.java
Deprecate old Resteasy asynchronous API.
https://issues.jboss.org/browse/RESTEASY-1362
> [RESTEASY-1362]

- jaxrs/resteasy-links/src/main/java/org/jboss/resteasy/links/RESTServiceDiscovery.java
- jaxrs/resteasy-links/src/main/java/org/jboss/resteasy/links/i18n/Messages.java
- jaxrs/resteasy-links/src/main/java/org/jboss/resteasy/links/impl/RESTUtils.java
- jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStore.java
- jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStoreMinimal.java
- jaxrs/resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestFacadeLinks.java
I wanted RESTEASY-833 to be fixed, so I just implemented the suggestion and added a unit test.
https://issues.jboss.org/browse/RESTEASY-833
> RESTEASY-833: Preserve manually added AtomLinks

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilder.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Encode.java
- jaxrs/resteasy-jaxrs/src/test/java/org/jboss/resteasy/specimpl/ResteasyUriBuilderTest.java
This is a fixed PR on top of https://github.com/resteasy/Resteasy/pull/791 to avoid TCK regressions.
> [RESTEASY-1197] Performance Issue: org.jboss.resteasy.spi.ResteasyUriInfo instantiation takes 20% of all the CPU time

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
- resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlDefaultResource.java
- resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/i18n/Messages.java
- security/skeleton-key-idm/skeleton-key-core/src/main/java/org/jboss/resteasy/skeleton/key/AbstractOAuthClient.java
- server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RequestHandler.java
- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/RequestHandler.java
- tjws/src/main/java/Acme/Serve/SSLAcceptor.java
- tjws/src/main/java/Acme/Serve/Serve.java
This supersedes https://github.com/resteasy/Resteasy/pull/812
> [RESTEASY-1356] 

- jaxrs/docbook/reference/en/en-US/modules/Validation.xml
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationExceptionMapper.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/api/validation/ViolationReport.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/AbstractValidatorContextResolver.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/ConstraintTypeUtil10.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/DoNotValidateRequest.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/GeneralValidatorImpl.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/ValidateRequest.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/ValidatorContextResolver.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/ValidatorContextResolverCDI.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/i18n/LogMessages.java
- jaxrs/providers/resteasy-hibernatevalidator-provider/src/main/java/org/jboss/resteasy/plugins/validation/hibernate/i18n/Messages.java
Deprecated resteasy-hibernatevalidator-provider.
> [RESTEASY-1411]

- docbook/reference/en/en-US/modules/jwt.xml
> Typo in the documentation

- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestAllWADLResources.java
- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestBase.java
- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestNettyContainer.java
- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/nextgen/wadl/resources/issues/RESTEASY1246.java
- resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlMethodMetaData.java
- resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlWriter.java
[RESTEASY-1246] Multiple Produces should be dealt with correctly
> [RESTEASY-1246] Multiple Produces should be dealt with correctly

- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/finegrain/MultipleEndpointsWarningTest.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
https://issues.jboss.org/browse/RESTEASY-1398 - warning message logged when it shouldn't be
https://issues.jboss.org/browse/RESTEASY-1369 - adding more details to log message
> [RESTEASY-1398, RESTEASY-1369] false "multiple matching endpoints" logged

- arquillian/RESTEASY-TEST-WF10/src/main/java/org/jboss/resteasy/resteasy1365/HeadContentLengthApplication.java
- arquillian/RESTEASY-TEST-WF10/src/main/java/org/jboss/resteasy/resteasy1365/SimpleResource.java
- arquillian/RESTEASY-TEST-WF10/src/test/java/org/jboss/resteasy/test/resteasy1365/HeadContentLengthTest.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpResponse.java
- server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpRequestDecoder.java
- server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpResponseEncoder.java
- server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/NettyTest.java
https://issues.jboss.org/browse/RESTEASY-1365
> RESTEASY-1365 HEAD should return the same content length as GET

- server-adapters/resteasy-jdk-http/src/main/java/org/jboss/resteasy/plugins/server/sun/http/SunHttpJaxrsServer.java
- server-adapters/resteasy-jdk-http/src/test/java/org/jboss/resteasy/test/PortAssigningTest.java
- server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
- server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/PortAssigningTest.java
- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
- server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/PortAssigningTest.java
https://issues.jboss.org/browse/RESTEASY-1429
> RESTEASY-1429 Pick random port when port=0

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/ComprehensiveJaxrsTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/resource/SigningResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/atom/resource/LinkProduct.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/datasource/ReadDataSourceTwiceCountTempFileTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/Jackson2Product.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/Jackson2Resource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/JsonFilterWriteInterceptor.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectFilterModifier.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectWriterModifierFilter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/XmlJAXBContextFinderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlPojoBindingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/jackson2/jsonfilter/web.xml
- testsuite/unit-tests/pom.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ResponseBuilderImplTest.java
* Add documentation annotations for various tests
* Check that tests expected to fail have appropriate jira assigned
* Add profile to unit-tests submodule to allow to run unit tests with different resteasy version than the current project version
> [RESTEASY-1450] Testsuite - annotations, review failing tests, configurable resteasy version for unit tests

- providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/ValidationWithCDITest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/AbstractAsyncRootResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/AsyncRootResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/AsyncRootResourceImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/AsyncSubResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/AsyncSubResourceImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/AsyncValidResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/QueryBeanParam.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/QueryBeanParamImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/RootResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/RootResourceImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/SubResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/SubResourceImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/TestApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/resource/ValidResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/cdi/validation/web.xml
Updated GeneralValidatorImpl.validateAllParameters() to test for non
root resources.
> [RESTEASY-1186]

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/PortProvider.java
- jaxrs/resteasy-spring/src/main/java/org/jboss/resteasy/plugins/spring/EmbeddedContainerBean.java
- jaxrs/server-adapters/resteasy-jdk-http/src/main/java/org/jboss/resteasy/plugins/server/sun/http/HttpServerContainer.java
- jaxrs/server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyContainer.java
- jaxrs/server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyContainer.java
- jaxrs/server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/test/NettyContainer.java
- jaxrs/server-adapters/resteasy-undertow/src/main/java/org/jboss/resteasy/plugins/server/undertow/UndertowJaxrsServer.java
Merging deprecation changes back to 3.0.x so that we can remove deprecated classes on master
> [RESTEASY-1460] Refactoring

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
Fix wording in the upgrade docs
> minor doc tweak

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartWriter.java
- testsuite/unit-tests/pom.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/MultipurtContainsJsonTest.java
add a unit test to produce the RESTEASY-1201 and fix RESTEASY-1201
> [RESTEASY-1201]block close in part writer

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/InterceptorStreamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/InterceptorStreamCustom.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/InterceptorStreamResource.java
Prepare new test for change streams in interceptors
* There are currently no tests for interceptors, where interceptor change streams
> [RESTEASY-1487] New test for change streams in interceptors

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientProxy.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ProxyEqualsTest.java
Fixed treatment of equality in client proxy.
> [RESTEASY-1196]

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilder.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientRequestHeaders.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/FilteredCookieTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/FilteredCookieContainerRequestFilter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/FilteredCookieResource.java
Allow cookies to be added to ResteasyHttpHeaders.
> [RESTEASY-1266]

- docbook/reference/en/en-US/modules/Async_job_service.xml
- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsynchronousDispatcher.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchCounterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsynchCounterResource.java
Use SecureRandom in AsynchronousDispatcher to generate job ids.
> [RESTEASY-1483]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/encoding/GZIPEncodingInterceptor.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/CommitHeaderOutputStream.java
CommitHeaderOutputStream.commit() is synchronized.
> [RESTEASY-1242]

- docbook/reference/en/en-US/modules/Json.xml
- providers/jackson/src/main/java/org/jboss/resteasy/annotations/providers/NoJackson.java
- providers/jackson/src/main/java/org/jboss/resteasy/plugins/providers/jackson/JacksonJsonpInterceptor.java
- providers/jackson/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJacksonProvider.java
Deprecate resteasy-jackson-provider.
> [RESTEASY-1513]

- arquillian/RESTEASY-1056-jetty-bv11/pom.xml
- arquillian/RESTEASY-1056-jetty-bv11/src/test/java/org/jboss/resteasy/test/resteasy1056/MissingCDITest.java
- arquillian/RESTEASY-736-jetty/pom.xml
- arquillian/RESTEASY-736-jetty/src/test/java/org/jboss/resteasy/test/resteasy736/AsyncTimeoutTest.java
- pom.xml
- resteasy-cdi/pom.xml
- resteasy-links/pom.xml
- resteasy-spring/pom.xml
- resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/JettyLifecycleManager.java
- testsuite/integration-tests/pom.xml
only bit problematic part is resteasy-spring update to jetty 9.
that is why I put it in separate commit.
> Update dependancies and build

- arquillian/RESTEASY-1056-jetty-bv11/src/test/resources/arquillian.xml
- arquillian/RESTEASY-736-jetty/src/test/resources/arquillian.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/LazyInitUriInfoInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncInvokeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncTimeoutExceptionsTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientExceptionsTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientExecutorShutdownTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientFormParamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientInvocationBuilderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseRedirectTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientTestBase.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/EntityBufferingInFileTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/GenericReturnTypeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/IndirectInvocationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/InputStreamResourceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/InputStreamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/LinkHeaderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/NullEntityTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ParameterListTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/PrimitiveTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/SmokeParamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/SyncInvokeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/TimeoutTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/TraceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/WebTargetTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/datasource/ReadDataSourceTwiceCountTempFileTest.java
- testsuite/integration-tests/src/test/resources/arquillian.xml
- testsuite/pom.xml
It is not perfect yet, but it runs better with this fixes applied.
> fix tests to pass on windows as well

- jboss-modules/build.xml
- jboss-modules/pom.xml
- jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-p-provider/main/module.xml
Adding resteasy-json-p-provider.
> [RESTEASY-1512]

- resteasy-guice/src/main/java/org/jboss/resteasy/plugins/guice/ext/RequestScopeModule.java
- resteasy-guice/src/test/java/org/jboss/resteasy/plugins/guice/ext/RequestScopeModuleTest.java
Fix infinite loop in RequestScopeModule.
> [RESTEASY-1428]

- providers/json-p-ee7/src/main/java/org/jboss/resteasy/plugins/providers/jsonp/AbstractJsonpProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonp/JsonpTest.java
AbstractJsonpProvider lets jsonp determine charset if none is specified.
> [RESTEASY-1482]

- resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/InfinispanCache.java
- resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCache.java
- resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheHitFilter.java
- resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheInterceptor.java
- resteasy-cache/resteasy-cache-core/src/test/java/org/jboss/resteasy/test/cache/PersistentServerCacheTest.java
- resteasy-cache/resteasy-cache-core/src/test/java/org/jboss/resteasy/test/cache/ServerCacheTest.java
Reverts resteasy/Resteasy#978
SimpleServerCache$CacheEntry doesn't completely implement ServerCache$Entry: it's missing MultivaluedMap<String, String> getVaryHeaders();
> Revert "RESTEASY-1539: Respect Vary headers"

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/HttponlyCookieTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/HttponlyCookieResource.java
Tests for previous fix in RESTEASY-1476.
> [RESTEASY-1472]

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AbortedResponse.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AbortMessageTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/AbortMessageResourceFilter.java
Handle entity in AbortedResponse generated by a client called from a
resource on the server.
> [RESTEASY-1540]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Updated exception message in ResteasyProviderFactory.getRuntimeDelegate().
> RESTEASY-1531

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Forgot to use Messages in ResteasyProviderFactory.getRuntimeDelegate().
> [RESTEASY-1531]

- resteasy-guice/src/main/java/org/jboss/resteasy/plugins/guice/ext/RequestScopeModule.java
- resteasy-guice/src/test/java/org/jboss/resteasy/plugins/guice/ext/RequestScopeModuleTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/other/ApacheHttpClient43Test.java
[RESTEASY-1285] added test for pre-existing fix
> [RESTEASY-1285]

- providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/JsonCollectionProvider.java
- providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/JsonMapProvider.java
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartWriter.java
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ThreadLocalResteasyProviderFactory.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractReaderInterceptorContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractWriterInterceptorContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ClientWriterInterceptorContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
[RESTEASY-1558] : https://issues.jboss.org/browse/RESTEASY-1558
> [RESTEASY-1558]: Logging debug info for MessageBodyWriters and MessageBodyReaders.

- docbook/reference/en/en-US/master.xml
- docbook/reference/en/en-US/modules/Migration_from_older_versions.xml
- docbook/reference/en/en-US/modules/Migration_to_3.1.xml
- docbook/reference/en/en-US/modules/gzip.xml
- resteasy-upgrade-guide/reference/en/en-US/master.xml
Added documentation for upgrading to Resteasy 3.1.
> [RESTEASY-1541]

- providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ApplicationScopeValidationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/ApplicationScopeIRestServiceAppScoped.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/ApplicationScopeIRestServiceReqScoped.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/ApplicationScopeMyDto.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/ApplicationScopeRestServiceAppScoped.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/ApplicationScopeRestServiceReqScoped.java
Fixed validation edge case with application scoped resource and invalid
parameters.
> [RESTEASY-1459]

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- docbook/reference/en/en-US/modules/Migration_from_older_versions.xml
Updated "Migration from older versions" chapter of User Guide.
> [RESTEASY-1506]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractReaderInterceptorContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractWriterInterceptorContext.java
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/LogCounter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingCustomReaderAndWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingEndPoint.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingReaderInterceptorCustom.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/resource/DebugLoggingWriterInterceptorCustom.java
https://issues.jboss.org/browse/RESTEASY-1562
* Clarify debug messages with used interceptors
* Prepare tests for provider's and interceptor's debug messages.
* https://issues.jboss.org/browse/RESTEASY-1415
* https://issues.jboss.org/browse/RESTEASY-1558
* https://github.com/resteasy/Resteasy/pull/954
* https://github.com/resteasy/Resteasy/pull/1008
> Prepare tests for provider's and interceptor's debug messages

- pom.xml
- providers/pom.xml
- security/pom.xml
[RESTEASY-1567] : https://issues.jboss.org/browse/RESTEASY-1567
> [RESTEASY-1567] : Remove redhat-prod profile.

- jaxrs/providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/JsonCollectionProvider.java
- jaxrs/providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/JsonMapProvider.java
- jaxrs/providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartWriter.java
- jaxrs/providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
- jaxrs/resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ThreadLocalResteasyProviderFactory.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/AbstractReaderInterceptorContext.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/AbstractWriterInterceptorContext.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
[Resteasy 1560] : https://issues.jboss.org/browse/RESTEASY-1560
[Upstream] : https://github.com/resteasy/Resteasy/pull/1008
> [RESTEASY-1560] : Logging debug info for MessageBodyWriters and MessageBodyReaders

- resteasy-legacy/src/main/java/org/jboss/resteasy/logging/Logger.java
- resteasy-legacy/src/main/java/org/jboss/resteasy/logging/impl/JULLogger.java
- resteasy-legacy/src/main/java/org/jboss/resteasy/logging/impl/Log4jLogger.java
- resteasy-legacy/src/main/java/org/jboss/resteasy/logging/impl/Slf4jLogger.java
[RESTEASY-1578] : https://issues.jboss.org/projects/RESTEASY/issues/RESTEASY-1578
> [RESTEASY-1578] : Mark classes in org.jboss.resteasy.logging in resteasy-legacy module as deprecated.

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchContextualDataTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsynchContextualDataProduct.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsynchContextualDataResource.java
Correcting ResteasyProviderFactory's handling of the context map stack.
> [RESTEASY-1225]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/PropertyInjectorImpl.java
https://issues.jboss.org/browse/RESTEASY-1602
> RESTEASY-1602 added privileged blocks to PropertyInjectorImpl

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
Proposed fix to avoid the leak; unless a specific impl of StorageProvider is requested, use a modified version of the TempFileStorageProvider that does not flag files as to be deleted on exit. Files end up being delete when the message body is disposed.
> [RESTEASY-1467] Workaround for deleteOnExit memory leak

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultCharsetTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/resource/DefaultCharsetResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/resource/basic/DefaultCharsetTestWeb_default.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/resource/basic/DefaultCharsetTestWeb_false.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/resource/basic/DefaultCharsetTestWeb_true.xml
Handle produced text-like media types without a charset.
> [RESTEASY-1565]  (master)

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultCharsetTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/resource/DefaultCharsetResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/resource/basic/DefaultCharsetTestWeb_default.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/resource/basic/DefaultCharsetTestWeb_false.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/resource/basic/DefaultCharsetTestWeb_true.xml
Add missing charset to text like resource method return media types that
lack charset.
> [RESTEASY-1565] (3.0)

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/FactoryFinder.java
[RESTEASY-1574] : https://issues.jboss.org/browse/RESTEASY-1574
[JBEAP-7988] : https://issues.jboss.org/browse/JBEAP-7988
> [RESTEASY-1574]: org.jboss.resteasy.spi.FactoryFinder does not close resources.

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
- jaxrs/tjws/src/main/java/Acme/Serve/Serve.java
Handle Set-Cookie attribute HttpOnly properly.
> [RESTEASY-1545]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/CustomContextProviderPreferenceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomContextProviderPreferenceResolver.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomContextProviderPreferenceResource.java
Cause user defined ContextResolvers to take precedence over built-in
ContextResolvers.
> [RESTEASY-1609]

- jaxrs/arquillian/RESTEASY-1223-WF8/src/test/java/org/jboss/resteasy/resteasy1223/TestResteasy1223.java
- jaxrs/arquillian/RESTEASY-1223-WF8/src/test/resources/META-INF/services/javax.ws.rs.ext.Providers
- jaxrs/providers/yaml/src/test/java/org/jboss/resteasy/test/providers/yaml/TestYamlProvider.java
> [RESTEASY-1618] Yaml unmarshalling vulnerable to RCE

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
Add note about resteasy.add.charset context parameter to User Guide.
> [RESTEASY-1620]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
Decrease log level of "MediaType %1 on %2() lacks charset. Consider ..."
from WARN to INFO.
> [RESTEASY-1622]

- docbook/reference/en/en-US/modules/Content_Marshalling_Providers.xml
- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/CacheInterceptor.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/interceptors/MessageSanitizerContainerResponseFilter.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ListenerBootstrap.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/MediaTypeHelper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ResponseObjectTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/ReaderWriterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/WriterNotBuiltinTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/ContentTypeMatchingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/TypeMappingJettisonTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlPojoBindingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultCharsetTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MatchedResourceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ResourceLocatorTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/ResourceMatchingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/VariantsTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/CustomForbiddenMessageTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ResponseObjectTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/ReaderWriterTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/WriterNotBuiltinTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/ContentTypeMatchingTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/providers/jettison/TypeMappingJettisonTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MatchedResourceTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ResourceLocatorTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/response/VariantsTest.java
Changed treatment of text media types without charset parameter to add
"charset=UTF-8" by default.
> [RESTEASY-1628]

- server-adapters/resteasy-undertow/src/main/java/org/jboss/resteasy/plugins/server/undertow/UndertowJaxrsServer.java
- server-adapters/resteasy-undertow/src/test/java/org/jboss/resteasy/test/undertow/UndertowParameterTest.java
UndertowJaxrsServer can handle context and initial parameters.
> [RESTEASY-1629]

- docbook/reference/en/en-US/modules/Jaxb.xml
Add notes in User Guide about retrieving Collections and Maps of JAXB
objects.
> [RESTEASY-1430]

- providers/resteasy-html/src/main/java/org/jboss/resteasy/plugins/providers/html/HtmlRenderableWriter.java
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/html/HeadersInViewResponseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/html/resource/HeadersInViewResponseResource.java
Handle response headers with View entity in resteasy-html.
> [RESTEASY-1422]

- docbook/reference/en/en-US/modules/Async_job_service.xml
- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- docbook/reference/en/en-US/modules/JAX-RS_Content_Negotiation.xml
- docbook/reference/en/en-US/modules/RESTEasy_EJB_Integration.xml
- docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
- docbook/reference/en/en-US/modules/Securing_JAX-RS_and_RESTeasy.xml
Update web.xml examples in User Guide to omit unnecessary elements like
<servlet> and <servlet-mapping>.
> [RESTEASY-1635]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Base64.java
JBEAP: https://issues.jboss.org/browse/JBEAP-9423
> [JBEAP-9423] Base64 class uses printStackTrace method

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
Avoid unnecessary log messages about missing charset parameter.
> [RESTEASY-1640]

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/core/BaseClientResponse.java
- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/core/executors/ApacheHttpClient4Executor.java
EAP 7.0x: https://issues.jboss.org/browse/JBEAP-10487
> RESTEASY-992 Legacy code fix

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MediaTypeFromMessageBodyWriterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/resource/MediaTypeFromMessageBodyWriterListAsText.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/resource/MediaTypeFromMessageBodyWriterListAsXML.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/resource/MediaTypeFromMessageBodyWriterResource.java
Choice of response entity media type takes MessageBodyWriters into
account (JAX-RS spec Section 3.8).
> [RESTEASY-1227]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/PathParamInjector.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiplePathSegmentTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiplePathSegmentResource.java
Correct treatment of parameters consisting of multiple PathSegments.
> [RESTEASY-1653]

- providers/fastinfoset/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/fastinfoset/FastinfoSetMarshaller.java
- providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/BadgerMarshaller.java
- providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/JettisonMappedMarshaller.java
- providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/JsonJAXBContextFinder.java
- providers/jettison/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/json/JsonParsing.java
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
- resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/InfinispanCache.java
- resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheFeature.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/AbstractCollectionProcessor.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AcceptParameterHttpPreprocessor.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
- resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlMethodMetaData.java
Reported at https://lgtm.com/projects/g/resteasy/Resteasy/alerts/
> Misc fixes

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/SourceProvider.java
- testsuite/README.MD
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/sourceProvider/SourceProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/sourceProvider/resource/Book.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/sourceProvider/resource/BookResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/sourceProvider/resource/SourceProviderApp.java
Issue: https://issues.jboss.org/browse/RESTEASY-1649
> [RESTEASY-1649] SourceProvider fails to write StreamSource created with StringReader

- pom.xml
- resteasy-dependencies-bom/pom.xml
- testsuite/README.MD
- testsuite/integration-tests-spring/deployment/src/test/resources/arquillian.xml
- testsuite/integration-tests-spring/inmodule/src/test/resources/arquillian.xml
- testsuite/integration-tests/src/test/resources/arquillian.xml
- testsuite/pom.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/LinkTest.java
* profile 'jacoco' generates jacoco coverage data
* profile 'jacoco.generate.report' creates html report from coverage data
* fixed LinkTest which fails with jacoco
* documented usage of jacoco plugin in testsuite
> [RESTEASY-1660] Jacoco coverage plugin

- providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBXmlSeeAlsoProvider.java
- providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBXmlTypeProvider.java
- providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/CdiConstructorInjector.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
https://issues.jboss.org/browse/RESTEASY-1663
> [RESTEASY-1663] Reduce memory allocation for better scalability

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/ProcessorFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/EncodedPathProxyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/EncodedPathProxyInterface.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/EncodedPathProxyResource.java
Flip treatment of @Encoded when using a client proxy to send a path
parameter with a "/".
> [RESTEASY-1475]

- docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyWebTarget.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilder.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ChunkedTransferEncodingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/ChunkedTransferEncodingResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/ChunkedTransferEncodingTestFile
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ChunkedTransferEncodingUnitTest.java
- testsuite/unit-tests/src/test/resources/org/jboss/resteasy/test/client/ChunkedTransferEncodingUnitTestFile
Add ability to configure WebTargets and ClientInvocations to be sent in
chunked mode.
> [RESTEASY-1554]

- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/RequestHandler.java
- server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/Expect100Test.java
Fix handling of "Expect: 100-continue" header.
> [RESTEASY-1544]

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/RangeResource.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/RangeResource.java
RangeTest didn't clean up tmp files properly.
> [TS] Clean up temporary files after testsuite run

- docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
@asoldano please review.
Just let me know if I should open a JIRA for this change and rename the PR title.
> [RESTEASY-1687] Adding sample to Spring Boot documentation section

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/MessageBodyParameterProcessor.java
Fix for RESTEASY-1684. I have added no test for this.
> Fix for RESTEASY-1684. No test added.

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/DefaultNumberWriter.java
> [RESTEASY-1697] Add BigInteger support to DefaultNumberWriter

- docbook/reference/en/en-US/modules/gzip.xml
Added path details for GZIP chapter.
> RESTEASY-1654 Updated docs

- docbook/reference/en/en-US/modules/StringConverter.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/DateParamConverter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedCookieParam.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedCookieParamConverter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParam.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamConverter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamConverterProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamResourceClient.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedPathParam.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedPathParamConverter.java
I've merged the code from https://github.com/resteasy/Resteasy/pull/1093
into master branch, along with documentation in StringConverter.xml in
the User Guide.
> [RESTEASY-1566]

- distribution/assembly.xml
- distribution/pom.xml
- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- jboss-modules/build.xml
- jboss-modules/pom.xml
- jboss-modules/src/main/resources/modules/javax/json/bind/api/main/module.xml
- jboss-modules/src/main/resources/modules/org/eclipse/yasson/main/module.xml
- jboss-modules/src/main/resources/modules/org/glassfish/javax/json/main/module.xml
- jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
- jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-binding-provider/main/module.xml
- providers/json-binding/pom.xml
- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/i18n/LogMessages.java
- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/i18n/Messages.java
- providers/json-binding/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
- providers/pom.xml
- resteasy-bom/pom.xml
- resteasy-client/pom.xml
- resteasy-dependencies-bom/pom.xml
- resteasy-jaxrs/pom.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/FindAnnotation.java
- testsuite/integration-tests-spring/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/Cat.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/JsonBindingResource.java
- testsuite/legacy-integration-tests/pom.xml
> [RESTEASY-1665] Json-Binding provider and clientside support

- docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
- docbook/reference/en/en-US/modules/StringConverter.xml
- docbook/reference/en/en-US/modules/gzip.xml
Adding documentation about annotations in org.jboss.resteasy.annotations
in resteasy-jaxrs.
> [RESTEASY-1543]

- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpRequestDecoder.java
- server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/HeaderTooLongTest.java
Prevent resteasy-netty4 from swallowing some errors.
> [RESTEASY-1244]

- resteasy-upgrade-guide/reference/en/en-US/modules/Miscellaneous.xml
Test revised based upon coding feedback on PR for RESTEASY-1712
> [RESTEASY-1703] added subsection in upgrade guide

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/LinkBuilderImpl.java
Fix NPE in LinkBuilderImpl.build()
> RESTEASY-1720

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseWithEntityTest.java
Cleaned up version of https://github.com/resteasy/Resteasy/pull/1244
> RESTEASY-1700

- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
@FroMage FYI, just in case I got this wrong ;-)
> [RESTEASY-1701] Fixing oversight

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/PathParamInjector.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/PathParamMissingDefaultValueTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/resource/PathParamMissingDefaultValueBeanParamEntity.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/resource/PathParamMissingDefaultValueResource.java
Add test to resteasy-integration-tests.
[RESTEASY-1732]
Fix treatment of missing @DefaultValue for @pathparam.
> [RESTEASY-1732]

- docbook/reference/en/en-US/master.xml
- docbook/reference/en/en-US/modules/JAX-RS_2.1_additions.xml
Here is a starting point.  Others should add more details.
> [RESTEASY-1727] initial pass at documentation

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AbstractAsynchronousResponse.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousExecutionContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PostMatchContainerRequestContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
- resteasy-legacy/src/main/java/org/jboss/resteasy/core/interception/ContainerResponseContextImpl.java
- resteasy-legacy/src/main/java/org/jboss/resteasy/core/interception/PostMatchContainerRequestContext.java
- resteasy-legacy/src/main/java/org/jboss/resteasy/core/interception/PreMatchContainerRequestContext.java
- resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasyHandlerAdapter.java
- resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasyNoResourceFoundView.java
- resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasyView.java
- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
- server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/ChunkOutputStream.java
- server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
- server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpResponse.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncRequestFilterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilterResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseResource.java
rebased and more backward compatible version of https://github.com/resteasy/Resteasy/pull/1318
> [RESTEASY-1701] Fix early connection completion on async response filters

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/ProviderPriorityProvidersInApplicationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/ProviderPriorityProvidersRegisteredProgramaticallyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityExceptionMapperAAA.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityExceptionMapperBBB.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityExceptionMapperCCC.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityFoo.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityFooParamConverter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityFooParamConverterProviderAAA.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityFooParamConverterProviderBBB.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityFooParamConverterProviderCCC.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/resource/ProviderPriorityTestException.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/PriorityEqualityTest.java
ResteasyProviderFactory handles ExceptionMappers and
ParamConverterProviders according to @Priority.
> [RESTEASY-1739]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/CookieParamWrapper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/CookieParamWrapperArrayConverter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamConverterProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamResourceClient.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamWrapper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamWrapperArrayConverter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/PathParamWrapper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/PathParamWrapperArrayConverter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ResponseHeaderTest.java
This PR is about providing support for custom conversion between multi valued param (queryParam, MatrixPartam, headerParam...) and array type arguments as it has been done in https://github.com/resteasy/Resteasy/pull/1251
> [RESTEASY-1746] Provide support for multi valued resource method array type arguments

- jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
JIRA: https://issues.jboss.org/browse/JBEAP-13427
Upstream PRs: #1299 
Upstream JIRAs: https://issues.jboss.org/browse/RESTEASY-1728
Follows up on #1303
>  [JBEAP-13427]  [JBEAP-13427,RESTEASY-1728] Look for resteasy.allowGzip system property in RegisterBuiltin

- docbook/reference/en/en-US/master.xml
- docbook/reference/en/en-US/modules/Asynchronous_HTTP.xml
- docbook/reference/en/en-US/modules/Interceptors.xml
- docbook/reference/en/en-US/modules/JAX-RS_2.1_additions.xml
- docbook/reference/en/en-US/modules/Reactive.xml
The long-awaited docs for the new async filter/return types features of Resteasy
> New docs for async filter/return types

- resteasy-legacy/src/main/java/org/jboss/resteasy/client/core/BaseClientResponse.java
See the attached JIRA issue for details: https://issues.jboss.org/browse/RESTEASY-1757
> [RESTEASY-1757]: fix NPE when input stream is null

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- docbook/reference/en/en-US/modules/Migration_from_older_versions.xml
- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/finegrain/resource/ClientErrorTest.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/MethodExpression.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientErrorTest.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/web_loose.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/web_not_loose.xml
Impose spec mandated restriction on resource methods considered in
resource matching algorithm.
> [RESTEASY-1763]

- providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBXmlTypeProvider.java
- providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/i18n/Messages.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/HomecontrolCustomJAXBContextTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/HomecontrolApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/HomecontrolCustomJAXBContext.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/HomecontrolJaxbProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/HomecontrolService.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/Base64Binary.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/BinaryType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/ErrorDomainType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/ErrorMessageType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/ErrorType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/IDType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/ObjectFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/RoleType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/UserType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/resource/homecontrol/package-info.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/jaxb/homecontrol/web.xml
I have run CI several times.  On each run, one of the env fails on test org.jboss.resteasy.test.providers.sse.SseTest.
The env that fails appears to be random.  I reviewed SseTest.  I don't see that this code change is causing this randon test failure.
> [RESTEASY-1754] add getter for JAXBContext and add testcase

- docbook/reference/en/en-US/modules/Migration_from_older_versions.xml
Adding documentation for the change in RESTEASY-1753.
> [RESTEASY-1753]

- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/smoke/SimpleResource.java
- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/smoke/TestSmoke.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
Jira: https://issues.jboss.org/browse/RESTEASY-1765
EAP 7.1 Jira: https://issues.jboss.org/browse/JBEAP-13928
PR to master branch: https://github.com/resteasy/Resteasy/pull/1358
> **NOTE**:  PR to the master branch does not apply to `3.0` branch for test cases, so the test cases in this PR are different than what are in master branch PR: https://github.com/resteasy/Resteasy/pull/1358
> [RESTEASY-1765] Remove q-qs parameters from header Content-type in responses

- docbook/reference/en/en-US/modules/Jaxb.xml
Update link to jettison in User Guide.
> [RESTEASY-1291]

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/CorsFiltersTest.java
Adding test coverage for JBEAP-12820
> [RESTEASY-1704] Test coverage.

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/CorsFiltersTest.java
Test coverage for JBEAP-12821
Issue: https://issues.jboss.org/browse/JBEAP-12821
Upstream Issue: https://issues.jboss.org/browse/RESTEASY-1704
Backporting test coverage for RESTEASY-1704 to 3.5 branch, (JBEAP 7.2.0)
> [RESTEASY-1704] Test coverage

- jboss-modules/build.xml
- jboss-modules/src/main/resources/modules/org/eclipse/microprofile/restclient/main/module.xml
- jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
- resteasy-cdi/pom.xml
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientDelegateBean.java
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientExtension.java
- resteasy-cdi/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/microprofile/DefaultResponseExceptionMapper.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilderResolver.java
- resteasy-client/src/main/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver
- resteasy-dependencies-bom/pom.xml
- resteasy-jaxrs/pom.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/microprofile-tck/pom.xml
- testsuite/pom.xml
This provides an implementation of the Microprofile RestClient specification 1.0. Your review and thoughts are appreciated.
- Specification: https://github.com/eclipse/microprofile-rest-client/releases/tag/microprofile-rest-client-1.0
- CDI Extensions and TCK Runner: https://github.com/heiko-braun/mp-rest-client-impl
> Add support for Microprofile RestClient API

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java
Check for local connection in CompletionStageResponseTest.
> [RESTEASY-1801]

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/RedirectTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/RedirectProxyResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/RedirectResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/TestResource.java
jira: https://issues.jboss.org/browse/RESTEASY-1808
master PR: https://github.com/resteasy/Resteasy/pull/1413
> [RESTEASY-1808] Tests for client redirection

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/RxInvokerTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/TestResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java
jira: https://issues.jboss.org/browse/RESTEASY-1812
master PR: https://github.com/resteasy/Resteasy/pull/1422
This PR updates also end-point for CompletionStageResponseTest
> [RESTEASY-1812] Tests for reactive client

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/RxInvokerTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingAnnotationsJacksonTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/Cat.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/JsonBindingCustomRepeaterProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/JsonBindingResource.java
- testsuite/integration-tests/src/test/resources/jboss-deployment-structure-json-b.xml
jira: https://issues.jboss.org/browse/RESTEASY-1814
3.5 PR: https://github.com/resteasy/Resteasy/pull/1426
> [RESTEASY-1814] Tests for JSON-B integration

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEnablingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseSmokeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseReconnectResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeMessageBodyWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeUser.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/sse/OutboundSseEventImplTest.java
This is part 1, to be included before 3.5.0.Final tag.
> [RESTEASY-1815] Sse tests

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseBroadcasterImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java
Same changes as in https://github.com/resteasy/Resteasy/pull/1395
> [RESTEASY-1793] Backporting changes to 3.5

- profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/MockedProfilingTest.java
- profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/ProfilingTest.java
- providers/jackson/src/test/java/org/jboss/resteasy/test/nextgen/providers/jackson/JacksonTest.java
- security-legacy/keystone/keystone-core/src/test/java/org/jboss/resteasy/test/keystone/TokenTest.java
- security-legacy/skeleton-key-idm/skeleton-key-core/src/test/java/org/jboss/resteasy/test/skeleton/key/SkeletonKeyTokenTest.java
- security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/security/doseta/SigningTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeMessageBodyWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/PatchErrorHandlingTest.java
Eliminate System.out.println + code cleanup
https://issues.jboss.org/browse/RESTEASY-1832
> [RESTEASY-1832] Eliminate System.out.println + code cleanup

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseRedirectTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/ContextProvidersTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CookieTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/HttponlyCookieTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseRedirectTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/ContextProvidersTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
- testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/response/CookieTest.java
Use Map.entrySet instead of iterating keySet and getting value later
https://issues.jboss.org/browse/RESTEASY-1810
~~Please **do not merged yet**, we need to discuss few items:~~
> [RESTEASY-1810] Usage of Map.entrySet instead of keySet in tests

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipTest.java
Adding test coverage for https://issues.jboss.org/browse/JBEAP-13475
> [RESTEASY-1735] Test coverage.

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/PartialAnnotationResourceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/PartialAnnotationResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/PartialAnnotationResourceImpl.java
Fix and tests
Jira: https://issues.jboss.org/browse/RESTEASY-798
> [RESTEASY-798] RestEasy takes into account (interface) methods without annotations

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/multipart/Jackson2MultipartFormTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/multipart/JsonForm.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/multipart/JsonFormResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/multipart/JsonUser.java
Create test to verify that RESTEasy can inject JSON formatted data into @MultipartForm parameter correctly
> RESTEASY-1841

- docbook/pom.xml
- docbook/reference/en/en-US/master.xml
- docbook/reference/en/en-US/modules/Multipart.xml
https://issues.jboss.org/browse/RESTEASY-1842
Create document to show how to inject JSON format data into @MultipartForm parameter correctly
> RESTEASY-1842

- docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
- resteasy-client/pom.xml
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyClientEngine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyClientResponse.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyContentStream.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyResponseStream.java
- resteasy-dependencies-bom/pom.xml
- testsuite/arquillian-utils/pom.xml
- testsuite/unit-tests/pom.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/JettyClientEngineTest.java
Rebased version of https://github.com/resteasy/Resteasy/pull/1380/ (plus doc fixes)
> [RESTEASY-1862] JettyClientEngine

- pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAllowGzipOnClientTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerNotAllowGzipOnClientTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAllowGzipOnClientTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerNotAllowGzipOnClientTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/resource/GzipInterface.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/resource/GzipResource.java
- testsuite/integration-tests/src/test/resources/arquillian.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTest-javax.ws.rs.ext.Providers
jira: https://issues.jboss.org/browse/RESTEASY-1882
upstream merged PR (master branch): https://github.com/resteasy/Resteasy/pull/1498
> [RESTEASY-1882] Regression tests for RESTEASY-1735 (gzip tests)

- docbook/reference/en/en-US/modules/Reactive.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/annotations/Stream.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawFlowableRxJava2Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawObservableRxJava1Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawObservableRxJava2Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawByteArrayMessageBodyReaderWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawFlowableRxJava2Resource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawMediaTypes.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawObservableRxJava1Resource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawObservableRxJava2Resource.java
Minor corrections pointed out on
https://github.com/resteasy/Resteasy/pull/1503.
> [RESTEASY-1798]

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ResponseExceptionMapperRuntimeExceptionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ExceptionMapperRuntimeExceptionWithReasonMapper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ResponseExceptionMapperRuntimeExceptionMapper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ResponseExceptionMapperRuntimeExceptionResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ResponseExceptionMapperRuntimeExceptionResourceInterface.java
Jira: https://issues.jboss.org/browse/RESTEASY-1847
Cherry picked from commit 2097354b48221224e409c3fe4303442d3d7edd7f
> [RESTEASY-1847] ClassCastException for Throwable produced by ResponseExceptionMapper

- docbook/reference/en/en-US/modules/Reactive.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageClientAsyncTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageServerAsyncTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageTest.java
Adding notes about using context objects in asynchronous code.
> [RESTEASY-1782]

- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/FindAnnotation.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchContextualDataTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/NullEntityProxyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/ExceptionMapperMarshalTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/JacksonJaxbCoexistenceProduct.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/VariantAcceptTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ApplicationScopeValidationTest.java
RESTEasy side of simpler / better performing alternative to #1566 
This needs changes on WFLY side too.
> RESTEASY-1911 / RESTEASY-1929 

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingAnnotationsJacksonTest.java
- testsuite/integration-tests/src/test/resources/jboss-deployment-structure-no-json-b.xml
> Fix test on container with jsonb always on

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/ClientResponseFilterExceptionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionFilter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResourceImpl.java
Close connection if server returns an entity but a ClientResponseFilter
throws an exception.
> [RESTEASY-1932]

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartFormDataWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/EncodingMimeMultipartFormProviderResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTestData.txt
Jira: https://issues.jboss.org/browse/RESTEASY-1779
> [RESTEASY-1779] Filename encoding is wrong in MultipartFormDataInput

- resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
Please read the discussion on #1456 on the reasoning that led to this PR
> [RESTEASY-1838]: Remove the SseEventSource.open() 30 seconds timeout to be fully synch

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/ClassNode.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyServerTracingEvent.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingUtils.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/BasicTracingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/Foo.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/FooLocator.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/OnDemandTracingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingApp.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/tracing/logging.properties
Server tracing events are all implemeted, and tests are added. Some minor bugs are fixed.
> [RESTEASY-1890] Implement all the server side tracing events.

- profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/InMemoryClientEngine.java
- resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientResponse.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AbortedResponse.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
- resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
> [Resteasy 1863] (2): SseEventSourceImpl should not close http client engine

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- docbook/reference/en/en-US/modules/Using_Path.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/MethodExpression.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientErrorTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/Jaxrs20MatchingResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/jaxrs_2_0_web.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/jaxrs_2_1_web.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest_Default.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest_Jaxrs20.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest_Jaxrs21.xml
Provide option for JAX-RS 2.0 resource method matching.
> [RESTEASY-1951]

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Filter30Dispatcher.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
which is required by Servlet spec.
> [RESTEASY-1748] Added "value" parameter to @webfilter and @WebServlet annotations,

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Filter30Dispatcher.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
annotations,
which is required by Servlet spec.
> [RESTEASY-1748] Added "value" parameter to @webfilter and @WebServlet

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
> [RESTEASY-1981] Prevent multiple instance registration of same provider

- .travis.yml
- testsuite/pom.xml
Move towards WildFly 14
https://issues.jboss.org/browse/RESTEASY-2002
> [RESTEASY-2002] Move towards WildFly 14

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ResponseTrimmingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/ResponseTrimmingResource.java
Prepare test for error message length
Jira: https://issues.jboss.org/browse/RESTEASY-2028
Master PR: https://github.com/resteasy/Resteasy/pull/1712
> [RESTEASY-2028] Prepare test for error message length

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/PreferJacksonOverJsonBClientTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/PreferJacksonOverJsonBClientResource.java
Prepare test for resteasy.preferJacksonOverJsonB property for client on deployment
This PR replaces https://github.com/resteasy/Resteasy/pull/1668
Jira: https://issues.jboss.org/browse/RESTEASY-1998
3.6 PR: https://github.com/resteasy/Resteasy/pull/1733
> [RESTEASY-1998] Prepare test for resteasy.preferJacksonOverJsonB property for client on deployment

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartFormDataWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/EncodingMimeMultipartFormProviderResource.java
Cherry picked from commit 0a0fce67adabab3050a7ca4238982dde0684aa7e
> [RESTEASY-2046] Space Improperly Encoded in Content-Disposition Filename

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/SetMethodWithMoreArgumentsTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/Dog.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/SetMethodWithMoreArgumentsResource.java
Prepare test for yasson/issues/152 - setter with multiple arguments
Jira: https://issues.jboss.org/browse/RESTEASY-2064
Master PR: https://github.com/resteasy/Resteasy/pull/1766
cc @marekkopecky
> [RESTEASY-2064] Prepare test for yasson/issues/152 - setter with multiple arguments

- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/PriorityTest.java
Hey @ronsigal, @asoldano,
This PR is simply to add the test of ContextResolver registration with priority override I was talking about in the first PR: https://github.com/resteasy/Resteasy/pull/1709#issuecomment-435511726
> [RESTEASY-2026]: Priority override MUST be taken into account when registering (2)

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/ProviderContextInjectionEnumContextResolver.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/ProviderContextInjectionTextPlainEnumContextResolver.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/PriorityTest.java
This PR is for 3.6 branch.
Master branch PR: https://github.com/resteasy/Resteasy/pull/1709
> [RESTEASY-2026]: Priority override MUST be taken into account when registering

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/ApplicationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/ApplicationTestAExplicitApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/ApplicationTestBExplicitApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/ApplicationTestSingletonA.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/ApplicationTestSingletonB.java
Extend ApplicationTest to test getSingletons()
Jira: https://issues.jboss.org/browse/RESTEASY-2082
3.6: https://github.com/resteasy/Resteasy/pull/1795
> [RESTEASY-2082] Extend ApplicationTest to test getSingletons()

- .travis.yml
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly12.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
- testsuite/pom.xml
Jira: https://issues.jboss.org/browse/RESTEASY-2094
3.6 PR: https://github.com/resteasy/Resteasy/pull/1797
> [RESTEASY-2094] Use WF15 in travis testing

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/NoApplicationSubclassTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/NoApplicationSubclassResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/core/basic/NoApplicationSubclassWeb.xml
Prepare test for application packaging when Application subclass is not present
Jira: https://issues.jboss.org/browse/RESTEASY-2081
Master: https://github.com/resteasy/Resteasy/pull/1792
> [RESTEASY-2081] Prepare test for application packaging when Application subclass is not present

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncBenchTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorBasicTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcastTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseBroadcastResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultMediaTypeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
Jira: https://issues.jboss.org/browse/RESTEASY-2077
master PR: https://github.com/resteasy/Resteasy/pull/1790
Cleanup of ignored tests:
* DuplicitePathTest
* related bug is fixed
* fix test
* remove ignoring
* SseBroadcastTest
* add description to ignore annotation
* improve ignored tests (cc @jimma )
* btw, related jira was reopened [RESTEASY-1819](https://issues.jboss.org/browse/RESTEASY-1819)
* AsyncBenchTest
* improve javadoc
* add description to ignore annotation
* ResourceClassProcessorBasicTest
* add description to ignore annotation
* DefaultMediaTypeTest
* improve javadoc
cc: @jbliznak
> [RESTEASY-2077] Cleanup of ignored tests

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java
Fix org.jboss.resteasy.test.xxe.SecureProcessingTest and org.jboss.resteasy.test.xxe.SecureProcessing2Test
Jira: https://issues.jboss.org/browse/RESTEASY-1806
Master: https://github.com/resteasy/Resteasy/pull/1803
> [RESTEASY-1806] org.jboss.resteasy.test.xxe.SecureProcessing*Test fix

- testsuite/pom.xml
Default WildFly version bump
Trivial change, no trcking JIRA was created.
> Default WildFly version bump

- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
* https://issues.jboss.org/browse/RESTEASY-2106
> RESTEASY-2106 Don't swallow JSON binding exceptions

- resteasy-core-spi/pom.xml
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ConstructorInjector.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ContextInjector.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/PropertyInjector.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/StringParameterUnmarshaller.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ValueInjector.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/AbstractCollectionFormInjector.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/PrefixedFormInjector.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-core/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLogger.java
- resteasy-spring/src/main/java/org/jboss/resteasy/plugins/spring/SpringBeanProcessor.java
- resteasy-spring/src/main/java/org/jboss/resteasy/propertyeditor/mediatype/editor/MediaTypeEditor.java
Jira: https://issues.jboss.org/browse/RESTEASY-2055
> [RESTEASY-2055] Fixed Javadoc

- resteasy-dependencies-bom/pom.xml
Versions upgrade - mail, vertx, undertow, rxjava, validator
https://issues.jboss.org/browse/RESTEASY-2116
> [RESTEASY-2116] Versions upgrade - mail, vertx, undertow, rxjava, validator

- resteasy-core-spi/pom.xml
- resteasy-core/pom.xml
Remove unused redhat-xerces profiles
https://issues.jboss.org/browse/RESTEASY-2118
> [RESTEASY-2118] Remove unused redhat-xerces profiles

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- resteasy-core/src/main/java/org/jboss/resteasy/util/Base64.java
- resteasy-core/src/main/java/org/jboss/resteasy/util/GroupParameterParser.java
- resteasy-core/src/main/java/org/jboss/resteasy/util/ParameterParser.java
- resteasy-links/src/main/java/org/jboss/resteasy/links/ResourceID.java
- resteasy-links/src/main/java/org/jboss/resteasy/links/ResourceIDs.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableProvider.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableRxInvoker.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableRxInvokerImpl.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableRxInvokerProvider.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleProvider.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleRxInvoker.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleRxInvokerImpl.java
- resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleRxInvokerProvider.java
Jira: https://issues.jboss.org/browse/RESTEASY-2055
Relates to https://github.com/resteasy/Resteasy/pull/1818
> [RESTEASY-2055] Fixed Javadoc for Java 11

- .travis.yml
Added CI run for Javadoc.
Jira: https://issues.jboss.org/browse/RESTEASY-2055
> [RESTEASY-2055] Added CI run for Javadoc

- resteasy-dependencies-bom/pom.xml
[RESTEASY-2117] Versions upgrade - netty, jetty, apis, logging, mp config, weld, wf elytron, wf core
https://issues.jboss.org/browse/RESTEASY-2117
> [RESTEASY-2117] Versions upgrade - netty, jetty, apis, logging, mp config, weld, wf elytron, wf core

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DocumentProvider.java
For details, see the referenced JIRA.
> [RESTEASY-2109] [master] Add nullary constructor to fix native image generation

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/DocumentProvider.java
> [RESTEASY-2109] [3.6] Add nullary constructor to fix native image generation

- resteasy-spring/pom.xml
- testsuite/integration-tests-spring/pom.xml
[RESTEASY-2121] Spring versions sync
https://issues.jboss.org/browse/RESTEASY-2121
> [RESTEASY-2121] Spring versions sync

- jboss-modules/build.xml
- resteasy-dependencies-bom/pom.xml
Upgrade of json-patch to 1.9
https://issues.jboss.org/browse/RESTEASY-2126
> [RESTEASY-2126] Upgrade of json-patch to 1.9

- resteasy-links/src/main/java/org/jboss/resteasy/links/impl/JsonLinkDecorator.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/Book.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStore.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStoreMinimal.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/Comment.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/SecureBookStore.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/SecureBookStoreMinimal.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestFacadeLinks.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestLinks.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/BookStoreInvalidEL.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/BookStoreNoPackage.java
Fix the 3 failed resteasy-link tests after replacing jettison with jackson
> RESTEASY-2099

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseWithEntityTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/ClientResponseWithEntityResponseFilter.java
[RESTEASY-2097] Update ClientResponse
> [RESTEASY-2097f] Reset streamRead in ClientResponse.resetEntity().

- docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
- resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
- resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
Jira: https://issues.jboss.org/browse/RESTEASY-1952
Includes small piece of doc so that this is also documented.
> [RESTEASY-1952] Unable to set proxy via JAX-RS API

- .travis.yml
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly13.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson/JacksonTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson/ProxyWithGenericReturnTypeJacksonTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJaxbCoexistenceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/ProxyWithGenericReturnTypeJacksonTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
- testsuite/pom.xml
Jira: https://issues.jboss.org/browse/RESTEASY-2173
Master PR: https://github.com/resteasy/Resteasy/pull/1882
Move towards WildFly 16
*  set default server version to WildFly 16
*  update Travis configuration to run WF 14/15/16
> [RESTEASY-2173] Move towards WildFly 16

- .travis.yml
Jira: https://issues.jboss.org/browse/RESTEASY-2173
Master PR: https://github.com/resteasy/Resteasy/pull/1885
> [RESTEASY-2173] Use WildFly 16 for javadoc travis testing

- providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyContext.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventSinkInterceptor.java
Some tentative changes to try improving performances after having looked at few recent jfr recordings; this is possibly related to https://issues.jboss.org/browse/RESTEASY-2000
> Misc minor perf improvements

- resteasy-core/src/main/resources/META-INF/services/org.jboss.resteasy.tracing.api.RESTEasyTracingInfo
- resteasy-dependencies-bom/pom.xml
This requires https://github.com/resteasy/resteasy-extensions/pull/5
> [RESTEASY-2110] Fixing issue with JPMS / JDK9+

- pom.xml
- profiling-tests/pom.xml
- testsuite/pom.xml
https://issues.jboss.org/browse/RESTEASY-2181
This PR covers part of the linked jira, more to come in separate PRs to allow better review.
> [RESTEASY-2181] Fix some maven warnings

- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
- testsuite/integration-tests/src/test/resources/arquillian.xml
Issue: https://issues.jboss.org/browse/RESTEASY-2171
> [RESTEASY-2171] JsonBindingProvider use incorrect charset encoding

- providers/jackson2/src/main/java/org/jboss/resteasy/tracing/providers/jackson2/Jackson2JsonFormatRESTEasyTracingInfo.java
- providers/jackson2/src/main/resources/META-INF/services/org.jboss.resteasy.tracing.api.RESTEasyTracingInfo
- providers/json-binding/src/main/java/org/jboss/resteasy/tracing/providers/jsonb/JSONBJsonFormatRESTEasyTracingInfo.java
- providers/json-binding/src/main/resources/META-INF/services/org.jboss.resteasy.tracing.api.RESTEasyTracingInfo
> [RESTEASY-1887] Fix JPMS issue with tracing classes in split packages

- resteasy-core/src/main/java/org/jboss/resteasy/specimpl/BuiltResponse.java
Clean useless variable in BuiltResponse class
jira: https://issues.jboss.org/browse/RESTEASY-2193
3.7 PR: https://github.com/resteasy/Resteasy/pull/1939
> [RESTEASY-2193] Clean useless variable in BuiltResponse class

- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
- resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheFeature.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/FormParamInjector.java
- resteasy-core/src/main/java/org/jboss/resteasy/util/Encode.java
- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/SniConfiguration.java
https://issues.jboss.org/browse/RESTEASY-2181
This is another part of the jira above, replacing usage deprecated calls of third party libraries.
> [RESTEASY-2181] Replace usage of deprecated stuff

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
- resteasy-core/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLogger.java
- resteasy-core/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLoggerImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingEnableTracingRequestFilter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/JsonFormattedTracingInfoTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingTestBase.java
> [RESTEASY-1977] Make server side tracing info to include request instance id 

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/RESTEasyParamCdiTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/RESTEasyParamBeanCdi.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/RESTEasyParamCdiResource.java
An integration test-case for RESTEASY-2194.
https://issues.jboss.org/browse/RESTEASY-2194
https://github.com/resteasy/Resteasy/pull/1942
> RESTEASY-2194 integration test-case

- docbook/reference/en/en-US/modules/Async_job_service.xml
- docbook/reference/en/en-US/modules/Cache_NoCache_CacheControl.xml
- docbook/reference/en/en-US/modules/Content_Marshalling_Providers.xml
- docbook/reference/en/en-US/modules/ExceptionMappers.xml
- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- docbook/reference/en/en-US/modules/JAX-RS_Content_Negotiation.xml
- docbook/reference/en/en-US/modules/Jaxb.xml
- docbook/reference/en/en-US/modules/Json.xml
- docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
- docbook/reference/en/en-US/modules/Securing_JAX-RS_and_RESTeasy.xml
- docbook/reference/en/en-US/modules/Validation.xml
- docbook/reference/en/en-US/modules/gzip.xml
> [RESTEASY-2131] Documentation for use of MicroProfile Config

- resteasy-dependencies-bom/pom.xml
- testsuite/README.MD
- testsuite/pom.xml
JaCoCo profile update
https://issues.jboss.org/browse/RESTEASY-2209
- avoid need for sources
- don't use external server
- update JaCoCo version
> [RESTEASY-2209] JaCoCo profile update

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/resource/BasicAuthRequestFilter.java
Jira: https://issues.jboss.org/browse/RESTEASY-2216
3.7: https://github.com/resteasy/Resteasy/pull/1987
> [RESTEASY-2216] Tests for testing basic authentication with ClientRequestFilter

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
- resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_en.properties
- resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_en_US.properties
- resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_xx.properties
- resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_xx_YY.properties
Jira: https://issues.jboss.org/browse/RESTEASY-1290
Master branch is fixed by a part of commit 28d62dae1e8b52554d3c79750cd4249254bdca33
> [RESTEASY-1290] Missing value in String format when parsing enums in query param

- resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/ProviderWithNoProducesTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/resource/Foo.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/resource/ProviderWithNoProducesMessageBodyWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/resource/ProviderWithNoProducesResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/noproduces/ProviderWithNoProduces_web.xml
> [RESTEASY-2232] Don't ignore MessageBodyWriters without @Produces

- resteasy-core/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/OptionalInjectionTest.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/OptionalResource.java
https://issues.jboss.org/browse/RESTEASY-1419
> RESTEASY-1419: add support for injecting Optional<T> parameter types

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/ContextResolverPriorityTest.java
removed from ResteasyProviderFactory.
> [RESTEASY-2231] Restore addContextResolver() methods previously

- jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-cdi/main/module.xml
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/JaxrsInjectionTarget.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Types.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptorResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_off.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_on.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
methods before validation.
[RESTEASY-2227] Checkstyle corrections
> [RESTEASY-2227] With CDI enabled, execute any @PostConstruct

- .travis.yml
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ClientHttpEngineBuilder43.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWildcardHostnameCertificateTest.java
shouldn't accept wildcard certificates
> [RESTEASY-2176]:Client-side SSL - HostnameVerificationPolicy.STRICT

- jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-cdi/main/module.xml
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/JaxrsInjectionTarget.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Types.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptorResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_off.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_on.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
methods
port of #2024 
JIRA: https://issues.jboss.org/browse/JBEAP-16688
>  [JBEAP-16688,RESTEASY-2227] With CDI enabled, execute any @PostConstruct

- docbook/reference/en/en-US/modules/Multipart.xml
fix the programlisting / fix indentation
> RESTEASY-2159 Review multipart provider documentation

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/DynamicFeatureTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/AddDynamicFeature.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/DynamicFeatureResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/GreetingInterceptor.java
Jira: https://issues.jboss.org/browse/RESTEASY-2251
3.7: https://github.com/resteasy/Resteasy/pull/2038
> [RESTEASY-2251] Test for DynamicFeature

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ClientHttpEngineBuilder43.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/HttpProxyTest.java
This put the code on master in synch with #2068
> RESTEASY-1952 additional changes / test improvements

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletDispatcher.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletContainerDispatcher.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/MicroProfileConfigUseGlobalTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/MicroProfileConfigUseGlobalApplication1.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/MicroProfileConfigUseGlobalApplication2.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/MicroProfileConfigUseGlobalResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_use_global.xml
Replaces https://github.com/resteasy/Resteasy/pull/2075
> [RESTEASY-2266] Fix storage of ServletConfig when useGlobal applies.

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/messagebody/ReaderUtility.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ReaderInterceptorContextTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextInterceptor.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextResource.java
> [RESTEASY-2298] ReaderInterceptorContext.getHeaders() must return a

- resteasy-core/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/messagebody/ReaderUtility.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ReaderInterceptorContextTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextInterceptor.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextResource.java
> [RESTEASY-2299] ReaderInterceptorContext.getHeaders() must return a

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java
Improvement based on https://github.com/resteasy/Resteasy/pull/1796#issuecomment-454384550.
jira: https://issues.jboss.org/browse/RESTEASY-2160
3.8: https://github.com/resteasy/Resteasy/pull/2095
> [RESTEASY-2160] Improve SseBroadcasterTest#testErrorListeners

- resteasy-dependencies-bom/pom.xml
> [RESTEASY-2308] Upgrade Jackson databind to 2.9.9.2

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ContentLanguageHeaderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/ContentLanguageHeaderResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
Jira: https://issues.jboss.org/browse/RESTEASY-2296
3.8: https://github.com/resteasy/Resteasy/pull/2093
> [RESTEASY-2296] Expand test coverage of response headers

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
- RESTEASY-2319 Resteasy-based application not deploying under Weblogic application server
> RESTEASY-2085 index.html (welcome-file in web.xml) is broken on Tomcat

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
…t (#2134)
* - RESTEASY-2085 index.html (welcome-file in web.xml) is broken on Tomcat
- RESTEASY-2319 Resteasy-based application not deploying under Weblogic application server
* fix url value
* Update HttpServlet30Dispatcher.java
> RESTEASY-2085 index.html (welcome-file in web.xml) is broken on Tomcat (branch 3.9)

- resteasy-core/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/OptionalInjectionTest.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/NotSupportedOpitionalPathParamResource.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/OptionalResource.java
Adjust the Optional feature implemented for @PathParam according to the discussion in EAP7-1248
> RESTEASY-2330

- docbook/reference/en/en-US/master.xml
- docbook/reference/en/en-US/modules/_OptionalParam.xml
add document for optional typed parameters
> RESTEASY-2332

- docbook/reference/en/en-US/master.xml
- docbook/reference/en/en-US/modules/_OptionalParam.xml
add document for optional typed parameters
> RESTEASY-2332 (for branch 3.9)

- .gitignore
- resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
- resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
https://issues.jboss.org/browse/RESTEASY-2325
> RESTEASY-2325 : Add request timeout support for Reactor Netty HttpClient

- resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
Do not include extractResult in the ReactorNettyClient requestTimeout
> [RESTEASY-2344] Do not include extractResult in requestTimeout

- resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
- resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/RESTEASY_2335_Resource.java
- resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/RESTEASY_2335_Test.java
* RESTEASY-2335 RestEasy Microprofile Client has a immutable template problem/bug
* fix NPE
> RESTEASY-2335 RestEasy Microprofile Client has a immutable template problem/bug

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormAnnotationReader.java
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormAnnotationWriter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/ContextProvidersTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/ContextProvidersCustomerFormNewAnnotationOnField.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/ContextProvidersCustomerFormNewAnnotationOnSetter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/ContextProvidersResource.java
Allow the multipart resolution to work with the new `@FormParam` annotations
> Multipart new annotations

- resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionClientEngineBuilder.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
- Create a ClientHttpEngineBuilder for URLConnectionEngine
- Modify URLConnectionEngine to set the read and connect timeouts
- Modify RestClientBuilderImpl to use the new builder to set the httpEngine
> [RESTEASY-2377] Improved handling of ClientHttpEngine

- resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriInfo.java
- resteasy-core/src/test/java/org/jboss/resteasy/specimpl/ResteasyUriInfoTest.java
> [RESTEASY-2375] Allow Caching of ResteasyUriInfo construction data

- resteasy-core/src/main/java/org/jboss/resteasy/specimpl/UnmodifiableMultivaluedMap.java
Logging your headers is much more effective when the map has a toString method!
> UnmodifiableMultivaluedMap: delegate toString

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientConfigurationImmutableSetsTest.java
> [RESTEASY-2402] ClientConfiguration.getClasses() and getInstances()

- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/Jackson2JsonpInterceptor.java
- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/WhiteListPolymorphicTypeValidatorBuilder.java
- resteasy-dependencies-bom/pom.xml
- security/jose-jwt/src/main/java/org/jboss/resteasy/jwt/JWTContextResolver.java
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/JaxRsActivator.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/TestRESTService.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/WhiteListPolymorphicTypeValidatorTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/model/AbstractVehicle.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/model/TestPolymorphicType.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/model/air/Aircraft.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/model/land/Automobile.java
Issue: https://issues.jboss.org/browse/RESTEASY-2411
Upstream PR: #2223
> [RESTEASY-2411] resteasy-jackson2-provider: default white-list based PolymorphicTypeValidator extension

- resteasy-spring-web/src/main/java/org/jboss/resteasy/spi/metadata/SpringResourceBuilder.java
- testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/TestController.java
See: https://github.com/quarkusio/quarkus/issues/5791
> [RESTEASY-2434] Prevent NPE on non spring-web-annotated methods

- resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
- resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
Just call `releaseConnection`, which will prevent connection leaks.
> RESTEASY-2457 Don't close the response upon an extraction error..

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
I agree on the Apache License 2.0 terms.
> [RESTEASY-2456]: JVM Heap leak fix.

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
resteasy.scan.providers, and resteasy.scan.resources in User Guide.
> [RESTEASY-2453] Deleted references to resteasy.scan,

- resteasy-core/pom.xml
- resteasy-dependencies-bom/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/microprofile-tck/pom.xml
I agree with the Apache License 2.0 terms.
> RESTEASY-2467 updated smallrye-config dependency from 1.3.9 to 1.5.1

- providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/AbstractJAXBProvider.java
Fixes https://issues.redhat.com/browse/RESTEASY-2489
> Handle NPE in AbstractJAXBProvider.findJAXBContext

- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/NOOPClientHelper.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/NOOPServerHelper.java
There's some new methods on ClientHelper and ServerHelper that I forgot to provide NOOPs for.
> Forgot some Client/ServerHelper NOOPS

- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentResource.java
[RESTEASY-2280]:PatchMethodFilter GET requires Consumes APPLICATION_JSON_PATCH_JSON
[RESTEASY-2496]:Add configuration parameter to disable PatchMethodFitler
> PR to fix https://issues.redhat.com/browse/RESTEASY-2280 & https://issues.redhat.com/browse/RESTEASY-2496

- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/CommonProviders.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ServerHelper.java
- server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/ContextResolverTest.java
- server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/DynamicFeatureTest.java
* Fixed a writer interceptor copy issue
* Fixed a contextresolver copy issue
> [RESTEASY-2487] Fix regression on TCK

- resteasy-core/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ServerWriterInterceptorContext.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseRawStreamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseRawStreamResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/SlowString.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/SlowStringWriter.java
Fix for bug noticed in Quarkus, as discussed by Zulip, email.
> Async io fixes

- resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientExtension.java
This is a fix for an issue in Quarkus (https://github.com/quarkusio/quarkus/pull/7639) that is currently  
temporarily fixed inside the Quarkus Extension (https://github.com/quarkusio/quarkus/pull/7639)
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>
> CDI BeanManager fix for Quarkus 

- providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyAbstractDataObject.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyDataObject.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyResourceIntf.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlySingletonResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatefulResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatelessResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyTestApplication.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/validation/NoFieldValidationEJBTest.java
> [RESTEASY-2503] Throw ViolationException for EJBs with just parameter

- providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ConstraintViolationExceptionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionDTO.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionResourceImpl.java
GeneralValidatorImpl.checkForConstraintViolations()
[RESTEASY-2522] Catch ConstraintViolationException in
GeneralValidatorImpl.checkForConstraintViolations()
[RESTEASY-2522] Add integration test.
> [RESTEASY-2522] Catch ConstraintViolationException in

- providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyAbstractDataObject.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyDataObject.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyResourceIntf.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlySingletonResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatefulResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatelessResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyTestApplication.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/validation/NoFieldValidationEJBTest.java
Issue: https://issues.redhat.com/browse/RESTEASY-2503
This is the cherry-pick of https://github.com/resteasy/Resteasy/pull/2324 into `3.6.1.SPx` branch for `EAP 7.2.z`
> [RESTEASY-2503] Throw ViolationException for EJBs with just parameter violations

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
This PR contains the change made in resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
by FroMage in a special test branch , see PR
https://github.com/resteasy/Resteasy/pull/2347
... In the PR 2347 FroMage wrote ....
So this bug is that we're calling SSEOutputStream.close() whose docs say "we close and if it's already closed then it's fine, you can keep closing it forever you will not get an exception", which is the right thing to do IMO.
But the implementation calls ResteasyAsynchronousResponse.complete(), which then forwards to a vertxFlush() which throws because it's already closed (by the client).
Now, perhaps the right thing to do is to ignore any IOException in SSEOutputStream.close() but I do wonder what the behaviour of …
> [RESTEASY-2542] ignore any IOException in SSEOutputStream.close()

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
- server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/SSETest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
As a consequence of https://github.com/resteasy/Resteasy/pull/2348
> [RESTEASY-2542] Restore tests

- providers/jaxb/pom.xml
- providers/resteasy-atom/pom.xml
- providers/resteasy-html/pom.xml
- resteasy-cdi/pom.xml
- resteasy-client-api/pom.xml
- resteasy-client-jetty/pom.xml
- resteasy-client-microprofile/pom.xml
- resteasy-client-vertx/pom.xml
- resteasy-client/pom.xml
- resteasy-core-spi/pom.xml
- resteasy-core/pom.xml
- resteasy-guice/pom.xml
- resteasy-jsapi/pom.xml
- resteasy-links/pom.xml
- resteasy-servlet-initializer/pom.xml
- resteasy-stats/pom.xml
- security/jose-jwt/pom.xml
- server-adapters/resteasy-jdk-http/pom.xml
- server-adapters/resteasy-netty4-cdi/pom.xml
- server-adapters/resteasy-netty4/pom.xml
- server-adapters/resteasy-undertow-spring/pom.xml
- server-adapters/resteasy-undertow/pom.xml
- server-adapters/resteasy-vertx/pom.xml
- testsuite/integration-tests-spring-web/pom.xml
- testsuite/integration-tests-spring/pom.xml
Jira requested only 2 module updates.   This pr updates all relevant modules
> [RESTEASY-2560] set scope for must junit dependencies to test

- resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
No test case to demonstrate jira's issue can be generated.  The original issue was found using resteasy in
conjunction with krazo.
> [RESTEASY-2391] changed code to use getMethod()

- resteasy-client/pom.xml
- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-2580
Variant for branch `3.12`
> [RESTEASY-2580] Remove duplicated dependencies in POMs

- resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeadersRequestFilter.java
- resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/utils/ClientRequestContextUtils.java
- resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/ClientHeadersFactoryCDITest.java
new static helper method:
ClientRequestContextUtils.getDeclaring(ClientRequestContext requestContext);
> [RESTEASY-2569]  RestClient does not propogate incoming headers

- resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
Additional ProxySelector.
see original smallrye code [here](https://github.com/smallrye/smallrye-rest-client/blob/master/implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java#L159)
> RESTEASY-2524

- .github/workflows/maven.yml
- resteasy-jaxrs/pom.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AbstractAsynchronousResponse.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/ContainerResponseContextImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/PreMatchContainerRequestContext.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SimpleProxyServer.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/AnotherPublisherResponseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseNoStreamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseRawStreamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseNoStreamResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseRawStreamResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseResource.java
This adds GitHub Actions for CI to the 3.12 branch. If this looks okay I can cherry-pick it to the 3.13 branch as well.
The second commit for the JavaDoc thing I'm not sure how to validate it still generates the expected JavaDoc. How are those usually built and distributed?
> Add GitHub Actions to 3.12

- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyUtil.java
- server-adapters/resteasy-netty4/src/test/java/org/jboss/resteasy/test/HeaderEmptyHostTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/HeaderEmptyHostTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/HeaderEmptyHostResource.java
https://issues.redhat.com/browse/RESTEASY-2300
> [RESTEASY-2300] Blank Host Name still throws exception

- resteasy-bom/pom.xml
This PR removed dependencies from the BOM that don't exist in the current version.
> Remove deps from the BOM that don't exist in the current version

- resteasy-core/src/main/java/org/jboss/resteasy/util/Encode.java
> Encode code points that span multiple characters

- .github/workflows/maven.yml
- .travis.yml
- testsuite/pom.xml
Use WFLY 20.0.1.Final for testing
> Update target containers

- pom.xml
- resteasy-dependencies-bom/pom.xml
- testsuite/README.MD
- testsuite/arquillian-utils/pom.xml
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForBootableJar.java
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cache/ServerCacheInterceptorTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorErrorTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/CryptoTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingDebugLoggingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
- testsuite/integration-tests/src/test/resources/arquillian-bootable.xml
- testsuite/pom.xml
Fixes https://issues.redhat.com/browse/RESTEASY-2694
> (3.13) Adding support for running test suite against bootable JAR

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/HeaderFlushedAsyncOutputStream.java
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/HeaderFlushedOutputStream.java
- resteasy-core/src/main/java/org/jboss/resteasy/util/WeightedLanguage.java
Small efficiency improvements for iterating through Map structure
https://issues.redhat.com/browse/RESTEASY-2724
> RESTEASY-2724 Small efficiency improvements for iterating through Map structure

- providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/IgnoredMediaTypes.java
Fix repeated check	on wildcard subtype against the same instance
https://issues.redhat.com/browse/RESTEASY-2722
> RESTEASY-2722 - Fix check on wildcard subtype

- docbook/reference/en/en-US/modules/WADL.xml
> RESTEASY-2739 - Update WADL section document

- resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/DynamicFeatureTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/AddDynamicFeature.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/AddFeature.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/DynamicFeatureResource.java
Issue: https://issues.redhat.com/browse/RESTEASY-2628
> [RESTEASY-2628] Review scope of properties/provider registered in a dynamic feature

- resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
Fixes https://issues.redhat.com/browse/RESTEASY-2731
> [RESTEASY-2731] Fix MessageBodyWriter resolving for HEAD requests

- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/HttpResponse.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
> (rebased)RESTEASY-1784 - Exception during chunked transfer is suppressed

- .gitignore
- resteasy-servlet-initializer/pom.xml
- resteasy-servlet-initializer/src/main/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializer.java
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializerTest.java
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/AppAndResource.java
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/AppWithAppPath.java
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/AppWithNoAppPath.java
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/Resource1.java
Also handle single class that is both an App and a resource class.
Resolves [RESTEASY-2650](https://issues.redhat.com/projects/RESTEASY/issues/RESTEASY-2650)
> RESTEASY-2650: Use web.xml servlets for app path

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/BaseServletConfigSource.java
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSource.java
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSourceImpl.java
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfigSource.java
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSource.java
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSourceImpl.java
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSource.java
- resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSourceImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceDefaultOrdinalFilterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceDefaultOrdinalServletContextListenerTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceDefaultOrdinalServletTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceOverrideOrdinalFilterTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceOverrideOrdinalServletContextListenerTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceOverrideOrdinalServletTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/MicroProfileConfigResource.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_default_ordinal_filter.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_default_ordinal_servlet.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_default_ordinal_servlet_context_listener.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_override_ordinal_filter.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_override_ordinal_servlet.xml
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_override_ordinal_servlet_context_listener.xml
Issue: https://issues.redhat.com/browse/RESTEASY-2624
> [RESTEASY-2624] Built in MicroProfile ConfigSource should let user override default ordinal

- resteasy-core/src/main/java/org/jboss/resteasy/util/TypeConverter.java
This change fixes a Java 2 Security issue that occurs when a security manager is installed when testing with Open Liberty.  The exception looks like this:
```
java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")java.base/java.security.AccessController.throwACE(AccessController.java:176)
java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
java.base/java.security.AccessController.checkPermission(AccessController.java:385)
java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:45)
java.base/java.lang.Class.checkMemberAccess(Class.java:247) …
```
> [RESTEASY-2804] DoPrivs for TypeConverter

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/mediatype/MediaTypeHeaderDelegateTest.java
> [RESTEASY-2812] Fix MediaType cache poisoning with trailing semi-colon

- resteasy-jaxrs/pom.xml
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfig.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfigProvider.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/ResteasyConfigResource.java
[RESTEASY-2805] Added uncommitted file.
> [RESTEASY-2805] Remove dependency on MicroProfile Config.

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfig.java
https://issues.redhat.com/browse/RESTEASY-2841
> [RESTEASY-2841] Attempt to load the API types before the implementation.

- resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusContainerResponseFilter.java
- resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusFeature.java
Fixes: https://github.com/quarkusio/quarkus/issues/16321
> Only set the status of response with @ResponseStatus if it's not already set

- resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
the delegating input stream is created.
https://issues.redhat.com/browse/RESTEASY-2868
This should be reviewed by someone that understands this better than I do. I think we want to do something along these lines though.
Also #2735 does need to be merged if this is merged.
> [RESTEASY-2868] Use a handler to pause the client response while

- resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
- resteasy-core/src/test/java/org/jboss/resteasy/core/ContextParameterInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/contextProxyInterfaces/ContextProxyInterfacesTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/contextProxyInterfaces/resource/CastableConfigurationResource.java
This PR resolves JIRA [RESTEASY-2866](https://issues.redhat.com/browse/RESTEASY-2866) by adding all implemented interfaces of the delegate class to the array of interfaces used when building the proxy class.
> [RESTEASY-2866] Ensure proxies implement all intfs

- .github/workflows/maven.yml
- pom.xml
- resteasy-dependencies-bom/pom.xml
This might actually fix CI. I've had 3 good runs so far.
> Attempt at fixing GitHub Actions CI

- .github/workflows/maven.yml
- resteasy-core/pom.xml
- resteasy-dependencies-bom/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/pom.xml
@ronsigal Here is a partial port of #2796. I did not include the Spring upgrade, however we can if you think we should.
> Component upgrades for 4.6

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/NewCookieHeaderDelegate.java
- resteasy-core/src/main/java/org/jboss/resteasy/util/ParameterParser.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/cookie/NewCookieHeaderDelegateTest.java
https://issues.redhat.com/browse/RESTEASY-2925
> [RESTEASY-2925]: Inconsitent NewCookie parsing when unknown attributes is found

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-2879
> [RESTEASY-2879] Upgrade Jackson to 2.12.3

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
https://issues.redhat.com/browse/RESTEASY-2872
> [RESTEASY-2872] Multipart annotation ignored when using async rest client

- resteasy-dependencies-bom/pom.xml
> Resolve version convergence issue with jboss-threads dependency

- resteasy-spring/src/main/java/org/jboss/resteasy/plugins/spring/ResteasyRegistration.java
- resteasy-spring/src/main/java/org/jboss/resteasy/plugins/spring/SpringBeanProcessor.java
This cleans up runtime warnings.
> [RESTEASY-2935] Replace Spring's deprecated @Required with @Autowired

- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/AsynchronousCdiTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/TimerInterceptorTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HeaderPropagator.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
- testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/webapplicationexception_web.xml
> Various Backports from main

- resteasy-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-2966
> [RESTEASY-2966] Add missing dependencies to the BOM.

- arquillian/RESTEASY-1056-jetty-bv11/pom.xml
- arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/pom.xml
- distribution/assembly.xml
- distribution/pom.xml
- profiling-tests/pom.xml
- providers/jackson2/pom.xml
- providers/jaxb/pom.xml
- providers/json-p-ee7/pom.xml
- providers/multipart/pom.xml
- providers/resteasy-html/pom.xml
- providers/resteasy-validator-provider/pom.xml
- resteasy-cache/resteasy-cache-core/pom.xml
- resteasy-cdi/pom.xml
- resteasy-core-spi/pom.xml
- resteasy-core/pom.xml
- resteasy-dependencies-bom/pom.xml
- resteasy-jsapi/pom.xml
- resteasy-links/pom.xml
- resteasy-servlet-initializer/pom.xml
- resteasy-stats/pom.xml
- resteasy-wadl-undertow-connector/pom.xml
- resteasy-wadl/pom.xml
- security/resteasy-crypto/pom.xml
- server-adapters/resteasy-netty4-cdi/pom.xml
- server-adapters/resteasy-reactor-netty/pom.xml
- server-adapters/resteasy-undertow/pom.xml
- server-adapters/resteasy-vertx/pom.xml
- testsuite/integration-tests-embedded/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/unit-tests/pom.xml
https://issues.redhat.com/browse/RESTEASY-2993
> [RESTEASY-2993] Migrate to the jakarta.* dependencies where we can.

- resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ViolationReport.java
https://issues.redhat.com/browse/RESTEASY-2914
Upstream #2810
> Fixing the ResteasyViolationException#toString concurrency 

- providers/multipart/pom.xml
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/HeaderFlushedOutputStream.java
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
- providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaroundTest.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
- resteasy-client/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43EngineTest.java
> [RESTEASY-2880] Config options for in-memory limit

- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/PriorityTest.java
https://issues.redhat.com/browse/RESTEASY-3016
> [RESTEASY-3016] Fix the PriorityTest by using the FakeHttpServer.

- resteasy-core/src/main/java/org/jboss/resteasy/util/NoContent.java
> [RESTEASY-3019] added trim string

- .github/workflows/maven.yml
- pom.xml
- testsuite/pom.xml
https://issues.redhat.com/browse/RESTEASY-3042
> [RESTEASY-3042] Upgrade WildFly Version to 25.0.1.Final.

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/test/StreamingOutputTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
Combined fix as the first commit seems to trigger the others failing more. Combining them just seemed correct.
Upstream #2968
> RESTEASY-3046 with other test fixes

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3067
> [RESTEASY-3067] Upgrade BouncyCastle to 1.70

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
https://issues.redhat.com/browse/RESTEASY-3072
> [RESTEASY-3072] Retrieving the output stream needs to be deferred.

- .github/workflows/maven.yml
- pom.xml
- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseBroadcasterImpl.java
- resteasy-dependencies-bom/pom.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/resource/StringBeanRuntimeDelegate.java
https://issues.redhat.com/browse/RESTEASY-3083
https://issues.redhat.com/browse/RESTEASY-3084
> Initial updates for Jakarta REST 3.1

- .github/workflows/maven.yml
- pom.xml
- resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/xxe/TestSecureProcessing.java
- security-legacy/pom.xml
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/AssumeUtils.java
- testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/SpringMvcHttpResponseCodesTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/CustomForbiddenMessageTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
- testsuite/microprofile-tck/pom.xml
- testsuite/pom.xml
https://issues.redhat.com/browse/RESTEASY-3082
> [RESTEASY-3082] Add Java SE 17 testing support.

- resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/PriorityServiceLoader.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/util/Functions.java
- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/PriorityServiceLoaderTestCase.java
- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/resources/NoEntriesInterface.java
- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/resources/TestImpl.java
- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/resources/TestImplFirst.java
- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/resources/TestImplLast.java
- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/resources/TestImplNoPriority.java
- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/resources/TestInterface.java
- resteasy-core-spi/src/test/resources/META-INF/services/org.jboss.resteasy.spi.resources.TestInterface
- resteasy-core-spi/src/test/resources/META-INF/services/org.jboss.resteasy.spi.resources.TestInterface$InnerInterface
https://issues.redhat.com/browse/RESTEASY-3090
> [RESTEASY-3090] Add a PriorityServiceLoader.

- resteasy-dependencies-bom/pom.xml
- resteasy-wadl-undertow-connector/pom.xml
- server-adapters/resteasy-undertow/pom.xml
https://issues.redhat.com/browse/RESTEASY-3093
> [RESTEASY-3093] Upgrade Undertow 2.2.14.Final

- testsuite/integration-tests/pom.xml
- testsuite/jakarta-rest-tck/README.adoc
- testsuite/jakarta-rest-tck/pom.xml
- testsuite/jakarta-rest-tck/src/main/java/dev/resteasy/tck/ResteasyApplicationArchiveProcessor.java
- testsuite/jakarta-rest-tck/src/main/java/dev/resteasy/tck/ResteasyLoadableExtension.java
- testsuite/jakarta-rest-tck/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
- testsuite/jakarta-rest-tck/src/main/resources/configure-wildfly.cli
- testsuite/jakarta-rest-tck/src/main/resources/jboss-web.xml
- testsuite/jakarta-rest-tck/src/test/resources/arquillian.xml
- testsuite/pom.xml
https://issues.redhat.com/browse/RESTEASY-3095
> [RESTEASY-3095] Add ability to run TCK test to the testsuite.

- resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/CacheInterceptor.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
- security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/doseta/DigitalVerificationInterceptor.java
Replaces #3029 
https://issues.redhat.com/browse/RESTEASY-3078
> [RESTEASY-3078] replace some getProperty calls to hasProperty

- docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
- pom.xml
- resteasy-client-utils/pom.xml
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/AuthorizationProcessor.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/HttpAuthenticators.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/HttpAuthorizationFilter.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/UserCredentials.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/basic/BasicAuthorizationProcessor.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/digest/Algorithm.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/digest/DigestAuthorizationProcessor.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/digest/DigestHashBuilder.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/authentication/digest/DigestScheme.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/common/ByteStringBuilder.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/common/Bytes.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/common/LimitMap.java
- resteasy-client-utils/src/main/java/dev/resteasy/client/util/logging/ClientMessages.java
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/AbstractDigestAuthenticationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/AuthenticationSetupTask.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/BasicAuthenticationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/Digest256AuthenticationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/Digest512256AuthenticationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/DigestAuthenticationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/MultipleAuthenticationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/RestActivator.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/TestAuth.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/authentication/UserResource.java
Add Basic and Digest authentication methods for client requests.
https://issues.redhat.com/browse/RESTEASY-2856
> [RESTEASY-2856] Add a new module for client utilities.

- testsuite/jakarta-rest-tck/pom.xml
> Update the signature tests class path and get signature tests working.

- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/test/StreamingOutputTest.java
> Re-enable the StreamingOutputTest.

- providers/multipart/pom.xml
- resteasy-core/pom.xml
- resteasy-dependencies-bom/pom.xml
- security/resteasy-crypto/pom.xml
- testsuite/unit-tests/pom.xml
Includes:
* https://issues.redhat.com/browse/RESTEASY-3101
* https://issues.redhat.com/browse/RESTEASY-3102
> Jakarta component upgrades

- resteasy-cdi/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-netty4-cdi/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/extensions/resource/CDIExtensionsBostonBean.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/resource/SessionBeanInterfaceMockBean.java
https://issues.redhat.com/browse/RESTEASY-3119
> [RESTEASY-3119] Upgrade CDI to 4.0 and Weld to 5.0

- resteasy-client-vertx/pom.xml
- resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
- resteasy-client-vertx/src/test/java/org/jboss/resteasy/test/client/vertx/VertxClientEngineTest.java
- resteasy-client-vertx/src/test/java/org/jboss/resteasy/test/client/vertx/VertxSslClientEngineTest.java
* https://issues.redhat.com/browse/RESTEASY-3120
* https://issues.redhat.com/browse/RESTEASY-3121
> Fixes for RESTEasy Vert.x Client

- resteasy-client-vertx/pom.xml
- resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
- resteasy-client-vertx/src/test/java/org/jboss/resteasy/test/client/vertx/VertxClientEngineTest.java
- resteasy-client-vertx/src/test/java/org/jboss/resteasy/test/client/vertx/VertxSslClientEngineTest.java
* https://issues.redhat.com/browse/RESTEASY-3120
* https://issues.redhat.com/browse/RESTEASY-3121
Upstream: #3075
> Fixes for RESTEasy Vert.x Client 

- providers/json-binding/pom.xml
- providers/json-p-ee7/pom.xml
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-vertx/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/JaxbXmlRootElementProviderTest.java
* https://issues.redhat.com/browse/RESTEASY-3103
* https://issues.redhat.com/browse/RESTEASY-3104
> Upgrade Jakarta JSON Processing and Jakarta JSON BInding

- resteasy-dependencies-bom/pom.xml
* https://issues.redhat.com/browse/RESTEASY-3130
* https://issues.redhat.com/browse/RESTEASY-3133
> Weld and Yasson Upgrades

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/microprofile/config/BaseServletConfigSource.java
https://issues.redhat.com/browse/RESTEASY-3134
Signed-off-by: Tobias Stadler <ts.stadler@gmx.de>
> [RESTEASY-3134] Do not cause a NPE when source is not available

- arquillian/pom.xml
- pom.xml
- testsuite/pom.xml
https://issues.redhat.com/browse/RESTEASY-3136
> [RESTEASY-3136] Add JVM arguments for XNIO-404/JDK-8285445 on Windows.

- galleon-feature-pack/src/main/resources/modules/system/layers/base/org/apache/james/mime4j/main/module.xml
- galleon-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-client/main/module.xml
- galleon-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-json-binding-provider/main/module.xml
- providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
- providers/multipart/pom.xml
- resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
- resteasy-client/pom.xml
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/EntityOutputStream.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/test/StreamingOutputTest.java
- server-adapters/resteasy-undertow/src/test/java/org/jboss/resteasy/test/undertow/AsyncIOResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/EntityBufferingInFileTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/InputStreamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/datasource/DataSourceProviderInputStreamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/datasource/ReadFromSocketDataSourceProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ResponseStreamPrematurelyClosedTest.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/NoContentStreamingCloseTest.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/multipart/Base64EncoderMultiPartTest.java
https://issues.redhat.com/browse/RESTEASY-3138
https://issues.redhat.com/browse/RESTEASY-3139
> [RESTEASY-3138] Remove dependency on commons-io.

- jboss-modules/build.xml
- jboss-modules/pom.xml
- pom.xml
- resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientDelegateBean.java
- testsuite/pom.xml
* https://issues.redhat.com/browse/RESTEASY-3144
* https://issues.redhat.com/browse/RESTEASY-3136
> Back port fixes 3.15

- resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/ProxyInvocationHandler.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
https://issues.redhat.com/browse/RESTEASY-3123
> [RESTEASY-3123] ParamConverterProvider NullPointerException on methods with no params

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3122
> [RESTEASY-3122] Upgrade Yasson to 3.0.0.

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
Issue: https://issues.redhat.com/browse/RESTEASY-3141
> Spelling mistake in ReverseInjectionTest.testMDB

- resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
https://issues.redhat.com/browse/RESTEASY-3089
> [RESTEASY-3089] ContainerResponseFilter will not allow null entities to be set

- resteasy-client-reactor-netty/pom.xml
- resteasy-client-vertx/pom.xml
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-netty4-cdi/pom.xml
- server-adapters/resteasy-netty4/pom.xml
- server-adapters/resteasy-reactor-netty/pom.xml
- server-adapters/resteasy-vertx/pom.xml
* https://issues.redhat.com/browse/RESTEASY-3158
* https://issues.redhat.com/browse/RESTEASY-3159
* https://issues.redhat.com/browse/RESTEASY-3160
> [4.7] Component upgrades

- resteasy-client-reactor-netty/pom.xml
- resteasy-client-vertx/pom.xml
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-netty4-cdi/pom.xml
- server-adapters/resteasy-netty4/pom.xml
- server-adapters/resteasy-reactor-netty/pom.xml
- server-adapters/resteasy-vertx/pom.xml
* https://issues.redhat.com/browse/RESTEASY-3157
* https://issues.redhat.com/browse/RESTEASY-3159
* https://issues.redhat.com/browse/RESTEASY-3160
> Component upgrades

- resteasy-client-reactor-netty/pom.xml
- resteasy-client-vertx/pom.xml
- resteasy-dependencies-bom/pom.xml
- resteasy-wadl-undertow-connector/pom.xml
- server-adapters/resteasy-netty4-cdi/pom.xml
- server-adapters/resteasy-netty4/pom.xml
- server-adapters/resteasy-reactor-netty/pom.xml
- server-adapters/resteasy-undertow/pom.xml
- server-adapters/resteasy-vertx/pom.xml
* https://issues.redhat.com/browse/RESTEASY-3156
* https://issues.redhat.com/browse/RESTEASY-3159
* https://issues.redhat.com/browse/RESTEASY-3160
> Component upgrades 6.0

- resteasy-client-reactor-netty/pom.xml
- resteasy-client-vertx/pom.xml
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-netty4-cdi/pom.xml
- server-adapters/resteasy-netty4/pom.xml
- server-adapters/resteasy-reactor-netty/pom.xml
- server-adapters/resteasy-vertx/pom.xml
* https://issues.redhat.com/browse/RESTEASY-3156
* https://issues.redhat.com/browse/RESTEASY-3159
* https://issues.redhat.com/browse/RESTEASY-3160
This replaces #3117
> Component upgrades 5.0

- config/eclipse/resteasy-template.xml
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/AsyncWriterInterceptor.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/AsyncWriterInterceptorContext.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
https://issues.redhat.com/browse/RESTEASY-3161
> [RESTEASY-3161] Use the ASLv2 license.

- resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
> [RESTEASY-3155] Concurrency issues in ResteasyViolationException

- resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java
https://issues.redhat.com/browse/RESTEASY-3154
> [RESTEASY-3154] Use a static cache of known locales and MediaTypes.

- .github/workflows/maven.yml
- pom.xml
https://issues.redhat.com/browse/RESTEASY-3171
> [RESTEASY-3171] Upgrade WildFly to 27.0.0.Alpha3.

- resteasy-dependencies-bom/pom.xml
- resteasy-reactor/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/OutOfBandResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/resource/CDIValidationSessionBeanResource.java
* https://issues.redhat.com/browse/RESTEASY-3185
* https://issues.redhat.com/browse/RESTEASY-3186
> [RESTEASY-3185 & RESTEASY-3186] Remove dependencies

- resteasy-dependencies-bom/pom.xml
* https://issues.redhat.com/browse/RESTEASY-3187
* https://issues.redhat.com/browse/RESTEASY-3188
* https://issues.redhat.com/browse/RESTEASY-3189
* https://issues.redhat.com/browse/RESTEASY-3190
* https://issues.redhat.com/browse/RESTEASY-3192
* https://issues.redhat.com/browse/RESTEASY-3193
* https://issues.redhat.com/browse/RESTEASY-3194
* https://issues.redhat.com/browse/RESTEASY-3195
* https://issues.redhat.com/browse/RESTEASY-3196
* https://issues.redhat.com/browse/RESTEASY-3197
* https://issues.redhat.com/browse/RESTEASY-3198
* https://issues.redhat.com/browse/RESTEASY-3199
* https://issues.redhat.com/browse/RESTEASY-3200
* https://issues.redhat.com/browse/RESTEASY-3201
> Several Component Upgrades

- resteasy-dependencies-bom/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationJaxbTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationXMLTest.java
https://issues.redhat.com/browse/RESTEASY-3202
> [RESTEASY-3202] Remove dependency on rest assured.

- docbook/reference/en/en-US/modules/tracing.xml
https://issues.redhat.com/browse/RESTEASY-3207
> RESTEASY-3207 - Write the document about ON_DEMAND tracing mode usage

- pom.xml
https://issues.redhat.com/browse/RESTEASY-3208
> [RESTEASY-3208] Upgrade Galleon Plugins to 6.0.0.Beta1.

- galleon-feature-pack/pom.xml
- galleon-feature-pack/src/main/resources/modules/system/layers/base/com/fasterxml/jackson/jakarta/jackson-jakarta-json-provider/main/module.xml
- galleon-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/resteasy/jose-jwt/main/module.xml
- galleon-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jackson2-provider/main/module.xml
- providers/jackson2/pom.xml
- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
- providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyObjectWriterInjector.java
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/BasicSSLTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/BasicTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/CleanUpTasksTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/JsonFilterModifierConditionalWriterInterceptor.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/JsonFilterModifierMultipleWriteInterceptor.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/JsonFilterWriteInterceptor.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectFilterModifier.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectFilterModifierConditional.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectFilterModifierMultiple.java
https://issues.redhat.com/browse/RESTEASY-3085
> [RESTEASY-3085] Upgrade Jackson to 2.13.

- .github/workflows/maven.yml
- pom.xml
https://issues.redhat.com/browse/RESTEASY-3219
> [RESTEASY-3219] Upgrade testing to use WildFly 27.0.0.Alpha5.

- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ContextProducers.java
- server-adapters/resteasy-undertow-cdi/src/test/java/dev/resteasy/embedded/server/ContextInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/RequiredInjectableContextTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/resource/RequiredInjectableContextResource.java
https://issues.redhat.com/browse/RESTEASY-3224
> [RESTEASY-3224] Allow the ResourceInfo to be injected via CDI.

- server-adapters/resteasy-netty4/pom.xml
- server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
Upstream #3236
https://issues.redhat.com/browse/RESTEASY-2693
> [RESTEASY-2693] remove use of a thread group from NettyJaxrsServer

- .github/workflows/wildfly-build.yml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
https://issues.redhat.com/browse/RESTEASY-3228
> [RESTEASY-3228] Re-enable previously ignored test by mistake and add additional runs to the WildFly build and test

- testsuite/pom.xml
> Remove the shibboleth.net maven repository.

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3242
> [RESTEASY-3242] Upgrade Jackson databind to 2.13.4.1.

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/ResteasyEntityPartBuilder.java
Signed-off-by: jim-krueger <jckofbyron@gmail.com>
> [3258] Add default mediaType for EntityParts

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyPathParamRegexTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ProxyPathParamRegexResource.java
https://issues.redhat.com/browse/RESTEASY-2845
Upstream #2754
> [RESTEASY-2845] ResteasyWebTarget.proxy(Class) problem with questionmark in @Path with Regex 

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientRequestHeaders.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/servlet/ServletConfigTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/UserDefinedHeaderParamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/UserDefinedHeaderParamResource.java
https://issues.redhat.com/browse/RESTEASY-2874
> [RESTEASY-2874] Web Target Proxy not overriding content type header

- .github/workflows/maven.yml
- pom.xml
https://issues.redhat.com/browse/RESTEASY-3270
> [RESTEASY-3270] Upgrade WildFly to 27.0.1.Final.

- providers/yaml/src/main/java/org/jboss/resteasy/plugins/providers/YamlProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/BadActorYamlProviderTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/AttackVector.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/MessageResource.java
https://issues.redhat.com/browse/RESTEASY-3260
Replaces #3372 and follows up on #3362
> [RESTEASY-3260] Harden the checks to an allow list only

- galleon-feature-pack/src/main/resources/modules/system/layers/base/org/apache/james/mime4j/main/module.xml
- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3274
> [RESTEAST-3274] Upgrade mime4j to 0.8.9.

- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/DataSourceProvider.java
- resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
- server-adapters/resteasy-undertow/src/test/java/org/jboss/resteasy/test/undertow/UndertowTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/XOPMultipartProxyTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/RangeResource.java
https://issues.redhat.com/browse/RESTEASY-3286
Upstream #3409
> [RESTEASY-3286] Use the new NIO file utilities to create temporary files

- docbook/reference/en/en-US/modules/ExceptionMappers.xml
- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/DefaultOptionsMethodException.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/registry/ConstantResourceInvoker.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DataSourceProvider.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/SegmentTest.java
* https://issues.redhat.com/browse/RESTEASY-3283
* https://issues.redhat.com/browse/RESTEASY-3286
> [5.0] Back ported fixes

- docbook/reference/en/en-US/modules/ExceptionMappers.xml
- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- jboss-modules/src/main/resources/modules/org/apache/james/mime4j/main/module.xml
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataOutput.java
- providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataOutputTest.java
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/Utils.java
- resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
- resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientRequestHeaders.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/DefaultOptionsMethodException.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/registry/ConstantResourceInvoker.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DataSourceProvider.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
- resteasy-dependencies-bom/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/cdi/AbstractRegistrationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/cdi/DynamicFeatureContextInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/cdi/FeatureContextInjectionTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/cdi/resources/ContextAndInjectionFilter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/cdi/resources/TestBean.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyPathParamRegexTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ProxyPathParamRegexResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/servlet/ServletConfigTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/UserDefinedHeaderParamTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/UserDefinedHeaderParamResource.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/SegmentTest.java
* https://issues.redhat.com/browse/RESTEASY-3286
* https://issues.redhat.com/browse/RESTEASY-2874
* https://issues.redhat.com/browse/RESTEASY-3256
* https://issues.redhat.com/browse/RESTEASY-2845
* https://issues.redhat.com/browse/RESTEASY-3217
* https://issues.redhat.com/browse/RESTEASY-3177
* https://issues.redhat.com/browse/RESTEASY-3283
* https://issues.redhat.com/browse/RESTEASY-3253
> [4.7] Back ported fixes

- pom.xml
- resteasy-dependencies-bom/pom.xml
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilSpring.java
- testsuite/integration-tests-spring-web/pom.xml
- testsuite/integration-tests-spring/pom.xml
https://issues.redhat.com/browse/RESTEASY-3287
> [RESTEASY-3287] Upgrade Spring to 5.3.25

- docbook/reference/en/en-US/modules/Jakarta_Se_Bootstrap.xml
- pom.xml
- resteasy-core/pom.xml
- resteasy-core/src/main/java/org/jboss/resteasy/core/scanner/ResourceScanner.java
- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3245
> [RESTEASY-3245] Migrate to SmallRye Jandex.

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
https://issues.redhat.com/browse/RESTEASY-3290
> [RESTEASY-3290] Avoid an NPE if the temporary directory is null.

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3295
> [RESTEASY-3295] Upgrade Jackson to 2.14.2.

- .github/workflows/maven.yml
- pom.xml
> Upgrade WildFly from 27 to 28.

- resteasy-dependencies-bom/pom.xml
- resteasy-wadl-undertow-connector/pom.xml
- server-adapters/resteasy-undertow-cdi/pom.xml
- server-adapters/resteasy-undertow-cdi/src/test/resources/logging.properties
- server-adapters/resteasy-undertow/pom.xml
https://issues.redhat.com/browse/RESTEASY-3323
> [RESTEASY-3323] Upgrade Undertow to 2.3.4.Final and Servlet to 6.0

- pom.xml
- resteasy-dependencies-bom/pom.xml
* #3598
* #3599
* #3603
* #3614
* #3615
> Combined component upgrades

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/ClientConfigProviderBearerTokenTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/ClientConfigProviderTestJarHelper.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithCorrectCertificateTest.java
Jira issue link https://issues.redhat.com/browse/RESTEASY-2992
> [RESTEASY-2992] Fix the ClientConfigProviderTestJarHelper to work on Windows

- jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-multipart-provider/main/module.xml
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4jWorkaroundBinaryEntityBuilder.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MultipartBinaryFormatTest.java
https://issues.redhat.com/browse/RESTEASY-3341
> [RESTEASY-3341] Ensure multipart data responses are written in binary.

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/PKCS7SignatureSmokeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/VerifyDecryptTest.java
https://issues.redhat.com/browse/RESTEASY-3344
> [RESTEASY-3344] Workaround a permission issue with BouncyCastle.

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3350
https://issues.redhat.com/browse/RESTEASY-3351
Replaces: #3680 and #3677
> Upgrade Netty and Vert.x

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3352
> [RESTEASY-3352] Upgrade the Jakarta XML Binding implementation to 2.3.8.

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3353
> [RESTEASY-3353] Upgrade Guava to 32.1.1.

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
When calling `close` on `SseEventSink`, it is possible to miss events that are still in the queue, because they are still waiting on output completion before being drained. Currently, the `close` method clears all events from the queue.
The proposal is to just call `drainQueue` instead of clearing the events on a close with flush.
> [RESTEASY-3358] Drain SseEventSink queue on close with flush

- resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
- resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
The JAX-RS API does not use checked exceptions, so it's important to covert to `ProcessingException` early so that callers have reliable exception behavior.  For example, IOExceptions are propagated as the causes of many ProcessingExceptions and callers may want to retry these.
> Reactor-Netty client: Make sure most exceptions are ProcessingExceptions

- resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
- resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
The JAX-RS API does not use checked exceptions, so it's important to early on do the conversion to ProcessingException because that's what client's of the JAX-RS API have to catch in order to look for IOExceptions (in the cause) that they may want to retry.
6.2 version of #3673
https://issues.redhat.com/browse/RESTEASY-3349
> Reactor-Netty client: Make sure most exceptions are ProcessingExceptions.

- resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
- resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
The JAX-RS API does not use checked exceptions, so it's important to early on do the conversion to `ProcessingException` because that's what client's of the JAX-RS API have to catch in order to look for IOExceptions (in the cause) that they may want to retry.
Merged #3673 already
> Make sure most exceptions are ProcessingExceptions.

- resteasy-core-spi/src/main/java/org/jboss/resteasy/annotations/Separator.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/SeparatorAnnotationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/SeparatorAnnotationAsFieldTargetEndPoint.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/SeparatorAnnotationAsMethodTargetEndPoint.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/SeparatorAnnotationAsParameterTargetEndPoint.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/resource/SeparatorAnnotationBeanParam.java
https://issues.redhat.com/browse/RESTEASY-3029
> [RESTEASY-3029] Allow @Separator annotation at fields and methods

- resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientEngine.java
- resteasy-client-jetty/src/test/java/org/jboss/resteasy/test/client/jetty/JettyClientEngineTest.java
(Not sure if this simple change needs a ticket so I directly opened the PR)
Right now a caller can set the request timeout on a per-request basis. This PR adds the similar ability for the idle timeout.
> Support per-request idle timeout

- .github/workflows/maven.yml
- pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/PKCS7SignatureSmokeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/VerifyDecryptTest.java
> Upgrade WildFly testing to 29.0.0.Final.

- pom.xml
- resteasy-dependencies-bom/pom.xml
Includes:
- #3748
- #3749
- #3751
- #3752
- #3762
> [6.2] Grouped Component Upgrades

- .github/workflows/wildfly-build.yml
- docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
- pom.xml
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ContextProducers.java
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ResteasyCdiExtension.java
- resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/AbstractCollectionProcessor.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseBroadcasterImpl.java
- resteasy-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-jaxb-provider/main/module.xml
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/AssumeUtils.java
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/ExternalParameterEntityTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/XxeJaxbTest.java
- testsuite/pom.xml
- [RESTEASY-3369](https://issues.redhat.com/browse/RESTEASY-3369): #3766
- [RESTEASY-3368](https://issues.redhat.com/browse/RESTEASY-3368): #3747
- [RESTEASY-3365](https://issues.redhat.com/browse/RESTEASY-3365): #3728
- [RESTEASY-3362](https://issues.redhat.com/browse/RESTEASY-3362): #3736
- [RESTEASY-3324](https://issues.redhat.com/browse/RESTEASY-3324): #3710
> [6.2] Back ported PR's

- pom.xml
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/AbstractCollectionProcessor.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseBroadcasterImpl.java
- resteasy-dependencies-bom/pom.xml
Includes:
- #3761 
- #3764 
- [RESTEASY-3365](https://issues.redhat.com/browse/RESTEASY-3365): #3728
- [RESTEASY-3369](https://issues.redhat.com/browse/RESTEASY-3369): #3766
> [5.0] Back ports and component upgrades

- resteasy-cdi/pom.xml
- resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/CdiPropertyInjector.java
https://issues.redhat.com/browse/RESTEASY-3382
> [RESTEASY-3382] Remove the required Weld dependency on resteasy-cdi.

- resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java
https://issues.redhat.com/browse/RESTEASY-2612
Upstream: #2727
> [RESTEASY-2612] Support CompletableFuture resource method return type

- .github/workflows/maven.yml
- pom.xml
- testsuite/cloud-tests/client-tests/pom.xml
- testsuite/cloud-tests/client-tests/src/main/java/dev/resteasy/cloud/tests/client/EchoResource.java
- testsuite/cloud-tests/client-tests/src/main/java/dev/resteasy/cloud/tests/client/RestActivator.java
- testsuite/cloud-tests/client-tests/src/test/java/dev/resteasy/cloud/tests/client/EchoIT.java
- testsuite/cloud-tests/images/cloud-server/pom.xml
- testsuite/cloud-tests/images/pom.xml
- testsuite/cloud-tests/pom.xml
- testsuite/pom.xml
- testsuite/test-utils/pom.xml
- testsuite/test-utils/src/main/java/dev/resteasy/cloud/tests/RestClientValueInjector.java
- testsuite/test-utils/src/main/resources/META-INF/services/org.wildfly.test.cloud.common.ValueInjector
https://issues.redhat.com/browse/RESTEASY-3386
> [RESTEASY-3386] Add cloud tests for Kubernetes.

- profiling-tests/pom.xml
- profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/MockedProfilingTest.java
- profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/ProfilingTest.java
https://issues.redhat.com/browse/RESTEASY-3405
> [RESTEASY-3405] Migrate the profiling-tests module to JUnit 5

- resteasy-jsapi/pom.xml
- resteasy-jsapi/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
- resteasy-jsapi/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
https://issues.redhat.com/browse/RESTEASY-3406
> [RESTEASY-3406] Migrate the resteasy-jsapi module to JUnit 5

- resteasy-servlet-initializer/pom.xml
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializerTest.java
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
- resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
https://issues.redhat.com/browse/RESTEASY-3416
> [RESTEASY-3416] Migrate the resteasy-servlet-initializer module to JUnit 5

- resteasy-wadl/pom.xml
- resteasy-wadl/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
- resteasy-wadl/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
- resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestWadlFunctions.java
- resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLNettyContainerTest.java
- resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLTestExistenceVerifier.java
- resteasy-wadl/src/test/java/org/jboss/resteasy/wadl/wadl/TestWADL_JAXB_Types.java
https://issues.redhat.com/browse/RESTEASY-3417
> [RESTEASY-3417] Migrate the resteasy-wadl module to JUnit 5

- security/resteasy-crypto/pom.xml
- security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
- security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
- security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/security/doseta/EagleDnsTest.java
- security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/security/doseta/SigningDnsTest.java
- security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/security/doseta/SigningTest.java
https://issues.redhat.com/browse/RESTEASY-3420
> [RESTEASY-3420] Migrate the resteasy-security-crypto module to JUnit 5

- resteasy-links/pom.xml
- resteasy-links/src/test/java/org/jboss/resteasy/links/impl/TestLinksInjector.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookClassProvider.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/SecureBookClassProvider.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestClassLinksProvider.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestFacadeLinks.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestLinkIds.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestLinks.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestSecureLinks.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/TestLinksInvalidEL.java
- resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/TestLinksNoPackage.java
- resteasy-links/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
- resteasy-links/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
https://issues.redhat.com/browse/RESTEASY-3412
> [RESTEASY-3412] Migrate the resteasy-links module to JUnit 5

- resteasy-client-reactor-netty/pom.xml
https://issues.redhat.com/browse/RESTEASY-3391
> [RESTEASY-3391] Remove unneeded JUnit dependency.

- resteasy-core-spi/src/main/java/org/jboss/resteasy/annotations/cache/Cache.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/CacheControlFeature.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/CacheControlAnnotationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/CacheAnnotationInheritance.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/CacheControlAnnotationResourceInheritance.java
https://issues.redhat.com/browse/RESTEASY-3111
> [RESTEASY-3111] Properly inherit @Cache annotation for base class.

- resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/QueryParamAsPrimitiveTest.java
https://issues.redhat.com/browse/RESTEASY-3304
> [Resteasy 3304] Return null upon missing value of request parameter

- resteasy-core-spi/src/main/java/org/jboss/resteasy/annotations/cache/Cache.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/CacheControlFeature.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/InputStreamProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/InputStreamResourceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/CacheControlAnnotationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/CacheAnnotationInheritance.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/CacheControlAnnotationResourceInheritance.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/QueryParamAsPrimitiveTest.java
- https://issues.redhat.com/browse/RESTEASY-3111
- https://issues.redhat.com/browse/RESTEASY-3304
- https://issues.redhat.com/browse/RESTEASY-3436
> Back port fixes to 6.2

- resteasy-core-spi/src/main/java/org/jboss/resteasy/annotations/cache/Cache.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/CacheControlFeature.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/InputStreamProvider.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/InputStreamResourceTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/CacheControlAnnotationTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/CacheAnnotationInheritance.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/CacheControlAnnotationResourceInheritance.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/QueryParamAsPrimitiveTest.java
- https://issues.redhat.com/browse/RESTEASY-3111
- https://issues.redhat.com/browse/RESTEASY-3304
- https://issues.redhat.com/browse/RESTEASY-3436
> Back port fixes to 5.0

- providers/multipart/pom.xml
- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartEntityPartWriter.java
- providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/MultipartEntityPartProviderTest.java
https://issues.redhat.com/browse/RESTEASY-3445
Upstream: #4011 #4013
> [RESTEASY-3445] Correctly add headers to output

- resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/RoleBasedSecurityFilter.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
https://issues.redhat.com/browse/RESTEASY-3205
> [RESTEASY-3205] Change Content-Type to text/plain for Security filter

- resteasy-core-spi/src/test/java/org/jboss/resteasy/spi/config/SizeUnitTestCase.java
https://issues.redhat.com/browse/RESTEASY-3449
Upstream #4042
> [RESTEASY-3449] Allow the SizeUnitTestCase to pass in all locales.

- pom.xml
> Upgrade WildFly testing to the latest version.

- pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/ContainerConstants.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAbstractTestBase.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAllowGzipOnClientTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerNotAllowGzipOnClientTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTestBase.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAbstractTestBase.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/resource/GzipResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultMediaTypeTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithCorrectCertificateTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWildcardHostnameCertificateTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWrongHostnameCertificateTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithoutCertificateTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslSniHostNamesTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslTestBase.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/BasicTracingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/JsonFormattedTracingInfoTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/OnDemandTracingTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingTestBase.java
- testsuite/integration-tests/src/test/resources/arquillian.xml
- testsuite/integration-tests/src/test/resources/logging.properties
- testsuite/pom.xml
https://issues.redhat.com/browse/RESTEASY-3451
This removes the need for any manual mode tests and uses setup tasks, if required, to configure the server.
> [RESTEASY-3451] Enable disabled tests due to manual mode test issues

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3467
> [RESTEASY-3467] Upgrade mime4j to 0.8.11.

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataInputImpl.java
https://issues.redhat.com/browse/RESTEASY-3465
> [RESTEASY-3465] Use an FIFO map for the form data.

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ClientHttpEngineBuilder43.java
https://issues.redhat.com/browse/RESTEASY-3470
> [RESTEASY-3470] Ensure idle connections are evicted.

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/EntityPartFilter.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/config/DefaultConfiguration.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletBootstrap.java
Normally two different commits like this would not be in the same PR. However, to get CI running for both this needs to be done this way.
- https://issues.redhat.com/browse/RESTEASY-3484
- https://issues.redhat.com/browse/RESTEASY-3486
> RESTEASY-3484 and  RESTEASY-3486

- providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/EntityPartFilter.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/config/DefaultConfiguration.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletBootstrap.java
Normally two different commits like this would not be in the same PR. However, to get CI running for both this needs to be done this way.
- https://issues.redhat.com/browse/RESTEASY-3484
- https://issues.redhat.com/browse/RESTEASY-3486
Upstream #4116
> RESTEASY-3484 and RESTEASY-3486 

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientProxy.java
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ClientProxyDefaultMethodTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/smoke/resource/ResourceWithInterfaceSimpleClient.java
https://issues.redhat.com/browse/RESTEASY-3490
@stevenschlansker does this seems okay to you?
> [RESTEASY-3490] Allow default methods on proxy clients to be used

- docbook/reference/en/en-US/modules/Installation_Configuration.xml
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/DelegateResteasyDeployment.java
- resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
- resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
- resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/DisabledProvidersTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resources/DisabledProvidersApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resources/DisabledProvidersResource.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resources/SimpleText.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resources/SimpleTextReaderWriter.java
Port of #2270
- https://issues.redhat.com/browse/RESTEASY-3496
- https://issues.redhat.com/browse/RESTEASY-3501
> [RESTEASY-3496] Add support for the resteasy.disable.providers configuration property

- resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
- resteasy-dependencies-bom/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/RESTEASY3109Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseCallbackTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseCallbackResource.java
- https://issues.redhat.com/browse/RESTEASY-2952
- https://issues.redhat.com/browse/RESTEASY-3498
Upstream #4154
> [RESTEASY-2952 & RESTEASY-3498] Clean up the SSE callback processing

- resteasy-dependencies-bom/pom.xml
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/resource/SessionBeanInterfaceMockProcessSessionBean.java
https://issues.redhat.com/browse/RESTEASY-3478
> [RESTEASY-3478] Upgrade Jakarta CDI to 4.1.0 and Weld to 6.0.

- resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
https://issues.redhat.com/browse/RESTEASY-3507
> [RESTEASY-3507] Cast the created application object instead of the type.

- resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java
- testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/mapper/ExceptionHandlerTest.java
https://issues.redhat.com/browse/RESTEASY-3500
> [RESTEASY-3500] The ExceptionHandler sets the media type of an except ion to text/html

- providers/json-binding/pom.xml
- providers/json-binding/src/test/java/org/jboss/resteasy/plugins/providers/jsonb/EntityTest.java
- providers/multipart/pom.xml
- providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/MultipartEntityPartProviderTest.java
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/AbstractBasicTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/BasicSSLTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/BasicTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/CleanUpTasksTest.java
- server-adapters/resteasy-undertow-cdi/pom.xml
- server-adapters/resteasy-undertow-cdi/src/test/java/dev/resteasy/embedded/server/ContextInjectionTest.java
- server-adapters/resteasy-undertow-cdi/src/test/java/dev/resteasy/embedded/server/InjectionTest.java
- server-adapters/resteasy-undertow-cdi/src/test/java/dev/resteasy/embedded/server/ServletTest.java
- testsuite/integration-tests-embedded/pom.xml
- testsuite/integration-tests-embedded/src/test/java/org/jboss/resteasy/embedded/test/core/validate/NonCDIValidatorFactoryTest.java
- testsuite/integration-tests-embedded/src/test/java/org/jboss/resteasy/embedded/test/interceptor/PriorityExecutionTest.java
https://issues.redhat.com/browse/RESTEASY-3533
Upstream #4279
> [RESTEASY-3533] Incorporate usages of the resteasy-junit-extension

- providers/json-binding/pom.xml
- providers/json-binding/src/test/java/org/jboss/resteasy/plugins/providers/jsonb/EntityTest.java
- providers/multipart/pom.xml
- providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/MultipartEntityPartProviderTest.java
- resteasy-dependencies-bom/pom.xml
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/AbstractBasicTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/BasicSSLTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/BasicTest.java
- server-adapters/resteasy-reactor-netty/src/test/java/org/jboss/resteasy/plugins/server/reactor/netty/CleanUpTasksTest.java
- server-adapters/resteasy-undertow-cdi/pom.xml
- server-adapters/resteasy-undertow-cdi/src/test/java/dev/resteasy/embedded/server/ContextInjectionTest.java
- server-adapters/resteasy-undertow-cdi/src/test/java/dev/resteasy/embedded/server/InjectionTest.java
- server-adapters/resteasy-undertow-cdi/src/test/java/dev/resteasy/embedded/server/ServletTest.java
- testsuite/integration-tests-embedded/pom.xml
- testsuite/integration-tests-embedded/src/test/java/org/jboss/resteasy/embedded/test/core/validate/NonCDIValidatorFactoryTest.java
- testsuite/integration-tests-embedded/src/test/java/org/jboss/resteasy/embedded/test/interceptor/PriorityExecutionTest.java
https://issues.redhat.com/browse/RESTEASY-3533
> [RESTEASY-3533] Incorporate usages of the resteasy-junit-extension 

- pom.xml
- resteasy-client-jetty/pom.xml
- resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientEngine.java
- resteasy-client-jetty/src/test/java/org/jboss/resteasy/test/client/jetty/MultipartTest.java
- resteasy-client-jetty/src/test/resources/META-INF/beans.xml
https://issues.redhat.com/browse/RESTEASY-3532
Upstream #4282
> [RESTEASY-3532] Ensure there is a boundary set for headers on the Jetty Client Engine. 

- pom.xml
- resteasy-client-jetty/pom.xml
- resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientEngine.java
- resteasy-client-jetty/src/test/java/org/jboss/resteasy/test/client/jetty/MultipartTest.java
- resteasy-client-jetty/src/test/resources/META-INF/beans.xml
https://issues.redhat.com/browse/RESTEASY-3532
> [RESTEASY-3532] Ensure there is a boundary set for headers on the Jetty Client Engine.

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3543
> [RESTEASY-3543] Upgrade Eclipse Angus mail to 2.0.3.

- resteasy-dependencies-bom/pom.xml
- https://issues.redhat.com/browse/RESTEASY-3543
- https://issues.redhat.com/browse/RESTEASY-3544
Upstream #4334
> [RESTEASY-3543] [RESTEASY-3544] Upgrade Apache Angus Activation and Mail

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/Student.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentJsonMergePatchTest.java
https://issues.redhat.com/browse/RESTEASY-2567
> [RESTEASY-2567] Extended JSON merge patch coverage

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3552
> [RESTEASY-3552] Upgrade Jetty to 12.0.15.

- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/Student.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentJsonMergePatchTest.java
- testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentPatchTest.java
* Removed redundant test
* Added test for patching a nested object
* Added test documentation
https://issues.redhat.com/browse/RESTEASY-2567
> [RESTEASY-2567] Added test for nested object

- pom.xml
- testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/setup/AbstractUsersRolesSecurityDomainSetup.java
- testsuite/integration-tests/pom.xml
https://issues.redhat.com/browse/RESTEASY-3559
Upstream #4418
> [RESTEASY-3559] Upgrade WildFly Arquillian to 5.1.0.Beta7.

- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Set this.defaultProxy before createDefaultHttpClient, cf. #6167e1534f6e2379cf0ad1074b34f87d13045e84
> Fix usage of defaultProxy

- resteasy-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RESTEASY-3654
> [RESTEASY-3654] Upgrade JUnit to 6.0.0.

- providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/MultipartEntityPartProviderTest.java
- resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
Issue: https://issues.redhat.com/browse/RESTEASY-3659
Includes #4697 and simply adds a test.
> [RESTEASY-3659] Allow multiple part form data to work with asynchronous invocations on proxies
